### ISSUE TITLE
Update??

### ISSUE THREAD

**Issue by FightingComa** [marzika/Snapprefs#10]
When are we getting a new update? I have been waiting for the update for a long time.

**Comment by inDream** [comment]
@FightingComa update has just released for version 9.11.0.0

**Comment by DDanielQ** [comment]
I can't post on xda so i write this here. Where is option in new update to save sent snaps? And when i'm exiting from settings snapprefs (from menu) always get a message "unfortunately snapprefs has stopped"

**Comment by marzika** [comment]
The exiting issue is fixed, saving sent snaps are removed temporaly, beta 3 already supports the latest version of SC.
