### ISSUE TITLE
Snapprefs doesn't work at all

### ISSUE THREAD

**Issue by AndoKarim** [marzika/Snapprefs#100]
Hello, first of all thank you for this module. 
Here is my configuration : Samsung S5 G900F, 6.0.1, rooted, xPosed installed. 
I activated Snapprefs on Xposed, rebooted etc. When I launch Snapprefs and configure it, no problem. But I can't use its feature (saving received snaps, etc). The only thing that worked was using a gallery image as a snap. 
I have the last version of Snapchat (maybe that's why it doesn't work?). 

Thank you for your help.

**Comment by NightMean** [comment]
Snapprefs works only with certain snapchat version,which is mention in xposed.. If you are using Snapprefs 1.6.5 use snapchat 9.21.1.0.
Next time do a little more research and don't open this as issue on Github and ask on G+ community or Reddit..

**Comment by AndoKarim** [comment]
I saw that to late, didn't now that a Gitter existed.. 
Sorry about that and thank you.
