### ISSUE TITLE
Pixlated videos

### ISSUE THREAD

**Issue by Whoknows14** [marzika/Snapprefs#102]
Thanks for all the work with this module. Everything works smooth with the current version that supports 9.21 but one thing I've noticed is that before when saving a video if the video contained stickers/smileys that covered someone face for example once the video is saved those stickers/enlarged smileys wouldn't save you'll see the video as if nothing was covering that person face I noticed lately that's not the case the video saved will show pixlated images where that sticker or smiley was. Wondering what caused the recent change

**Comment by NightMean** [comment]
Yes it's normal that the stickers or text which is on the video won't get saved.It was saving before but with newer updates it got removed because it caused saving issues.For pixelated video.. I will see if I see it too.

**Comment by marzika** [comment]
It's pixelated because in newer versions Snapchat have added that to protect the privacy of people who hide behind these emojis and stickers, it has nothing to do with Snapprefs and it is not possible to remove them.
