### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by kwest12** [marzika/Snapprefs#103]
Hi there, I've been on the same ROM with the most recent version of Snapchat and Snapprefs for months and months (if not longer.) Nothing has changed on my end, but for some reason I've started encountering a new bug in the past week. I have all saving of pictures and video being done by Sweep to Save (no automatic saving is enabled.) When I view someone's story, it'll sometimes randomly start saving everything automatically (and sometimes will save multiple copies of one picture.)  I haven't found a reliable way to fix the issue yet, although it seems a reboot may help. 

Is this something that you are aware of?

**Comment by hakankocyigit** [comment]
I had this error, but the error was not an alpha version than snapprefs

**Comment by marzika** [comment]
Random issues cannot take place, especially that major ones when nothing has been changed. The only thing I would think of is that these times when you open the snap your device hangs for a bit and registers as that the snap is started to be viewed and tracks the opening touch as a sweep,
