### ISSUE TITLE
Update Process 

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#104]
Not trying to sound like a dick aha I'm a regular Snapprefs user and im constantly swapping between 9.33 and 9.21.1.0 to get the features of snapprefs so first off 
Great work Marz 
second off do you plan for any live streams soon cause I know your study Dentistry and i know its coming to the end of your academic year

**Comment by NightMean** [comment]
This should be on Reddit or G+ not as an issue on Github..

**Comment by TehMerkMods** [comment]
link me the G+?

**Comment by NightMean** [comment]
Is it that hard to google ? anyway.. 
https://plus.google.com/communities/111884042638955665569

**Comment by TehMerkMods** [comment]
Well first thanks for the link and secondly sorta ;D

**Comment by marzika** [comment]
I will finish the new version when I have finished my exams. It has been said countless times and it does not have any place on Github.
