### ISSUE TITLE
[FC] Downgrading Snapchat

### ISSUE THREAD

**Issue by vintheword** [marzika/Snapprefs#105]
It's not possible anymore to downgrade to 9.21.1.

If you have 9.33.0 and try to downgrade it to 9.21 using XInstaller, the app opens and force closes 10 ~ 15 seconds later, probably file incompatibility.

Is there a way to extract the current SessionToken and use it on other versions? I know Casper can detect and use it to disguise itself as official app.

**Comment by marzika** [comment]
Either log directly into 9.21.1.0 or try this: https://www.reddit.com/r/xposed/comments/45674a/comment/czvrhto .
