### ISSUE TITLE
What additional fixes are needed?

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#108]
What fixes are needed so I can look into then later on tonight so I can attempt to build a working version

**Comment by edi194** [comment]
Search for /TODO in Obfuscator. As i can see, is needed to find strings for filters and stickers

**Comment by stirante** [comment]
Stickers got quite big update, so probably finding new class names won't be enough. About filters they are also changed a bit but not too much. Still needs few fixes. I'll try updating filters with marzika soon.

**Comment by datechnerd** [comment]
Jenkins's site doesn't load. Moto XT1575 Snapchat crashes with each save.

**Comment by TehMerkMods** [comment]
@datechnerd Saving been fixed and Jenkins idk who was hosting it but stopped if he gave me source to site id rehost it

**Comment by edi194** [comment]
What build're you using? With latest commits saving is working correctly

**Comment by datechnerd** [comment]
@edi184 I believe build #6

**Comment by edi194** [comment]
So you're using build what doesn't have commit with save fix, you need to build app byself

**Comment by TehMerkMods** [comment]
@edi184 Am i allowed to post updated build downloads?(generated apk)

**Comment by edi194** [comment]
Nope, Marż doesn't allow this.

**Comment by TehMerkMods** [comment]
@edi184 sucks for the little guys then ay xD

**Comment by datechnerd** [comment]
@TehMerkMods anyway you could make it available?  I've only got access to my phone. No computer until Friday.

**Comment by Sal7one** [comment]
@TehMerkMods so you made a working version?

**Comment by JacopoD** [comment]
@TehMerkMods The latest release on github is working!

**Comment by Sal7one** [comment]
@JacopoD with what version of SP ?

**Comment by JacopoD** [comment]
Snapchat 9.31.1.0
