### ISSUE TITLE
Snapprefs somehow does not work

### ISSUE THREAD

**Issue by hakankocyigit** [marzika/Snapprefs#109]
Snapchat 9.21.1.0 and Snapprefs 1.6.5 installed.
Snapprefs But why does it work?
Snapprefs has activated after installing and setting Snapprefs but did not work.

**Comment by krugm0f0** [comment]
Please try again. Uninstall and install, reboot, etc. it will work if your phone is properly set up and xposed is working.

**Comment by AmineI** [comment]
I guess this should be on reddit. + you must explain your problem or noone will be able to help. Does Snapchat launch ? Where is the problem ? What doesn't work ?
