### ISSUE TITLE
What version is the latest build set to

### ISSUE THREAD

**Issue by M1kep** [marzika/Snapprefs#110]
Hey there, so I saw that there are automatic builds now for dev-versions, just wanted to ask which version the the latest build(~1 day ago) set to?

Edit:

Nvm, found the version in the [Obfuscator class](https://github.com/marzika/Snapprefs/blob/stable/app/src/main/java/com/marz/snapprefs/Obfuscator.java): 9.31.1.0

**Comment by AmineI** [comment]
Read the commit name. It's not finished and won't work with 9.31.1.0 . + not an issue, should be on reddit
