### ISSUE TITLE
[Enhancement] Swipetosave could be disabled when looking at how many people have seen your story

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#112]
Set Swipetosave to false if the expandable viewing arrow is currently opened from the bottom of your story images/videos. Then when the expandable list is closed, swipetosave could be set to true again, this will avoid multiple copies of the same image/video being saved... If you want to see who's seen your story more than once, which I am sure most people do

**Comment by NightMean** [comment]
This was already mentioned a long time ago but I think Marz want to add block to save your story to prevent saving

**Comment by avi312singh** [comment]
Couldn't this just be done by putting the method for swipeToSave in a IF, and setting the expandable window as a boolean variable- which I am sure is already done somewhere because in 9.21.1.0 as volume is set to 0 whenever the viewing window is expanded... If the variable is found I cant imagine it would be that hard to add another IF statement for swipeToSave. I guess blocking saving your own story altogether could also work, as you can already choose if you want to save story automatically when posting in settings - so this is another solution...

**Comment by avi312singh** [comment]
This can be closed as this can be avoided with the save button :)

**Comment by roryclaasen** [comment]
@avi312singh However the save button is now always visible on the screen. Snapchat has its own save button for your own story however the Snapprefs save button is on top of this and it is still on top of the list when looking at how many people have seen your story

**Comment by marzika** [comment]
The new system by @Andrerm124 solves this issue.
