### ISSUE TITLE
Unlimited captions doesn't work

### ISSUE THREAD

**Issue by edi194** [marzika/Snapprefs#114]
Idk if FullCaption is this for unlim captions. They're enabled in Snapprefs, log from latest source build (commit d55e3ca5052e24b55354b5c5fe48e271186c2af8).
[xposed_error_20160727_011936.txt](https://github.com/marzika/Snapprefs/files/385009/xposed_error_20160727_011936.txt)

**Comment by marzika** [comment]
You don't have the feature enabled.

**Comment by edi194** [comment]
It's enabled in settings. Ok, i was tought it's problem with switcher in app, close this please
