### ISSUE TITLE
Root or Xposed hooking detecting 

### ISSUE THREAD

**Issue by haoning-yang** [marzika/Snapprefs#117]
I've just compiled and installed the new version of Snapprefs and Snapchat 9.31.1.0.
I restored my snapchat data und accept their Terms of Use and Privacy.
But the applications says i haven't accepted thei ToU & Privacy, and i can't use it.
If i disable Snapprefs, Snapchat works..

**Comment by tasiv** [comment]
you have to uninstall xposed, install snapchat, log in, reinstall xposed
and activate snapprefs.  snapchat looks for xposed framework now and
creates errors while logging in if xposed is present.

**Comment by haoning-yang** [comment]
yes. i unstalled xposed and then installed snapchat logged in and reinstalled xposed. 
If i activate snapprefs the app doesn't work. but if i disable snapprefs, snapchat works..
i don't know why.
i also tried RootCloak, but it isn't working also.

**Comment by johndoe245** [comment]
I compiled the latest version as well. I don't see the error that you have, but nothing works in snapprefs. How do people compile it and have it work?

**Comment by rebane2001** [comment]
@eliyameri I have the exact same problem, it won't attach to Snapchat (log: http://pastebin.com/eLe1QdfX) and some settings just crash the app

**Comment by johndoe245** [comment]
@rebane2001 the exact same thing happens to me. I installed it once without changing any settings and it doesn't work, so i'm guessing there's something we need to do

**Comment by a-elkaim** [comment]
Has anyone tried with the systemless xposed version ?

**Comment by johndoe245** [comment]
@azsde I'm using it with systemless xposed, but apparently snapprefs isn't hooking onto snapchat.

**Comment by haoning-yang** [comment]
oh well.. that's funny.. i reopened snapchat again without any changes on xposed or snapprefs. and snapchat works and it's saves pics and vids.. lol
