### ISSUE TITLE
Can't get the app to hook onto snapchat

### ISSUE THREAD

**Issue by johndoe245** [marzika/Snapprefs#118]
I compiled the latest apk, and downgraded my snapchat but none of the features work. I see many people here with working versions so i'm wondering what i'm either doing wrong or need to do.

I'll provide log if I need to, i'm just not sure how

Thanks!

**Comment by rebane2001** [comment]
Same problem here, log: http://pastebin.com/eLe1QdfX

**Comment by Sal7one** [comment]
@eliyameri 
@rebane2001 


what version of Snapchat do you use? 

try Snapchat 9.30.1.0

**Comment by rebane2001** [comment]
I use 9.31.1.0 since that was marked as the latest supported, I'll try 9.30.1.0 now

**Comment by marzika** [comment]
@rebane2001 L629 isn't even a valid line as it is commented out.

Logs are needed @eliyameri

**Comment by rebane2001** [comment]
@marzika I took a look at L23 of Obfuscator.java because I'm stupid and didn't find the version elsewere

**Comment by rebane2001** [comment]
Installed older Snapchat (0.30.1.0), rebooted, still the same problem, but a different cause, logfile: http://pastebin.com/xLUQYyFK

**Comment by marzika** [comment]
The app always supports the exact version that the Obfuscator.java states, not newer, not older.

**Comment by johndoe245** [comment]
@marzika sorry i'm not helping, but how do i get the logs?

**Comment by rebane2001** [comment]
@marzika I tried 9.30.1.0, which you suggested and 9.31.1.0, which is in the Obfuscator.java, both didn't work sadly :(

**Comment by rebane2001** [comment]
@eliyameri In snapprefs, you might need to turn on Debug mode (not sure). You'll find your logs in the Xposed Installers Log section

**Comment by johndoe245** [comment]
@rebane2001 alright. I'll get it now!

**Comment by marzika** [comment]
I did not suggest 9.30.1.0, some other guy did, whose comment I have already deleted as it was completly wrong.

**Comment by rebane2001** [comment]
@marzika Sorry about that, felt like it was you, anyways it still doesn't work. Here is the log: http://pastebin.com/eLe1QdfX (9.31.1.0)

**Comment by johndoe245** [comment]
i enabled debug mode, and i'm not getting a log like the one you posted, just a generic xposed log with all my modules

**Comment by rebane2001** [comment]
@eliyameri That is it, you just need to copy the part where snapprefs is included. I usually clear the log and run Snapchat, then I go back into the log

**Comment by johndoe245** [comment]
@rebane2001 ahh i didn't clear logs. I'll do that right now

**Comment by marzika** [comment]
I will not say it again. Your error in the log points to a line that is commented out, let alone is in an other method. Use the latest commits.

**Comment by johndoe245** [comment]
Umm... this is interesting. I don't get anything in my log when running snapchat.

**Comment by rebane2001** [comment]
@marzika I have the latest version, the same part in my code is also commented. I don't know why it does that then though?

I'll try to recompile

**Comment by rebane2001** [comment]
@marzika Could you please provide the apk of your build? It tried to build it any way possible but I still get the same error, so having a built apk would be awesome

**Comment by marzika** [comment]
@eliyameri If absolutely no lines are displayed regarding Snapprefs, then your system cannot load the module, because you probably ran it with Instant Run.

@rebane2001 Then tell me something: Your error strangely comes from the exact same line that the latest released app on the Xposed Repo has (https://github.com/marzika/Snapprefs/blob/8703eef7b5828caf8044f7ce08b026d55d4aef18/app/src/main/java/com/marz/snapprefs/HookMethods.java#L629). Another strange thing is that since with the addition of SaveButton the lenght of the saveModes array grew by one and your active module version only thinks that there is currentlength-1 items in the array it throws the ArrayIndexOutOfBoundsException.

All in all: you installed the latest app by building it, but haven't rebooted since then therefore the old module is loaded.

Please, both of you: read the wiki of the Xposed Bridge first on how to properly build apps for the Framework, then understand why a reboot is needed.

**Comment by rebane2001** [comment]
@marzika Actually, I did reboot, but only a soft one

**Comment by rebane2001** [comment]
Okay, I got it to work @eliyameri 
What I did was I firstly, disabled the xposed module, then I did a full reboot (not soft reboot)
After that I enabled the module and did a full reboot once more and got it to work

**Comment by eliyameri** [comment]
@rebane2001 Thanks for letting me know! I'll try it out soon

**Comment by dkisselev** [comment]
fyi for you guys, Instant Run doesn't cause modules to disappear from the logs. Xposed will still specify in the log that it tried to load the module and failed because of Instant Run.

**Comment by johndoe245** [comment]
@dkisselev yeah, i didn't know that instant run messes with modules. I have everything sorted out thanks to everyone here!
