### ISSUE TITLE
[BUG] Sponsored snaps are not hidden

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#119]
When I use the option to hide them they do not hide.

**Comment by marzika** [comment]
I need a log.

**Comment by ahmedtsadek** [comment]
07-31 01:09:09.765 I/Xposed  (31903): ----------------- SNAPSHARE STARTED -----------------
07-31 01:09:09.765 I/Xposed  (31903): SnapPrefs: Intent type: null, intent action:android.intent.action.MAIN
07-31 01:09:09.765 I/Xposed  (31903): SnapPrefs: Regular call of Snapchat.
07-31 01:09:09.765 I/Xposed  (31903): SnapPrefs: SNAPCONTEXT, NULL? - false
07-31 01:09:09.824 I/Xposed  (31903): SnapPrefs: Skipping VisualFilters
07-31 01:09:09.837 I/Xposed  (31903): Adding g.png
07-31 01:09:09.837 I/Xposed  (31903): Adding AFS.png
07-31 01:09:09.837 I/Xposed  (31903): Adding ninja.png
07-31 01:09:09.837 I/Xposed  (31903): Adding Simpson.png
07-31 01:09:09.837 I/Xposed  (31903): Adding AFS2.png
07-31 01:09:09.841 I/Xposed  (31903): SnapPrefs: Error while blocking Channel Intro Download
07-31 01:09:09.841 I/Xposed  (31903): SnapPrefs: java.lang.NoSuchMethodError: FC#b(android.database.Cursor)#exact
07-31 01:09:09.904 I/Xposed  (31903): SnapPrefs: SNAPCONTEXT, NULL? - false
07-31 01:09:09.939 I/Xposed  (31903): SnapPrefs: Skipping VisualFilters
07-31 01:09:09.967 I/Xposed  (31903): Adding g.png
07-31 01:09:09.967 I/Xposed  (31903): Adding AFS.png
07-31 01:09:09.967 I/Xposed  (31903): Adding ninja.png
07-31 01:09:09.967 I/Xposed  (31903): Adding Simpson.png
07-31 01:09:09.967 I/Xposed  (31903): Adding AFS2.png
07-31 01:09:09.968 I/Xposed  (31903): SnapPrefs: Error while blocking Channel Intro Download
07-31 01:09:09.968 I/Xposed  (31903): SnapPrefs: java.lang.NoSuchMethodError: FC#b(android.database.Cursor)#exact

**Comment by marzika** [comment]
Fixed https://github.com/marzika/Snapprefs/commit/d9a32750d34a9070d337ba550825207cb37ffb38
