### ISSUE TITLE
Bootloop on Intel x86 device

### ISSUE THREAD

**Issue by itsarjunsinh** [marzika/Snapprefs#12]
I have an Asus ZenFone 5. Applying this module ends up in a bootloop. Tried 1.4.3 beta 3 and beta 2. .Android version: 5.0

**Comment by itsarjunsinh** [comment]
Logcat
SDK: v21
Xposed version: v69 (tried v68) as well. 
Logcat: https://shrib.com/mdokl93R

**Comment by marzika** [comment]
It should be an issue with Xposed for x86. I used to test my stuff on an
x86 emulator, but Snapchat crashes since they dropped the libs for x86
devices.

Arjunsinh Jadeja notifications@github.com ezt írta (2015. augusztus 6.,
csütörtök):

**Comment by itsarjunsinh** [comment]
Update:
Snapprefs v1.6.3
Snapchat v9.20.2.0 
It's working. Just thought I'd post an update.
