### ISSUE TITLE
Automatic and button Saving

### ISSUE THREAD

**Issue by SlayaMods** [marzika/Snapprefs#121]
Automatic and button saving doesn't seem to work on on received snaps on snapchat v9.31.1.0 although sweep to save works fine on stories and received snaps, the button works on stories but sometimes disappears, When I try to use automatic saving it pops up that this image is already saved but when i go to the save location it shows the image is corrupted. And i know there has been similar issues but i'm not sure if its the same issue since i didn't get the multiple notifications

**Comment by marzika** [comment]
Same issue. The commit message even says that the button disappears occasionally.

https://github.com/marzika/Snapprefs/issues/84
