### ISSUE TITLE
I need again the Module

### ISSUE THREAD

**Issue by IkerFuenmayor** [marzika/Snapprefs#123]
Hi, I have time looking bugs in Snapprefs 9.31.1.0 , but I had to reset my phone and did not realize the support of the apk . I could go again the latest version in which they work ? Thanks guys.

GalaxyS4Mini creator Roms .

**Comment by AmineI** [comment]
(Not an issue) What's the question here ? You want the module apk link ?
Note that Marz' has prohibited to share debug apks, so if you really want to help you need to compile it yourself.
