### ISSUE TITLE
Jenkins snapshot link unavailable.

### ISSUE THREAD

**Issue by code-issues-pull** [marzika/Snapprefs#124]
Just letting you know, that is all.

**Comment by TehMerkMods** [comment]
@tomose I Already asked someone for the latest build of the Jenkins site and ill host it but it not ill just make a site if @marzika gives me permissions to host latest builds on the site

**Comment by code-issues-pull** [comment]
Alrighty. Just wanted marzika to be aware that he should either update or remove that link. :) Still looking forward to the official xposed update when it happens.
