### ISSUE TITLE
Found an unexpected entry at stories TYPE

### ISSUE THREAD

**Issue by Howley1** [marzika/Snapprefs#125]
I am using:
SnapPrefs: 1.6.5
Snapchat: 9.31.1.0
and I am 90% sure I have compiled the app correctly, but when I look at the log after saving some stories I see the following:

> SnapPrefs: Found an unexpected entry at stories TYPE: PT
> or 
> SnapPrefs: Found an unexpected entry at stories TYPE: Qp

From what I can see the stories I am looking at do get saved.

**Comment by marzika** [comment]
You don't have the latest commits.

https://github.com/marzika/Snapprefs/blob/stable/app/src/main/java/com/marz/snapprefs/Obfuscator.java#L256-L257
