### ISSUE TITLE
Data Saving not working

### ISSUE THREAD

**Issue by ahmedtsadek** [marzika/Snapprefs#126]
A same issue that been told before and here are the same errors even after updating after your last updates 2 hours ago still same error
Xposed (31903): SnapPrefs: Error while blocking Channel Intro Download
Xposed (31903): SnapPrefs: java.lang.NoSuchMethodError: FC#b(android.database.Cursor)#exact

**Comment by marzika** [comment]
The application no longer contains any of those strings. You are running a version that doesn't have the latest changes. https://github.com/marzika/Snapprefs/commit/d9a32750d34a9070d337ba550825207cb37ffb38#diff-bf4a3df43084c515523e4302d0c1f164L132
