### ISSUE TITLE
[BUG] Snapchat FC on chat

### ISSUE THREAD

**Issue by krugm0f0** [marzika/Snapprefs#128]
Snapchat force closes on swiping right to open chat. Have this been seen by others?

I am using lastest snapprefs commits, buildt the apk a few hours after the last update with discovery blocking, and SC 9.31.1.0. It also happenes on the previous build.

I usually logcat with adb, but I'm at work right now. What app do you recommend to logcat from phone so I can look into the issue myself?

**Comment by systemallica** [comment]
This doesn't happen to me. Are you sure that you have the latests commits and you built the apk without any error? you can also try to delete the app's cache and/or reinstall

**Comment by krugm0f0** [comment]
Seems to be an error on my end, a complete reinstall of SC, xposed and SP solved it.
