### ISSUE TITLE
[BUG] Snapprefs null pointer

### ISSUE THREAD

**Issue by Flouzr** [marzika/Snapprefs#129]
I just compiled the latest Snapprefs build (72e8d39) without any errors whatsoever. Attached is the logcat of what should be the crash. If anything else is needed please let me know.
[2016-08-01-17-40-51.txt](https://github.com/marzika/Snapprefs/files/394837/2016-08-01-17-40-51.txt)

**Comment by marzika** [comment]
08-01 17:40:27.912 E/Xposed  (9678): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
08-01 17:40:27.912 E/Xposed  (9678):    at com.marz.snapprefs.HookMethods.px(HookMethods.java:157)

points to a place where there is only a declaration of CaptionEditText, no calls for getResources is done there. Please delete both Snapchat and Snapprefs, pull the latest commits of Snapprefs and try again.

**Comment by Flouzr** [comment]
That seemed to have fixed it. Thank you!
