### ISSUE TITLE
[BUG] sc doesn't open 

### ISSUE THREAD

**Issue by dgc95** [marzika/Snapprefs#131]
Snapchat doesn't open when snapprefs is activated on Xposed 
Snapchat version 9.31.1.0
Snapprefs version 1.6.5

**Comment by SlayaMods** [comment]
You have to turn of some of your settings in snapprefs and it should work

**Comment by dgc95** [comment]
I turned off everything and still doesn't open

**Comment by SlayaMods** [comment]
Have you tried unistalling snapprefs and reinstalling it?

**Comment by dgc95** [comment]
Yes I tried and still the same issue. When I disable snapprefs on Xposed snapchat opens normally

**Comment by NightMean** [comment]
I have same issue with latest commits,I will try to experiment tonight

**Comment by krugm0f0** [comment]
I am using latest commits, and have not seen this problem. Full reinstall? Install SC,  log in, install xposed, install sp.

**Comment by NightMean** [comment]
I will try to build apk once more and clear snapprefs data,already reinstalled snapchat

**Comment by marzika** [comment]
I need the logcat of Snapchat.

**Comment by NightMean** [comment]
[2016-08-05-20-59-41.txt](https://github.com/marzika/Snapprefs/files/404439/2016-08-05-20-59-41.txt)
[xposed_error_20160805_210134.txt](https://github.com/marzika/Snapprefs/files/404440/xposed_error_20160805_210134.txt)
Here you go but I deleted Snapprefs Data and Snapchat works normally now.
Going to try if some option does this weird thing

Edit:Just found that if u accept Terms and open snapchat the notification to accept terms is still there.I had to force close snapchat to detect that I accepted it.

Edit2:I found that Custom Stickers are doing this when enabled

**Comment by marzika** [comment]
@NightMean 
It's because settings are not getting applied during runtime, but when the app is started from a clean state.

Custom Stickers were not working previously, https://github.com/marzika/Snapprefs/commit/689966c6f1cad3e188e1e1fc1b32f98bc78e846d solves them.
