### ISSUE TITLE
Bug Filters and Slow-Fast Video

### ISSUE THREAD

**Issue by NorvikScarlett** [marzika/Snapprefs#132]
When sharing a video, add a common filter or place the option of slow or fast, is not saved and is only shared as normal , unfiltered and speed.

**Comment by krugm0f0** [comment]
Sharing a video from gallery, or one taken with SC camera?

**Comment by NorvikScarlett** [comment]
When sharing video from gallery, I shared with more than 1 minute long and there is no problem, only if you add color filters or speed (snail, plane, squirrel) is not saved, shared, as if he had not added nothing but clean the video climbs

**Comment by krugm0f0** [comment]
Have you tried with a 10 sec long video?

**Comment by NorvikScarlett** [comment]
I also tried that but to no avail. The only thing that stays in the video editing is time, temperature, speed km/hr and geofiltros. There are also bug in the Stickers and visual filters (lomo, vintage, etc) but that is another issue.

**Comment by di0g0h** [comment]
I've got the same "bug", when a vídeo is shared from gallery and we apply a filter or disable thr sound, it doesnt upload the vídeo with these modifications

**Comment by NorvikScarlett** [comment]
I know... But @Marzika have solution soon
