### ISSUE TITLE
ToU and Privacy Policy

### ISSUE THREAD

**Issue by Abbasoo** [marzika/Snapprefs#133]
Can u please fix this.

![c90683aef42b631c5e727e4519344f85](https://cloud.githubusercontent.com/assets/20796710/17460374/1bdff89c-5c6c-11e6-9b12-66d50d5e62a9.png)

![80cd61a47e45402df65a139e2654cac7](https://cloud.githubusercontent.com/assets/20796710/17460375/2222ee3a-5c6c-11e6-9b10-0f8bbfcdc9a7.png)

![0e255618044a724b104848e1370dd0bb](https://cloud.githubusercontent.com/assets/20796710/17460376/2a4a119c-5c6c-11e6-8976-9ff0d3f50fd7.png)

**Comment by SlayaMods** [comment]
I tried to fix it but gave up and recoded it to make it so when it pops up in can click outside of it and it'll disappear so I can use it

**Comment by Abbasoo** [comment]
@SlayaMods I hope @marzika will fix this. cuz i tried like 10 times!

**Comment by SlayaMods** [comment]
What I've noticed is that it pops up when I go into the snapprefs app and then into Snapchat but it doesn't always happen, do you want help to do like a hot fix for temporary while we wait for a fix?

**Comment by Abbasoo** [comment]
@SlayaMods Yes. I forced stop Snapchat, and cleared the data of Snapprefs. Then Reopened Snapprefs and accept ToU. Now it works.
^ But it takes me an hour to start it.

**Comment by NorvikScarlett** [comment]
Uncheck the Stickers and closes both APK and see that it works.

**Comment by ghost** [comment]
It worked for me when i rebooted my phone after accepting the ToU

**Comment by marzika** [comment]
You have to either change a setting and force close Snapchat or restart your phone when you installed a new version. If I enabled the option to click outside of the dialog it would defeat it's purpose since without accepting it, you must not use the project.

**Comment by abby1208** [comment]
Please help me to get red of this , everytime i open snapchat i get this pop up of tou and privacy policy .Please help ASAP.

**Comment by krugm0f0** [comment]
Open Snapprefs app settings and clear its data. Open Snapchat. Accept 
ToU and PP. Exit Snapchat. Kill Snapchat. Open Snapprefs, change the 
settings to what you like. Open Snapchat. Should be ok. The thing is 
that after accepting the ToU/PP you have to change something in 
Snapprefs for it to take effect.

**Comment by MuhsinunCool** [comment]
@krugm0f0 that worked for me the first time, but now it's not working again. I had to do it again from the start since I didn't realize I had to actually select the settings I wanted for the final time...
