### ISSUE TITLE
Stories and my story

### ISSUE THREAD

**Issue by hakankocyigit** [marzika/Snapprefs#135]
Bug
Stories saver button does not work. (Some of)
I have to save the photos to see who's story
Snapchat version 9.31.1.0

**Comment by SlayaMods** [comment]
This has been knownamed and MARZ is working on the reason it's happening

**Comment by hakankocyigit** [comment]
@SlayaMods thanks

**Comment by SlayaMods** [comment]
No problem, just an fyi you can still use the save button even if it doesn't appear

**Comment by hakankocyigit** [comment]
(I know my english is a little poor) told me I could use the save button

**Comment by marzika** [comment]
Care to read the commit message? https://github.com/marzika/Snapprefs/commit/024eb1a31654d01259af8370aea28daa3f5e3f20
