### ISSUE TITLE
Duplicate images saved, story videos don't save

### ISSUE THREAD

**Issue by kenjamin80** [marzika/Snapprefs#137]
I tried the current available version that was on Xposed and caused the image to save multiple times, vibrating several times in a row. I tried uninstalling that and using the latest buildbot version, but I get the same result. Also, videos from snaps save, but story videos do not.

I am using a Nexus 6, everything stock except for rooted and using xposed.

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/issues/84
