### ISSUE TITLE
Missing location.png in drawables

### ISSUE THREAD

**Issue by notyal** [marzika/Snapprefs#14]
The following snippet of code is currently broken in `HookMethods.java`:

```
location.setImageDrawable(mResources.getDrawable(R.drawable.location));
```

Is it possible to add the proper `location.png` files in the various drawable folders?

**Comment by marzika** [comment]
Android Studio not to add the files for some reasons. You can find them here:

https://github.com/marzika/Snapprefs/commit/31484ff1fa3f842601a447048aa654b5c4c45897
