### ISSUE TITLE
Stickers aren't working

### ISSUE THREAD

**Issue by bobjoeshmoe** [marzika/Snapprefs#140]
I've tried multiple sticker packs from xda thread on it however they don't work. Is this a known issue? 9.21.1.0 used to work with my stickers but now they don't. 

Yes it is enabled in snapprefs

I am currently on 9.31.1.0 with the latest compiled snapprefs

**Comment by NorvikScarlett** [comment]
It works perfectly in version 9.31.1.0, if you're observant, Marzika explains how to operate the Stickers 5 days ago...

**Comment by bobjoeshmoe** [comment]
@NorvikScarlett I have been busy these last days, is there a link to it I can follow?

**Comment by NorvikScarlett** [comment]
Here Bro! https://github.com/marzika/Snapprefs/commit/689966c6f1cad3e188e1e1fc1b32f98bc78e846d >_<
![screenshot_1](https://cloud.githubusercontent.com/assets/20871030/17578005/af67feb8-5f49-11e6-9cfc-2d901b7eab0b.png)

**Comment by marzika** [comment]
Use it with the new needed name.
