### ISSUE TITLE
[Bug] Auto-save for chats when sending fails

### ISSUE THREAD

**Issue by bernito** [marzika/Snapprefs#142]
When you send a chat message and it fails, Snapprefs tries to save it either way.
This makes the "Remove all failed messages?" dialog to appear not once but near 10 times, one after another, and no matter what's your answer (Yes/No) it keeps appearing, ignoring whatever your answer was (the failed message doesn't get removed).

**Comment by igresso** [comment]
I have this problem before, but I think I have it only when I was not getting good internet connection. Just saying.
