### ISSUE TITLE
Not getting unlimited caption 

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#144]
Latest build 
SC version 9.31.1.0
SP version -newest build- 
Unl captions are enabled and still.nothing 
Has it not been updated?

**Comment by NorvikScarlett** [comment]
Try to push the top option [ " T" ] once or twice and that way you can place text without limits.

**Comment by marzika** [comment]
Works flawlessly for me.

**Comment by avmabrie** [comment]
Unlimited fat captions work. Regular captions are limited even when pressing the "T" a few times

**Comment by marzika** [comment]
I need the Xposed log to back up your claim.

**Comment by TehMerkMods** [comment]
http://www.tehmerkmods.xyz/xposed.log

**Comment by avmabrie** [comment]
https://drive.google.com/file/d/0BzSweYAIh8HcUEpXN012VFZDWGs/view?usp=drivesdk

**Comment by M1kep** [comment]
I don't have the issue on a nexus 6p

**Comment by marzika** [comment]
@TehMerkMods your log doesn't show any reason why it would not work, it even says that it's getting unlimited.

@avmabrie You don't even have the latest commits...

**Comment by TehMerkMods** [comment]
@marzika Well i can record a video if you would like. Anyways besides that the unlimited Fat captions work just not the slim one with that black bar?

**Comment by edi194** [comment]
I have same problem. I have no idea why it's 'working' that's way.
Nexus 5/ CM13 CAF

**Comment by TehMerkMods** [comment]
@marzika that's too many people saying there are issues for it to not need a fix bud

**Comment by o0Sevenfold0o** [comment]
I have the same issue here. Unlimited fat captions works fine but unlimited regular captions just doesn't work.

**Comment by marzika** [comment]
Please record then. Show in that you have the settings enabled for both, force close Snapchat, show the build number of Snapchat (not that it is 9.31.1.0, but 847), open Snapchat, take a picture, type in the caption and press the new line button 4-5 times, then type.

**Comment by TehMerkMods** [comment]
@marzika first step for me is finding where the build number is xD

**Comment by TehMerkMods** [comment]
@marzika https://youtu.be/POQdRWWnVbQ

**Comment by marzika** [comment]
Ahh, it changes everything, I thought you cannot even do multiple lines. I will fix it in the afternoon.

**Comment by TehMerkMods** [comment]
@marzika well one little bug at a time aye BTw I seen that you updated the video time to 200 mins but I am still limited to 10secs

**Comment by marzika** [comment]
Fixed in https://github.com/marzika/Snapprefs/commit/0d26f818520aae99427bdaf1f1447022ed56c786
Please open a new issue if the error still happens.
