### ISSUE TITLE
Unlimited video length

### ISSUE THREAD

**Issue by M1kep** [marzika/Snapprefs#145]
Not sure if this was an intentional removal, but previous version(the one for 9.21.xxx) I could record unlimited length videos but now it doesn't seem to work, here's the xposed log:

08-13 09:24:53.775 I/Xposed  (21819): SnapPrefs: SNAPCONTEXT, NULL? - false
08-13 09:24:53.800 I/Xposed  (21819): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-13 09:25:05.831 I/Xposed  (21819): SnapPrefs: We have the URI file:///data/user/0/com.snapchat.android/cache/snaps/preview/tracked_video_8784583165966075373.mp4.nomedia
08-13 09:25:05.831 I/Xposed  (21819): SnapPrefs: We have the URI file:///data/user/0/com.snapchat.android/cache/snaps/preview/tracked_video_8784583165966075373.mp4.nomedia
08-13 09:25:05.831 I/Xposed  (21819): SnapPrefs: We have the URI file:///data/user/0/com.snapchat.android/cache/snaps/preview/tracked_video_8784583165966075373.mp4.nomedia
08-13 09:25:05.831 I/Xposed  (21819): SnapPrefs: We have the URI file:///data/user/0/com.snapchat.android/cache/snaps/preview/tracked_video_8784583165966075373.mp4.nomedia
08-13 09:25:05.832 I/Xposed  (21819): SnapPrefs: We have the URI file:///data/user/0/com.snapchat.android/cache/snaps/preview/tracked_video_8784583165966075373.mp4.nomedia
08-13 09:25:05.836 I/Xposed  (21819): CLEARING ADDED
08-13 09:25:05.836 I/Xposed  (21819): CLEARING ADDED
08-13 09:25:05.836 I/Xposed  (21819): CLEARING ADDED
08-13 09:25:05.836 I/Xposed  (21819): CLEARING ADDED
08-13 09:25:05.836 I/Xposed  (21819): CLEARING ADDED
08-13 09:25:05.965 I/Xposed  (21819): SnapPrefs: Unlimited vanilla captions
08-13 09:25:05.988 I/Xposed  (21819): SnapPrefs: Called setColor: -65536
08-13 09:25:05.989 I/Xposed  (21819): SnapPrefs: Called setColor: -65536
08-13 09:25:05.989 I/Xposed  (21819): SnapPrefs: Called setColor: -65536
08-13 09:25:05.989 I/Xposed  (21819): SnapPrefs: Called setColor: -65536
08-13 09:25:05.989 I/Xposed  (21819): SnapPrefs: Called setColor: -65536
08-13 09:25:06.018 I/Xposed  (21819): Adding new filters
08-13 09:25:06.018 I/Xposed  (21819): Adding new filters
08-13 09:25:06.018 I/Xposed  (21819): Adding new filters
08-13 09:25:06.018 I/Xposed  (21819): Adding new filters
08-13 09:25:06.018 I/Xposed  (21819): Adding new filters

**Comment by M1kep** [comment]
Sorry log isn't in log format, for some reason my phone isn't  co-operating with that

**Comment by M1kep** [comment]
Also, I'm using the most recent version

**Comment by TehMerkMods** [comment]
@marzika @M1kep Also having this issue here @marzika you already got my xposed log but other than that i don't think this is implemented into the 9.31.1.0 build of SP yet

**Comment by marzika** [comment]
Fixed in https://github.com/marzika/Snapprefs/commit/26dfba57e5dbe95dad307a5dd925639159035f1e
Note that the size limit is still there (as it previously were too) and right now I haven't found a way to lift that.

**Comment by di0g0h** [comment]
i still have this bug with the build #15

**Comment by AmineI** [comment]
check your file size, please. Is it under ~2Mo ?

It's just over your post :

> Note that the size limit is still there
