### ISSUE TITLE
[REQUEST] Option to disable auto load next story

### ISSUE THREAD

**Issue by darke5tshad0w** [marzika/Snapprefs#146]
Option to return stories back to old function of choosing storys to watch, not choosing the first one then autoloading the next one. Don't always have time to watch all or only want to pick and choose etc.
On snapchat 9.31.1.0 and latest debug version as at 13/8/16, Nexus 5x, MM, PureNexus Rom

http://www.techinsider.io/turn-off-snapchat-stories-autoplay-feature-2016-3 
Thanks

**Comment by avi312singh** [comment]
This would be good, although I would imagine it would be hard to implement.. It would attract a lot of new potential users tho...

**Comment by darke5tshad0w** [comment]
If thats the case for him then its no problem, had to ask though lol.

**Comment by ShaRkK45** [comment]
Would love to see that enhancement.

**Comment by avi312singh** [comment]
Just to say this is available in the SR jenkins build, tick the option to disable story autoload in datasaving settings... Only th story you click will load - no further story will load... 
Snappers #23
Sc 9.31.1.0

**Comment by igresso** [comment]
@avi312singh Do u mean it is in build #23 ? cuz I'm in #18 and nothing prevent next friend story to show.

**Comment by avi312singh** [comment]
Well I'm on build #23 and its all good yeah.. The next story will not show after clicking on one friends story

**Comment by igresso** [comment]
Even in build #23 it still loading next story.

**Comment by marzika** [comment]
@avi312singh is talking about the Story Preloading blocking, while the others are talking about the Auto Advance blocking. Two entirely different things, the first is already added, the second is not added yet.

**Comment by marzika** [comment]
It has been already added, for the current version. For later versions, Snapchat has removed this feature.
