### ISSUE TITLE
Auto-save not working

### ISSUE THREAD

**Issue by crxed9** [marzika/Snapprefs#147]
Manual saving is working for me, but Auto save in normal snaps (image/video) does not seem to work. 
I get the red notification that says "image/video already exists" and the file gets saved with 0kb.

I tried to find an error with adb logcat, but there does not seem to be any error at the time of the save.

Build#15 (14-aug-2016 0:11:07) / Snapchat 9.31.1.0

**Comment by entlife** [comment]
I'm also having this issue. 

build.board: hammerhead
build.bootloader: HHZ12k
build.brand: google
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: hammerhead
build.display: cm_hammerhead-userdebug 6.0.1 MMB29X af2f753d61 test-keys
build.fingerprint: google/hammerhead/hammerhead:6.0.1/MMB29Q/2480792:user/release-keys
build.hardware: hammerhead
build.host: cyanogenmod
build.id: MMB29X
build.manufacturer: LGE
build.model: Nexus 5
build.product: hammerhead
build.radio: unknown
build.serial: 0baf3b07259c9a45
build.tags: test-keys
build.time: 1461020250000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: af2f753d61
version.release: 6.0.1
version.sdk_int: 23
08-14 14:18:51.961 I/Xposed  (12416): SnapPrefs: SNAPCONTEXT, NULL? - false
08-14 14:18:52.068 I/Xposed  (12416): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-14 14:18:52.084 I/Xposed  (12416): Adding 4ox5mo.png
08-14 14:18:52.212 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:52.213 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:52.215 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:55.008 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:55.009 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:55.010 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:56.135 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:18:56.135 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.139 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:18:56.139 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.141 I/Xposed  (12416): SnapPrefs: Image already exists
08-14 14:18:56.179 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:18:56.179 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.179 I/Xposed  (12416): SnapPrefs: Image already exists
08-14 14:18:56.190 I/Xposed  (12416): SnapPrefs: Exception while saving an image
08-14 14:18:56.195 E/Xposed  (12416): java.lang.IllegalStateException: Can't compress a recycled bitmap
08-14 14:18:56.195 E/Xposed  (12416): at android.graphics.Bitmap.checkRecycled(Bitmap.java:352)
08-14 14:18:56.195 E/Xposed  (12416): at android.graphics.Bitmap.compress(Bitmap.java:1019)
08-14 14:18:56.195 E/Xposed  (12416): at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:971)
08-14 14:18:56.195 E/Xposed  (12416): at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:962)
08-14 14:18:56.195 E/Xposed  (12416): at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-14 14:18:56.195 E/Xposed  (12416): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-14 14:18:56.195 E/Xposed  (12416): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-14 14:18:56.195 E/Xposed  (12416): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-14 14:18:56.195 E/Xposed  (12416): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-14 14:18:56.195 E/Xposed  (12416): at java.lang.Thread.run(Thread.java:818)
08-14 14:18:56.817 I/Xposed  (12416): SnapPrefs: FOUND VIDEOVIEW AS A CHILD - 2131691039
08-14 14:18:56.828 I/Xposed  (12416): SnapPrefs: Added To HashMap!
08-14 14:18:56.828 I/Xposed  (12416): SnapPrefs: Video snap opened
08-14 14:18:56.829 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.836 I/Xposed  (12416): SnapPrefs: Video snap opened
08-14 14:18:56.836 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.837 I/Xposed  (12416): SnapPrefs: Video already exists
08-14 14:18:56.856 I/Xposed  (12416): SnapPrefs: FOUND VIDEOVIEW AS A CHILD - 2131691039
08-14 14:18:56.856 I/Xposed  (12416): SnapPrefs: Added To HashMap!
08-14 14:18:56.857 I/Xposed  (12416): SnapPrefs: Video snap opened
08-14 14:18:56.857 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.857 I/Xposed  (12416): SnapPrefs: Video already exists
08-14 14:18:56.868 I/Xposed  (12416): SnapPrefs: Video snap opened
08-14 14:18:56.868 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.869 I/Xposed  (12416): SnapPrefs: Video already exists
08-14 14:18:56.878 I/Xposed  (12416): SnapPrefs: FOUND VIDEOVIEW AS A CHILD - 2131691039
08-14 14:18:56.878 I/Xposed  (12416): SnapPrefs: Added To HashMap!
08-14 14:18:56.879 I/Xposed  (12416): SnapPrefs: Video snap opened
08-14 14:18:56.879 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.880 I/Xposed  (12416): SnapPrefs: Video already exists
08-14 14:18:56.891 I/Xposed  (12416): SnapPrefs: Video snap opened
08-14 14:18:56.891 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:18:56.892 I/Xposed  (12416): SnapPrefs: Video already exists
08-14 14:18:57.126 I/Xposed  (12416): SnapPrefs: Video has been saved
08-14 14:18:57.128 I/Xposed  (12416): SnapPrefs: Path: /mnt/sdcard/zpix/jkraantje_2016-08-14_10-57-57-669.mp4
08-14 14:18:57.128 I/Xposed  (12416): SnapPrefs: MediaScanner started
08-14 14:18:57.412 I/Xposed  (12416): SnapPrefs: MediaScanner scanned file: content://media/external/video/media/17018
08-14 14:18:58.853 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:58.854 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:58.854 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:18:59.659 I/Xposed  (12416): SnapPrefs: StateBuilder.setScreenshotCount set to 0L
08-14 14:18:59.659 I/Xposed  (12416): SnapPrefs: StateBuilder.setScreenshotCount set to 0L
08-14 14:18:59.659 I/Xposed  (12416): SnapPrefs: StateBuilder.setScreenshotCount set to 0L
08-14 14:19:00.136 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:19:00.138 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:19:00.139 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:19:00.194 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:19:00.195 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:19:00.196 I/Xposed  (12416): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
08-14 14:19:00.680 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:19:00.680 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:19:00.683 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:19:00.683 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:19:00.686 I/Xposed  (12416): SnapPrefs: Image already exists
08-14 14:19:00.686 I/Xposed  (12416): SnapPrefs: Exception while saving an image
08-14 14:19:00.687 E/Xposed  (12416): java.lang.IllegalStateException: Can't compress a recycled bitmap
08-14 14:19:00.687 E/Xposed  (12416): at android.graphics.Bitmap.checkRecycled(Bitmap.java:352)
08-14 14:19:00.687 E/Xposed  (12416): at android.graphics.Bitmap.compress(Bitmap.java:1019)
08-14 14:19:00.687 E/Xposed  (12416): at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:971)
08-14 14:19:00.687 E/Xposed  (12416): at com.marz.snapprefs.Saving$saveImageJPGTask.doInBackground(Saving.java:962)
08-14 14:19:00.687 E/Xposed  (12416): at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-14 14:19:00.687 E/Xposed  (12416): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-14 14:19:00.687 E/Xposed  (12416): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-14 14:19:00.687 E/Xposed  (12416): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-14 14:19:00.687 E/Xposed  (12416): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-14 14:19:00.687 E/Xposed  (12416): at java.lang.Thread.run(Thread.java:818)
08-14 14:19:00.697 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:19:00.697 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:19:00.697 I/Xposed  (12416): SnapPrefs: Image already exists
08-14 14:19:00.843 I/Xposed  (12416): SnapPrefs: Added To HashMap!
08-14 14:19:00.844 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:19:00.844 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:19:00.844 I/Xposed  (12416): SnapPrefs: Image already exists
08-14 14:19:00.854 I/Xposed  (12416): SnapPrefs: Added To HashMap!
08-14 14:19:00.855 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:19:00.855 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:19:00.855 I/Xposed  (12416): SnapPrefs: Image already exists
08-14 14:19:00.863 I/Xposed  (12416): SnapPrefs: Added To HashMap!
08-14 14:19:00.863 I/Xposed  (12416): SnapPrefs: Image snap opened
08-14 14:19:00.863 I/Xposed  (12416): SnapPrefs: Mode: auto save
08-14 14:19:00.864 I/Xposed  (12416): SnapPrefs: Image already exists
08-14 14:19:03.615 I/Xposed  (12416): SnapPrefs: StateBuilder.setScreenshotCount set to 0L
08-14 14:19:03.615 I/Xposed  (12416): SnapPrefs: StateBuilder.setScreenshotCount set to 0L
08-14 14:19:03.615 I/Xposed  (12416): SnapPrefs: StateBuilder.setScreenshotCount set to 0L

**Comment by SlayaMods** [comment]
Guys guys, this has been a known issue and he has been working on other things that take priority over auto save because sweep to save and save button works

**Comment by crxed9** [comment]
Okay, thanks for the reply. I didn't see an issue topic for it, so that's why I created it.

Now we know.

**Comment by SlayaMods** [comment]
No problem I submitted the issue about a month ago and MARZ told me that is been an issue so I figured to inform you

**Comment by entlife** [comment]
Only reason I commented is because I asked on gitter and was told by a couple people including Marz that it works, but not for stories.

**Comment by igresso** [comment]
I confirm that in private snap, first there is message "error saving" so I pressed the download button in the corner , it says the video saved but when I opened gallery there is only broken video file.

The xposed log show exact same

SnapPrefs: StateBuilder.setScreenshotCount set to 0L

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/issues/84

**Comment by cephalovia** [comment]
Marzika ... I came up with a turn around to this issue from the settings and it did work. I created a folder inside DICM folder and set it to be my default snappref saving folder. I uncheched the other two sorting options. Working fine now. And hey, thanks a million for your magnificent work.
