### ISSUE TITLE
Captions on videos are not saved

### ISSUE THREAD

**Issue by crxed9** [marzika/Snapprefs#148]
When saving a video, the caption is lost.
This used to be saved in a seperate PNG file, but not on this version.

Build#15 (14-aug-2016 0:11:07) / Snapchat 9.31.1.0

**Comment by rebane2001** [comment]
Can confirm

**Comment by NightMean** [comment]
Saving captions is not a feature anymore.It caused saving issues in older version it was removed

**Comment by rebane2001** [comment]
If I screenshot the video caption, will a notification be sent to the image sender?

**Comment by NightMean** [comment]
Nope

**Comment by marzika** [comment]
It has been removed in 1.4.7.
@rebane2001 It will not be sent.
