### ISSUE TITLE
Crashing when trying to send any video

### ISSUE THREAD

**Issue by GroxicTinch** [marzika/Snapprefs#149]
Snapchat crashes when trying to send a video, it happens after pressing the button to get to the contact list and happens after about 4 seconds minus how long the video was, so a 4 second video crashes instantly after pressing, 1 second will last about 3 seconds. This is what happens in the logs when I record a video then try to send it.

[Pastebin](http://pastebin.com/yBpQmHZX)

`Xposed  (12888): java.lang.NoSuchMethodError: com.android.incallui.CallCardFragment#isVBHiddenByOverride()#exact
Xposed  (12888):   at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
Xposed  (12888):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
Xposed  (12888):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
Xposed  (12888):   at com.xanadu.xposed.cmoptions.XposedModule.handleLoadPackage(XposedModule.java:137)
Xposed  (12888):   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
Xposed  (12888):   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
Xposed  (12888):   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
Xposed  (12888):   at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
Xposed  (12888):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)`

I don't know what other info you need but I have a Samsung S5 with CM13 ROM which is Marshmallow 6.0.1using the xposed v86 sdk23 arm

**Comment by marzika** [comment]
The crash originates from com.xanadu.xposed.cmoptions.XposedModule.handleLoadPackage(XposedModule.java:137) . Snapprefs has nothing to do with it.
