### ISSUE TITLE
I can't save any chat images.

### ISSUE THREAD

**Issue by Ma7moodHD** [marzika/Snapprefs#151]
I already enabled "Chat image saving" feature but when i click and hold on the image it's saved in Snapchat not the device. 

Sorry for my english

**Comment by AmineI** [comment]
I think you must just click once on the image, if it's a chat image. I haven't tried since a while so I may be wrong.

**Comment by Ma7moodHD** [comment]
@Aminel If i click only once on the image that will expand it.

**Comment by AmineI** [comment]
>  If i click only once on the image that will expand it.

And save it to your save folder, inside a "chat" folder.

**Comment by Ma7moodHD** [comment]
@Aminel How i can save it? The only way is by taking a screenshot. That will reduce the resolution of tge image.

**Comment by AmineI** [comment]
It's not what I meant. If you click only once on the image it will expand it AND save it to the location you chose. 
EDIT : But I just tried and I was wrong. long click on it, pay attention to clicking on the picture and not the white space around it. Then check in your save folder :)

Which version are you using ? The one that support snapchat 9.21 ?

**Comment by Ma7moodHD** [comment]
@Aminel I'm using latest version from github with Snapchat 9.31.1.0

**Comment by Abbasoo** [comment]
@Ma7moodHD Same here. Not Working.

**Comment by AmineI** [comment]
Oh, latest version. That makes sense. Sorry !

**Comment by hakankocyigit** [comment]
I understand not saved snap. (my English is not good) I have no problem, I'm using latest version from github with Snapchat 9.31.1.0

**Comment by marzika** [comment]
Fixed in and added chat video saving https://github.com/marzika/Snapprefs/commit/33a589c0e6d672572f465837aaa1a3032d1849d7
