### ISSUE TITLE
Not recognising acceptance of ToS

### ISSUE THREAD

**Issue by lgdolman** [marzika/Snapprefs#152]
Xposed  ( 1125): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
08-16 14:03:40.441 I/Xposed  ( 1125):   Loading class com.marz.snapprefs.HookMethods
08-16 14:04:28.506 I/Xposed  ( 7564): ----------------- SNAPPREFS HOOKED -----------------
08-16 14:04:28.510 I/Xposed  ( 7564): SnapChat Version: 9.31.1.0 (847)
08-16 14:04:28.510 I/Xposed  ( 7564): SnapPrefs Version: 1.6.5 (24)
08-16 14:04:28.706 I/Xposed  ( 7564): 
08-16 14:04:28.706 I/Xposed  ( 7564): ~~~~~~~~~~~~ SNAPPREFS SETTINGS
08-16 14:04:28.706 I/Xposed  ( 7564): FullCaption: false
08-16 14:04:28.706 I/Xposed  ( 7564): SelectAll: false
08-16 14:04:28.706 I/Xposed  ( 7564): SelectStory: false
08-16 14:04:28.706 I/Xposed  ( 7564): SelectVenue: false
08-16 14:04:28.706 I/Xposed  ( 7564): HideBF: false
08-16 14:04:28.706 I/Xposed  ( 7564): HideRecent: false
08-16 14:04:28.706 I/Xposed  ( 7564): ShouldAddGhost: false
08-16 14:04:28.706 I/Xposed  ( 7564): TxtColours: false
08-16 14:04:28.706 I/Xposed  ( 7564): BgColours: false
08-16 14:04:28.706 I/Xposed  ( 7564): Size: false
08-16 14:04:28.706 I/Xposed  ( 7564): Transparency: false
08-16 14:04:28.706 I/Xposed  ( 7564): Rainbow: false
08-16 14:04:28.707 I/Xposed  ( 7564): Background Transparency: false
08-16 14:04:28.707 I/Xposed  ( 7564): TextStyle: false
08-16 14:04:28.707 I/Xposed  ( 7564): TextGravity: false
08-16 14:04:28.707 I/Xposed  ( 7564): mTimerCounter: true
08-16 14:04:28.707 I/Xposed  ( 7564): mChatAutoSave: true
08-16 14:04:28.707 I/Xposed  ( 7564): mChatImageSave: true
08-16 14:04:28.707 I/Xposed  ( 7564): mIntegration: true
08-16 14:04:28.707 I/Xposed  ( 7564): mPaintTools: true
08-16 14:04:28.707 I/Xposed  ( 7564): CustomFilters: false
08-16 14:04:28.707 I/Xposed  ( 7564): MultiFilters: true
08-16 14:04:28.707 I/Xposed  ( 7564): CustomFiltersLocation: /storage/emulated/0/Snapprefs/Filters
08-16 14:04:28.707 I/Xposed  ( 7564): CustomFilterType: 0
08-16 14:04:28.707 I/Xposed  ( 7564): mSpeed: false
08-16 14:04:28.707 I/Xposed  ( 7564): mWeather: false
08-16 14:04:28.707 I/Xposed  ( 7564): mLocation: false
08-16 14:04:28.707 I/Xposed  ( 7564): mStoryPreload: false
08-16 14:04:28.707 I/Xposed  ( 7564): mDiscoverSnap: false
08-16 14:04:28.707 I/Xposed  ( 7564): mDiscoverUI: false
08-16 14:04:28.707 I/Xposed  ( 7564): mCustomSticker: false
08-16 14:04:28.707 I/Xposed  ( 7564): mHideLive: false
08-16 14:04:28.707 I/Xposed  ( 7564): mHidePeople: false
08-16 14:04:28.707 I/Xposed  ( 7564): mReplay: false
08-16 14:04:28.707 I/Xposed  ( 7564): mStealth: false
08-16 14:04:28.707 I/Xposed  ( 7564): mTyping: false
08-16 14:04:28.707 I/Xposed  ( 7564): mUnlimGroups: false
08-16 14:04:28.707 I/Xposed  ( 7564): mForceNavbar: 0
08-16 14:04:28.707 I/Xposed  ( 7564): mColours: false
08-16 14:04:28.707 I/Xposed  ( 7564): ****_Debugging: false ***_*
08-16 14:04:28.708 I/Xposed  ( 7564): mLicense: 0
08-16 14:04:28.708 I/Xposed  ( 7564): ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
08-16 14:04:28.708 I/Xposed  ( 7564): ----------------------- SAVING SETTINGS -----------------------
08-16 14:04:28.708 I/Xposed  ( 7564): Preferences have changed:
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mModeSnapImage: SAVE_AUTO
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mModeSnapVideo: SAVE_AUTO
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mModeStoryImage: SAVE_AUTO
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mModeStoryVideo: SAVE_AUTO
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mOverlays: false
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mTimerMinimum: 0
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mToastEnabled: true
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mVibrationEnabled: true
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mToastLength: 1
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mSavePath: /storage/emulated/0/Snapprefs
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mSaveSentSnaps: false
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mSortByCategory: true
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mSortByUsername: true
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mTimerUnlimited: true
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mHideTimerStory: false
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mLoopingVids: true
08-16 14:04:28.708 I/Xposed  ( 7564): ~ mHideTimer: false
08-16 14:04:28.723 I/Xposed  ( 7564): SnapPrefs: ROOTCHECK: b
08-16 14:04:28.723 I/Xposed  ( 7564): SnapPrefs: ROOTCHECK: c
08-16 14:04:28.723 I/Xposed  ( 7564): SnapPrefs: ROOTCHECK: d
08-16 14:04:28.724 I/Xposed  ( 7564): SnapPrefs: ROOTCHECK: e
08-16 14:04:28.726 I/Xposed  ( 7564): SnapPrefs: SECOND_MAX_VIDEO_DURATION set over 10
08-16 14:04:28.808 I/Xposed  ( 7564): ----------------- SNAPSHARE HOOKED -----------------
08-16 14:04:28.808 I/Xposed  ( 7564): SnapChat Version: 9.31.1.0 (847)
08-16 14:04:28.808 I/Xposed  ( 7564): SnapPrefs Version: 1.6.5 (24)
08-16 14:04:28.815 I/Xposed  ( 7564): SnapPrefs: Hooked onCameraStateEvent
08-16 14:04:29.382 I/Xposed  ( 7564): ----------------- SNAPSHARE STARTED -----------------
08-16 14:04:29.382 I/Xposed  ( 7564): SnapPrefs: Intent type: null, intent action:android.intent.action.MAIN
08-16 14:04:29.382 I/Xposed  ( 7564): SnapPrefs: Regular call of Snapchat.

Just updated to latest version but each time I open Snapchat it requires me to go to snappers and accept the TOS.

Tried uninstalling and reinstalling accepting but the the issue still persists. Also tried clearing data and accepting but that didn't work either. I rebooted at each step too.

**Comment by marzika** [comment]
Open the Snapprefs app and change any option, force close Snapchat and it will work. Upon installing the for some reasons the system reads the default preferences instead of your own ones.
