### ISSUE TITLE
.

### ISSUE THREAD

**Issue by punpouet** [marzika/Snapprefs#153]
Hello, 
I'm using SC 9.31.1.0 and the lastest snapprefs build
I did set the save to sweep-to-save, but on snaps and stories, the save button is showing.
Is it a normal or a bug? It's a bit annoying not being able to hide the button.

Thanks for your help ! And sorry if someone already mentionned that "bug".

**Comment by SlayaMods** [comment]
This is new because MARZ has just fixed an issue with the save button not staying so he made it permanent for the time being

**Comment by punpouet** [comment]
Thanks alot! Another bug was that some filters made my snapchat crash or make my screen black but it's because it's not the lastest version I guess. Pretty impatient to use both snapprefs and bitmojis haha
