### ISSUE TITLE
anyone havw problem

### ISSUE THREAD

**Issue by ShtHappensBro** [marzika/Snapprefs#154]
With trying to load an old picture  ? It doesn't show my story for some reason using build #18. And Snapchat 9.31.1.0 or whatever it is lol  and on some of my Snapchat story's that people post some times I can't open them Snapchat force closes?  Any ideal  android note 2. Android version  4.2

**Comment by ShtHappensBro** [comment]
Ahhh I found the problem in Snapchat you know where u take the pictures and video it has the _^_ kinda like that and you press it takes you to you're  gallery (pictures) then when I select the pix I want to . Send  it goes back to Snapchat with the picture but when I want to send it.  It won't let me send it to my story  just to other  people.   So I exit Snapchat and I went to the picture it self and clicked on share and selected snapprefs  and it worked like that.  I don't know if its a bug or not

**Comment by marzika** [comment]
It works like that.
