### ISSUE TITLE
Latest commit break support for colour and text editor (Build #19)

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#155]
From the Jenkins build #19 is affected with the bug and #18 is good.

Snapchat would instantly crash on attempting to use either function. no logs in aLogcat from what i saw.

As of right now this can be solved by downgraded to build #18 because there was a clean up of unused functions for build #19 and it seems someone were mistakenly removed.

Sorry i was not able to get any logs. i will check if there were any produced from the crashes

[Commit ](https://github.com/marzika/Snapprefs/commit/d2172e67dd861d6d1c3c81adfabb5528c8251cd8) seems to be the culprit

Edit: minor bug ive noticed with #18 is that there do seem to be a few times where the editor will not show in #18 but it is solved with a reboot (seems to be random what parts show and dont. once the text editor showed but the colour editor didnt)

**Comment by CrilleTheBoss** [comment]
I can confirm, I have this issue as well in the latest build

**Comment by marzika** [comment]
Fixed in: https://github.com/marzika/Snapprefs/commit/9c88e03e7baad69ee71cb4fc0ea19b348d85eca4
