### ISSUE TITLE
Removing the Saving Button

### ISSUE THREAD

**Issue by ShaRkK45** [marzika/Snapprefs#157]
If its possible to hide the saving button when other methods are selected such as sweep to save or save automatically. Specially when I have friends looking over my Snaps ;p
Thanks. Testing the #19 atm.

**Comment by marzika** [comment]
This commit states that it is intentional and will be fixed. https://github.com/marzika/Snapprefs/commit/a37f062e2a333ec5f3684e28effbaca7f48a14e4
