### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by ShtHappensBro** [marzika/Snapprefs#159]
Updated snapprefs ? The webpage not found???  Weird?  Won't let me go to it and does snapprefs work with all versions of Snapchat?  BC on my phone Snapchat 9.31.1.0 is buggy my videos lags when I try to upload a video and the stories people post I can't view them sometimes force close my Snapchat?

**Comment by NorvikScarlett** [comment]
Try to compile the application (apk) yourself ....

**Comment by krugm0f0** [comment]
This is a work in progress. I believe the current official version of Snapprefs + Snapchat is 1.6.5 + 9.21.1.0.
To use versions other than that you will have to compile the apk yourself from source.

**Comment by marzika** [comment]
Sometimes I wonder what have I done in my life that I attract these people...
