### ISSUE TITLE
Blank files

### ISSUE THREAD

**Issue by mathispesch** [marzika/Snapprefs#160]
When using auto save with build #23, some snaps and stories aren't saved and a blank file (0 B) is created on the SD card. It seems that the only snaps correctly saved are those that aren't the first ones (first one doesn't get saved but the following do).
The error "this image already exists" is shown when enabling the notifications.

Here is the xposed log : http://pastebin.com/SgRXpzts

**Comment by SlayaMods** [comment]
Just to let you know this has been a known issue

**Comment by mathispesch** [comment]
But I hadn't this problem with the previous builds.

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/issues/88
