### ISSUE TITLE
Unlimited Video Length v Sharing

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#161]
So I have a video in my gallery which is longer than the snapchat timer and I can perfectly post this to my story/other people... However if I want to film a video which is longer than the default timer, it won't let me because as soon as the red circle goes full, SC goes to the editing screen for posting. Maybe some of the code could be reused, or is that nonsense?

**Comment by edi194** [comment]
https://github.com/marzika/Snapprefs/issues/145 known bug.
