### ISSUE TITLE
Hide certain people from stories bug

### ISSUE THREAD

**Issue by tomifier** [marzika/Snapprefs#164]
The persons story is not present in the list of stories that people posted but now with snapchat auto load story it shows the persons story which is supposed to be hidden..

**Comment by avi312singh** [comment]
It seems to work for me, enable BSP in data saving setttings.. Only the story you click on will load AND play - or at least that's what happens for me... No more people's story's will be played OR loaded...

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/issues/146
