### ISSUE TITLE
Can't send snaps with text

### ISSUE THREAD

**Issue by joneeze** [marzika/Snapprefs#165]
Whenever I put text longer than like 6-7 characters in a picture it won't send. Either nothing happens when I press the send button (download and reject buttons still work, but not the story button), or the app crashes.

**Comment by NightMean** [comment]
Post logs from xposed with Snapprefs debugging enabled and logcat

**Comment by joneeze** [comment]
@NightMean 
Maybe I need to strip this down... sorry I'm new with this.
[snap.txt](https://github.com/marzika/Snapprefs/files/428880/snap.txt)

**Comment by joneeze** [comment]
Seems to work now after I disabled Multi-filters...

**Comment by marzika** [comment]
It's because you have too many filters in the application.
