### ISSUE TITLE
Recording Timer is Limited

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#166]
I am not sure if this is known or not, but the recording timer for me stops when it reaches the end of the circle, is this just for me? Also there are numbers showing inside the circle as well.

**Comment by NightMean** [comment]
Yes it stops (I don't know if it's intended or not) The numbers in circle are counting how much the video is long,you can turn that off in General/Misc

**Comment by avi312singh** [comment]
OK thanks, if it's intended permanently that's ashame because that has been my main reason for SR's

**Comment by edi194** [comment]
https://github.com/marzika/Snapprefs/issues/145

**Comment by avi312singh** [comment]
So I am guessing it wasn't intended :)

**Comment by Sal7one** [comment]
@avi312singh Thank you i thought i was the only one

**Comment by marzika** [comment]
It should be resolved, try one of the new builds after https://github.com/marzika/Snapprefs/commit/67a72101258516682c1e54bcbd857c231456885e
