### ISSUE TITLE
Items in the downloaded filters folder are visible in gallery.

### ISSUE THREAD

**Issue by Freekystar** [marzika/Snapprefs#167]
**Snapprefs:** 2.00 BETA
**Snapchat version:** 9.31.0

**Issue:** Items in the downloaded filters folder are visible in gallery.

**Solution:** Auto-add .nomedia-file to the created folder.

**Comment by marzika** [comment]
I will not auto-add a .nomedia file into the folder, because some people (like me) prefer managing the filters from a gallery app. If people find it disturbing, the folder hiding option can place a .nomedia file there.
