### ISSUE TITLE
[Issue/Suggestion] - Downloadbutton size

### ISSUE THREAD

**Issue by Freekystar** [marzika/Snapprefs#168]
**Snapprefs:** 2.00 BETA
**Snapchat:** 9.31.1.0

**Issue/Suggestion:**  The downloadbutton covers a portion of the right corner but it's easy to click beside it and click away the image instead of saving. 

**Solution:** Downloadbutton that covers the whole right corner (the size of an index finger) so misclicking rarely happens.

**This is an example of my suggestion:**
![snapprefs](https://cloud.githubusercontent.com/assets/20667119/17838289/2821d986-67ca-11e6-90b5-1626e8d1641c.jpg)

Obviously the color can be different or even transparent but the button-coverage should be around that size.

**Comment by NightMean** [comment]
Agree 👍

**Comment by marzika** [comment]
It's not getting moved to the bottom since it will block the buttons of your own story's.
