### ISSUE TITLE
Question on compatibility 

### ISSUE THREAD

**Issue by SlayaMods** [marzika/Snapprefs#169]
I know it says it's for 9.31.1.0 but I see you are using 9.35 is that just for you @MARZ or is that working for everyone?

**Comment by NightMean** [comment]
9.31.1.0 is the only version that is currently supported (from newest) new updates will come later for new snapchat

**Comment by entlife** [comment]
Good question, I'm curious too. I'm happy as hell on 9.31.1.0 though.

**Comment by SlayaMods** [comment]
I realize that @nightmean but I'm just curious, I've been around long enough to know about the latest build of snapprefs

**Comment by blvcklotus** [comment]
@entlife I'm certainly not. It's so buggy for me, with or without Snapprefs and Xposed

**Comment by marzika** [comment]
I am using Snapchat on iOS, not on Android, that's why I am always on the latest.
