### ISSUE TITLE
[Request] Now Playing filter

### ISSUE THREAD

**Issue by 3mru** [marzika/Snapprefs#170]
Would love a Now Playing filter that displays the song you are playing on your phone with the album artwork just like snap plus on the iphone.

Thank you for your work really appreciate it.

**Comment by stirante** [comment]
Well, I was working on it, but it got delayed to the next version as well as some other new exciting features :D 
I think chances for Now Playing filter are like 90%

**Comment by SilverSix** [comment]
Oooh! A dynamic filter! Those sound amazing!! :dancer:

**Comment by stirante** [comment]
Actually I wanted to also add something like dynamic stickers with maybe hour and date, now playing one etc

**Comment by stirante** [comment]
Implemented
