### ISSUE TITLE
Snapchat force closes When attempting to hide stories

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#171]
Hey guys,

I'm getting a force close on Snapchat when clicking the Snapprefs button on Stories in order to hide specific people from my feed. (There is no popup of usernames allowing be to select names)

Here's a fresh logcat from xposed from opening Snapchat to the Force close.
http://pastebin.com/PL5ywfLh

Any more info needed just let me know.

**Comment by marzika** [comment]
Fixed in https://github.com/marzika/Snapprefs/commit/60e66dd3587a7eb68e5b97f50aaf75032a89c13f
