### ISSUE TITLE
Stories not marked as seen

### ISSUE THREAD

**Issue by SilverSix** [marzika/Snapprefs#172]
At this moment, any stories seen will not be marked as read and therefore will still be displayed on the top half of the list - ready to be seen again.

Snapprefs 2.0
Snapchat 9.31.1.0
Device: Samsung Galaxy S3 (Virgin Mobile)
OS: Exodus ROM (Marshmallow) - Android 6.0.1
Premium features not activated (no ghost viewing; regular snaps are being properly marked as seen)

**Comment by blvcklotus** [comment]
I have the same issue. LG G3 on Exodus as well. I'll have to watch the story and then swipe down and refresh to get it to remove sometimes

**Comment by SilverSix** [comment]
Issue is no longer present on my end. No settings were changed. ROM Build was updated after the issue was gone.

Perhaps exiting the app via force close rather than the "Back" button closed the app before it could tell the servers that it had seen the story.

I'll close this thread. If it comes up again, please start a new one. Thanks!

**Comment by flamery** [comment]
This is not related to snapprefs, I had the same issue on snapchat 9.31.1.0 a while ago with no snapprefs installed. I also agree it somehow corrected itself, most likely an issue on snapchat server side.
