### ISSUE TITLE
Snapprefs button on stories not working properly

### ISSUE THREAD

**Issue by smooter** [marzika/Snapprefs#173]
Here are my logs ; http://hastebin.com/nicovigora.coffee

5.1.1 - Galaxy s5 g900t - device

When I hit the logo button on the stories page, it just freezes snapchats and I have to close the app and reopen to get snapchat to work. Likely for the reason my hide story option not working.

at the bottom of the logs you can notice 
"atal signal 11 (SIGSEGV), code 1, fault addr 0x58 in tid 12598 (napchat.android)"
is when I hit the logo button

Everything else seems to work properly, excepted those effected by this issue.

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/issues/171
