### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by arismelachroinos** [marzika/Snapprefs#177]
is it possible when i save a text , to have the option of the ather person not seeing i saved it? so only i can read it whenever i want

**Comment by NightMean** [comment]
Noone knows if u saved text or no even without snapprefs

**Comment by arismelachroinos** [comment]
no,when u long press on a text or even an image on the chat,you and the other person can view it by swiping down on your chat. if the other person has saved it, you can't do anything unless that person "unsaves" it

**Comment by NightMean** [comment]
Okay then that's new for me I thought this haven't changed and the text save works just for my account

**Comment by arismelachroinos** [comment]
that's how I would like it to be,thats why I requested it

**Comment by SilverSix** [comment]
That is a Snapchat feature and it is not client side but server side. Therefore, I highly doubt SP can achieve the function you request. It's the same reason why it can't block Best Friends, which was a highly requested feature in 2015.

as far as I know, SP blocks all screenshot notices. I've screenshot a chat and the other user was never notified. If you wished to save chats and images (which SP does already) you could screenshot all chats and save them in a folder.

Perhaps a more plausible request would be to add a "screenshot chat" feature or a "read (saved) chats, save them in a text file or similar, then unsave them all."

**Comment by marzika** [comment]
Not possible.
