### ISSUE TITLE
snapprefs stickers? 

### ISSUE THREAD

**Issue by ShtHappensBro** [marzika/Snapprefs#178]
Some reason I download the dead pool sticker and ext them to snapprefs stickers kill Snapchat and reload it I don't see them stickers I just see the normal ones like the clock and stuff???  What am I doing wrong?

**Comment by NorvikScarlett** [comment]
Make sure that the path is correct and rename them as you indicated below:

•Path:

Snapprefs/Stickers/ (here files .zip)

•Rename:

twemoji_2_png.zip & twemoji_2_svg.zip

•Activate custum stickers in snapprefs and reborn

**Comment by ShtHappensBro** [comment]
Not working everything I do I can't get the dead pool one working or the other ones they don't show up at alll are is there a new place to download them?  From then the old place on XDA?

**Comment by NightMean** [comment]
Mr.Yawnie posted on xda correct way how to rename it I think in snapprefs is currently a typo.. 
http://forum.xda-developers.com/showpost.php?p=68290025&postcount=11103

**Comment by ShtHappensBro** [comment]
Alright awesome that seemed to work for ne
