### ISSUE TITLE
Cant use "Select All" feature

### ISSUE THREAD

**Issue by teamRockets** [marzika/Snapprefs#181]
Hey guys, I've been trying to use the feature "Select All" and it does select everything but as soon as I send my snap, It gives me "Failed to send, Tap to try again"

I think its because its selecting too many friends, I tried to select most of them manually without ticking select all and it let me, Any clue?

**Comment by marzika** [comment]
Snapchat's servers refuse to send to more than 200 at a time. Use groups and send them in smaller portions.
