### ISSUE TITLE
Unlimited video repeat not unlimites

### ISSUE THREAD

**Issue by M1kep** [marzika/Snapprefs#182]

**Comment by M1kep** [comment]
The video repeat stops after two or three repeats usually

**Comment by hakankocyigit** [comment]
@M1kep characterized in that :)

**Comment by SilverSix** [comment]
This issue was also present in the previous version of SP.

**Comment by avi312singh** [comment]
I think it depends on the length of the story, if the snap is short it will repeat for some time, but not if it's longer
