### ISSUE TITLE
Sending snaps

### ISSUE THREAD

**Issue by iiTranquility** [marzika/Snapprefs#183]
Whenever I send a snap with the Snapprefs filters, my Snapchat crashes.

A normal filter doesn't crash it.

**Comment by marzika** [comment]
Xposed log and Logcat is needed.

**Comment by zevozki** [comment]
Try this

http://forum.xda-developers.com/showpost.php?p=68621654&postcount=11634

Or this

http://forum.xda-developers.com/showpost.php?p=68448356&postcount=11459

**Comment by zevozki** [comment]
Sorry to hijack this issue but I want to say something it might be related to this similar issues. 

I have a theory and it needs developers to do experiments to prove it or reject it. When you launch a snapchat and immediately once the take picture button appears and you press it,  I doubt that the snapprefs app still not loaded completely at the same time which leads conflicts to crashes. However,  if you luanch snapchat and wait for couple seconds (letting snapprefs loads completely)  and then you start taken pictures there is a less tendency to crach.

So I hope someone have the time to test this.

**Comment by Sal7one** [comment]
@zevozki nice catch the first solution didn't work for me though i'll try the second one later

**Comment by M1kep** [comment]
@zevozki With the way Xposed works I'm pretty sure all the methods are hooked before you even see that button, but @stirante or @Andrerm124 could offer some more insight

**Comment by zevozki** [comment]
@M1kep so i can narrow it,  its possible the filters not fully loaded and that can cause a crash? 
I would love to hear from developers also.

**Comment by M1kep** [comment]
So I spoke with @Andrerm124 and he does agree that certain hooks can be affected, if your able to reproduce a crash and upload some logs that may be useful, MIGHT want to create a new issue at that point.

**Comment by zevozki** [comment]
Thanks for that.  I will try to squeeze some time to repreduce this problem.

**Comment by iiTranquility** [comment]
I have the Xposed logcat, but how would I do a normal logcat?

**Comment by Ketrel** [comment]
This app should be able to get it for you (requires root of course)

https://play.google.com/store/apps/details?id=com.nolanlawson.logcat

**Comment by stirante** [comment]
Isnt IT already fixed?
https://github.com/marzika/Snapprefs/commit/a543578f5bfaab47d5f9fd64488089032c542773

**Comment by lolololOMG** [comment]
09-26 22:18:58.519 E/Xposed  (29933):   at com.snapchat.android.ui.caption.CaptionEditText.a(SourceFile:206)
09-26 22:18:58.519 E/Xposed  (29933):   at com.snapchat.android.ui.caption.VanillaCaptionEditText.a(SourceFile:91)
09-26 22:18:58.519 E/Xposed  (29933):   at com.snapchat.android.ui.caption.SnapCaptionView.b(SourceFile:261)
09-26 22:18:58.519 E/Xposed  (29933):   at com.snapchat.android.ui.caption.SnapCaptionView.h(SourceFile:253)
09-26 22:18:58.519 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$32.onClick(SourceFile:1564)
09-26 22:19:01.107 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.onEditCaptionEvent(SourceFile:1065)
09-26 22:19:01.107 E/Xposed  (29933):   at com.snapchat.android.ui.caption.VanillaCaptionEditText.b(SourceFile:133)
09-26 22:19:01.107 E/Xposed  (29933):   at com.snapchat.android.ui.caption.CaptionEditText.onKeyPreIme(SourceFile:1225)
09-26 22:19:01.122 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.d(SourceFile:1137)
09-26 22:19:01.122 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.onEditCaptionEvent(SourceFile:1067)
09-26 22:19:01.122 E/Xposed  (29933):   at com.snapchat.android.ui.caption.VanillaCaptionEditText.b(SourceFile:133)
09-26 22:19:01.122 E/Xposed  (29933):   at com.snapchat.android.ui.caption.CaptionEditText.onKeyPreIme(SourceFile:1225)
09-26 22:19:03.414 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.414 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.414 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.414 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.414 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.414 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.414 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.414 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.419 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.419 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.419 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.419 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.419 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.419 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.419 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.419 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.420 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.420 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.420 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.421 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.421 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.421 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.422 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.422 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.422 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.423 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.423 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.423 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.424 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.424 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.424 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.425 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.425 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.425 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.425 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.425 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.425 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.425 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.425 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.427 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.427 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.427 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.427 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.427 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.427 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.427 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.427 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.428 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.428 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.428 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.428 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.428 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.428 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.428 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.428 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.429 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.429 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.429 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.429 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.429 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.429 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.429 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.429 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:03.430 E/Xposed  (29933): java.lang.NoSuchFieldError: com.snapchat.android.app.shared.model.filter.BatteryLevel#FULL_BATTERY
09-26 22:19:03.430 E/Xposed  (29933):   at com.snapchat.android.ui.SnapEditorView.l(SourceFile:1550)
09-26 22:19:03.430 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.O(SourceFile:2161)
09-26 22:19:03.430 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(SourceFile:2139)
09-26 22:19:03.430 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.l(<Xposed>)
09-26 22:19:03.430 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment.G(SourceFile:209)
09-26 22:19:03.430 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$14.run(SourceFile:1705)
09-26 22:19:03.430 E/Xposed  (29933):   at com.snapchat.android.preview.SnapPreviewFragment$15.onClick(SourceFile:1714)
09-26 22:19:06.634 E/AndroidRuntime(29933): Process: com.snapchat.android, PID: 29933
09-26 22:19:06.634 E/AndroidRuntime(29933):     at com.snapchat.android.LandingPageActivity.onSnapReadyForSendingEvent(SourceFile:50337)
09-26 22:19:06.634 E/AndroidRuntime(29933):     at com.snapchat.android.fragments.sendto.SendToFragment$10.a(SourceFile:442)
09-26 22:19:06.634 E/AndroidRuntime(29933):     at com.snapchat.android.fragments.sendto.SendToFragment$10.onClick(SourceFile:438)
09-26 22:19:06.635 W/ActivityManager(680):   Force finishing activity com.snapchat.android/.LandingPageActivity
09-26 22:19:07.167 W/ActivityManager(680): Activity pause timeout for ActivityRecord{2ee91e42 u0 com.snapchat.android/.LandingPageActivity t8222 f}
09-26 22:19:08.742 W/InputDispatcher(680): channel '2d0a5bb4 com.snapchat.android/com.snapchat.android.LandingPageActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-26 22:19:08.742 E/InputDispatcher(680): channel '2d0a5bb4 com.snapchat.android/com.snapchat.android.LandingPageActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-26 22:19:08.746 I/WindowState(680): WIN DEATH: Window{2d0a5bb4 u0 com.snapchat.android/com.snapchat.android.LandingPageActivity}
09-26 22:19:08.746 W/InputDispatcher(680): Attempted to unregister already unregistered input channel '2d0a5bb4 com.snapchat.android/com.snapchat.android.LandingPageActivity (server)'
09-26 22:19:08.847 I/ActivityManager(680): Process com.snapchat.android (pid 29933) has died
09-26 22:19:08.852 W/ActivityManager(680): Scheduling restart of crashed service com.snapchat.android/.util.chat.SecureChatService in 1000ms
09-26 22:19:08.852 W/ActivityManager(680): Scheduling restart of crashed service com.snapchat.android/.service.ScStickyService in 1175296ms
09-26 22:19:09.942 I/ActivityManager(680): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.snapchat.android/.LandingPageActivity bnds=[540,1021][777,1343](has extras)} from uid 10013 on display 0
09-26 22:19:09.950 D/LauncherLog(1620): Launcher:: startActivity: pkg: com.snapchat.android clz: com.snapchat.android.LandingPageActivity
09-26 22:19:10.017 I/ActivityManager(680): Start proc com.snapchat.android for activity com.snapchat.android/.LandingPageActivity: pid=30306 uid=10184 gids={50184, 9997, 3003, 1028, 1015} abi=armeabi-v7a
09-26 22:19:10.094 I/Xposed  (30306): SnapChat Version: 9.31.1.0 (847)
09-26 22:19:10.331 D/houdini (30306): [30306] Added shared library /data/app/com.snapchat.android-2/lib/arm/libSnapMediaUtils.so for ClassLoader by Native Bridge.
09-26 22:19:10.347 I/Xposed  (30306): SnapChat Version: 9.31.1.0 (847)
09-26 22:19:10.365 V/Monotype(30306): SetAppTypeFace- try to flip, app = com.snapchat.android
09-26 22:19:10.375 E/Vold    (239): Failed to find mounted volume for /storage/MicroSD/Android/data/com.snapchat.android/cache/
09-26 22:19:10.376 W/ContextImpl(30306): Failed to ensure directory: /storage/MicroSD/Android/data/com.snapchat.android/cache
09-26 22:19:10.423 D/houdini (30306): [30333] Added shared library /data/app/com.snapchat.android-2/lib/arm/libc++_shared.so for ClassLoader by Native Bridge.
09-26 22:19:10.491 D/houdini (30306): [30333] Added shared library /data/app/com.snapchat.android-2/lib/arm/libopencv.so for ClassLoader by Native Bridge.
09-26 22:19:10.610 D/houdini (30306): [30333] Added shared library /data/app/com.snapchat.android-2/lib/arm/liblooksery5.0.683.so for ClassLoader by Native Bridge.
09-26 22:19:10.653 V/Monotype(30306): SetAppTypeFace- try to flip, app = com.snapchat.android
09-26 22:19:10.820 I/Xposed  (30306): SnapPrefs: Regular call of Snapchat.
09-26 22:19:10.930 I/Xposed  (30306): Adding snapchat king.png
09-26 22:19:10.965 E/Xposed  (30306):   at com.snapchat.android.LandingPageActivity.onCreate(<Xposed>)
09-26 22:19:11.062 I/Xposed  (30306): Adding snapchat king.png
09-26 22:19:11.065 E/Xposed  (30306):   at com.snapchat.android.LandingPageActivity.onResume(<Xposed>)
09-26 22:19:11.178 I/Finsky  (28995): [10721] com.google.android.finsky.billing.iab.s.a(5210): com.snapchat.android: Account determined from installer data - [17R5RtOSEIT5fdbgahxHTEVAPoQ]
09-26 22:19:11.199 D/houdini (30306): [30410] Added shared library /data/app/com.snapchat.android-2/lib/arm/libsccrypto.so for ClassLoader by Native Bridge.
09-26 22:19:11.222 D/houdini (30306): [30410] Added shared library /data/app/com.snapchat.android-2/lib/arm/libscplugin.so for ClassLoader by Native Bridge.
09-26 22:19:11.402 E/Xposed  (30306):   at com.snapchat.android.camera.CameraFragment.a(SourceFile:660)
09-26 22:19:11.402 E/Xposed  (30306):   at com.snapchat.android.camera.BaseCameraFragment.onCreateView(SourceFile:93)
09-26 22:19:11.402 E/Xposed  (30306):   at com.snapchat.android.camera.CameraFragment.onCreateView(SourceFile:459)
09-26 22:19:11.408 E/Xposed  (30306):   at com.snapchat.android.camera.CameraFragment.a(SourceFile:660)
09-26 22:19:11.408 E/Xposed  (30306):   at com.snapchat.android.camera.BaseCameraFragment.onCreateView(SourceFile:93)
09-26 22:19:11.408 E/Xposed  (30306):   at com.snapchat.android.camera.CameraFragment.onCreateView(SourceFile:459)
09-26 22:19:11.486 E/Xposed  (30306):   at com.snapchat.android.camera.CameraFragment.onVisible(SourceFile:1028)
09-26 22:19:11.486 E/Xposed  (30306):   at com.snapchat.android.util.fragment.SnapchatFragment.h(SourceFile:403)
09-26 22:19:11.486 E/Xposed  (30306):   at com.snapchat.android.util.fragment.SnapchatFragment.ak(SourceFile:576)
09-26 22:19:11.486 E/Xposed  (30306):   at com.snapchat.android.camera.CameraFragment.onResume(SourceFile:913)
09-26 22:19:11.687 E/Xposed  (30306):   at com.snapchat.android.ui.chat.VideoNoteRecordingView.<init>(SourceFile:2325)
09-26 22:19:11.687 E/Xposed  (30306):   at com.snapchat.android.ui.chat.VideoNoteRecordingView.<init>(SourceFile:73)
09-26 22:19:11.687 E/Xposed  (30306):   at com.snapchat.android.fragments.chat2.ChatV2Fragment.onCreateView(SourceFile:299)
09-26 22:19:11.721 E/Xposed  (30306):   at com.snapchat.android.ui.chat.AudioNoteRecordingView.<init>(SourceFile:1248)
09-26 22:19:11.721 E/Xposed  (30306):   at com.snapchat.android.ui.chat.AudioNoteRecordingView.<init>(SourceFile:74)
09-26 22:19:11.721 E/Xposed  (30306):   at com.snapchat.android.fragments.chat2.ChatV2Fragment.onCreateView(SourceFile:299)
09-26 22:19:11.790 W/PackageManager(845): Failure retrieving resources for com.snapchat.android: Resource ID #0x0
09-26 22:19:11.873 W/PackageManager(845): Failure retrieving resources for com.snapchat.android: Resource ID #0x0
09-26 22:19:12.372 E/Vold    (239): Failed to find mounted volume for /storage/MicroSD/Android/data/com.snapchat.android/cache/
09-26 22:19:12.373 W/ContextImpl(30306): Failed to ensure directory: /storage/MicroSD/Android/data/com.snapchat.android/cache
09-26 22:19:13.571 I/Finsky  (28995): [10722] com.google.android.finsky.billing.iab.s.a(5210): com.snapchat.android: Account determined from installer data - [17R5RtOSEIT5fdbgahxHTEVAPoQ]
09-26 22:19:13.575 I/Finsky  (28995): [10721] com.google.android.finsky.billing.iab.s.a(5210): com.snapchat.android: Account determined from installer data - [17R5RtOSEIT5fdbgahxHTEVAPoQ]
09-26 22:19:13.939 I/ActivityManager(680): Killing 30306:com.snapchat.android/u0a184 (adj 16): remove task
09-26 22:19:14.054 W/ActivityManager(680): Scheduling restart of crashed service com.snapchat.android/.service.ScStickyService in 4701184ms
09-26 22:19:14.054 W/ActivityManager(680): Scheduling restart of crashed service com.snapchat.android/.util.chat.SecureChatService in 1000ms
09-26 22:19:14.054 W/ActivityManager(680): Scheduling restart of crashed service com.snapchat.android/.service.SnapchatService in 1000ms
09-26 22:19:15.118 I/ActivityManager(680): Start proc com.snapchat.android for service com.snapchat.android/.service.SnapchatService: pid=30488 uid=10184 gids={50184, 9997, 3003, 1028, 1015} abi=armeabi-v7a
09-26 22:19:15.177 I/Xposed  (30488): SnapChat Version: 9.31.1.0 (847)
09-26 22:19:15.383 D/houdini (30488): [30488] Added shared library /data/app/com.snapchat.android-2/lib/arm/libSnapMediaUtils.so for ClassLoader by Native Bridge.
09-26 22:19:15.399 I/Xposed  (30488): SnapChat Version: 9.31.1.0 (847)
09-26 22:19:15.414 V/Monotype(30488): SetAppTypeFace- try to flip, app = com.snapchat.android
09-26 22:19:15.420 E/Vold    (239): Failed to find mounted volume for /storage/MicroSD/Android/data/com.snapchat.android/cache/
09-26 22:19:15.422 W/ContextImpl(30488): Failed to ensure directory: /storage/MicroSD/Android/data/com.snapchat.android/cache
09-26 22:19:15.458 D/houdini (30488): [30515] Added shared library /data/app/com.snapchat.android-2/lib/arm/libc++_shared.so for ClassLoader by Native Bridge.
09-26 22:19:15.527 D/houdini (30488): [30515] Added shared library /data/app/com.snapchat.android-2/lib/arm/libopencv.so for ClassLoader by Native Bridge.
09-26 22:19:15.634 D/houdini (30488): [30515] Added shared library /data/app/com.snapchat.android-2/lib/arm/liblooksery5.0.683.so for ClassLoader by Native Bridge.

This is how I got crashed....

**Comment by M1kep** [comment]
We have recently pushed the development branch over to the stable branch in this we have resolved many issue, and added new functionalities. For the time being this build can be downloaded from: http://138.68.21.49:8080/job/SNAPPREFS%20-%20Official%20-%20stable/lastSuccessfulBuild/

**Please Note** This Version Is Built For SnapChat 9.39.5 **End Note**
If you cannot install this version as an update we recomend that you re-install this version. 

If this new build solves your issue please comment, and close the issue. Otherwise leave a comment stating this issue is still present.

**Comment by marzika** [comment]
If you still have the issue, please post the log here properly filtered.
