### ISSUE TITLE
Upload Button Crash

### ISSUE THREAD

**Issue by PedroC1999** [marzika/Snapprefs#184]
Getting a crash when the SnapPrefs Upload button (Within the camera UI, above the take snap button) is clicked and the gallery is open, if I then click to go back, SnapPrefs hangs and I have to long press the back button to kill the app, SnapPrefs is then killed and the camera is usable again

**Comment by marzika** [comment]
Xposed log and Logcat is needed.

**Comment by PedroC1999** [comment]
---

## Log file is larger than 2,048 kB, skipped first 4,174 kB

08-31 22:33:49.351 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:49.381 I/Xposed  (24816): SnapPrefs: SNAPCONTEXT, NULL? - false
08-31 22:33:49.441 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:49.511 E/Xposed  (24816): java.lang.NullPointerException: Attempt to get length of null array
08-31 22:33:49.511 E/Xposed  (24816):   at com.marz.snapprefs.Stickers.initStickers(Stickers.java:80)
08-31 22:33:49.511 E/Xposed  (24816):   at com.marz.snapprefs.HookMethods$1$1.afterHookedMethod(HookMethods.java:470)
08-31 22:33:49.511 E/Xposed  (24816):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:707)
08-31 22:33:49.511 E/Xposed  (24816):   at com.snapchat.android.LandingPageActivity.onResume(<Xposed>)
08-31 22:33:49.511 E/Xposed  (24816):   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java)
08-31 22:33:49.511 E/Xposed  (24816):   at android.app.Activity.performResume(Activity.java)
08-31 22:33:49.511 E/Xposed  (24816):   at android.app.ActivityThread.performResumeActivity(ActivityThread.java)
08-31 22:33:49.511 E/Xposed  (24816):   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java)
08-31 22:33:49.511 E/Xposed  (24816):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
08-31 22:33:49.511 E/Xposed  (24816):   at android.os.Handler.dispatchMessage(Handler.java)
08-31 22:33:49.511 E/Xposed  (24816):   at android.os.Looper.loop(Looper.java)
08-31 22:33:49.511 E/Xposed  (24816):   at android.app.ActivityThread.main(ActivityThread.java)
08-31 22:33:49.511 E/Xposed  (24816):   at java.lang.reflect.Method.invoke(Native Method)
08-31 22:33:49.511 E/Xposed  (24816):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
08-31 22:33:49.511 E/Xposed  (24816):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
08-31 22:33:49.511 E/Xposed  (24816):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
08-31 22:33:49.521 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:49.521 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:51.331 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:51.331 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:52.201 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:52.201 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:55.871 I/Xposed  (24816): SnapPrefs: SNAPCONTEXT, NULL? - false
08-31 22:33:55.871 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:55.881 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:55.901 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:55.951 E/Xposed  (24816): java.lang.NullPointerException: Attempt to get length of null array
08-31 22:33:55.951 E/Xposed  (24816):   at com.marz.snapprefs.Stickers.initStickers(Stickers.java:80)
08-31 22:33:55.951 E/Xposed  (24816):   at com.marz.snapprefs.HookMethods$1$1.afterHookedMethod(HookMethods.java:470)
08-31 22:33:55.951 E/Xposed  (24816):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:707)
08-31 22:33:55.951 E/Xposed  (24816):   at com.snapchat.android.LandingPageActivity.onResume(<Xposed>)
08-31 22:33:55.951 E/Xposed  (24816):   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java)
08-31 22:33:55.951 E/Xposed  (24816):   at android.app.Activity.performResume(Activity.java)
08-31 22:33:55.951 E/Xposed  (24816):   at android.app.ActivityThread.performResumeActivity(ActivityThread.java)
08-31 22:33:55.951 E/Xposed  (24816):   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java)
08-31 22:33:55.951 E/Xposed  (24816):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
08-31 22:33:55.951 E/Xposed  (24816):   at android.os.Handler.dispatchMessage(Handler.java)
08-31 22:33:55.951 E/Xposed  (24816):   at android.os.Looper.loop(Looper.java)
08-31 22:33:55.951 E/Xposed  (24816):   at android.app.ActivityThread.main(ActivityThread.java)
08-31 22:33:55.951 E/Xposed  (24816):   at java.lang.reflect.Method.invoke(Native Method)
08-31 22:33:55.951 E/Xposed  (24816):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
08-31 22:33:55.951 E/Xposed  (24816):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
08-31 22:33:55.951 E/Xposed  (24816):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
08-31 22:33:55.961 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:33:55.961 I/Xposed  (24816): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:34:00.681 I/Xposed  (14377): ----------------- SNAPPREFS HOOKED -----------------
08-31 22:34:00.701 I/Xposed  (14377): SnapChat Version: 9.31.1.0 (847)
08-31 22:34:00.701 I/Xposed  (14377): SnapPrefs Version: 2.0.0 beta (25)
08-31 22:34:00.921 I/Xposed  (14377): 
08-31 22:34:00.921 I/Xposed  (14377): ~~~~~~~~~~~~ SNAPPREFS SETTINGS
08-31 22:34:00.921 I/Xposed  (14377): SelectAll: true
08-31 22:34:00.921 I/Xposed  (14377): SelectStory: true
08-31 22:34:00.921 I/Xposed  (14377): SelectVenue: true
08-31 22:34:00.921 I/Xposed  (14377): HideBF: false
08-31 22:34:00.921 I/Xposed  (14377): HideRecent: false
08-31 22:34:00.921 I/Xposed  (14377): ShouldAddGhost: true
08-31 22:34:00.921 I/Xposed  (14377): mTextTools: true
08-31 22:34:00.921 I/Xposed  (14377): mTimerCounter: true
08-31 22:34:00.921 I/Xposed  (14377): mChatAutoSave: true
08-31 22:34:00.921 I/Xposed  (14377): mChatMediaSave: true
08-31 22:34:00.921 I/Xposed  (14377): mIntegration: true
08-31 22:34:00.921 I/Xposed  (14377): mPaintTools: true
08-31 22:34:00.921 I/Xposed  (14377): CustomFilters: true
08-31 22:34:00.921 I/Xposed  (14377): MultiFilters: true
08-31 22:34:00.921 I/Xposed  (14377): CustomFiltersLocation: /storage/emulated/0/Snapprefs/Filters
08-31 22:34:00.921 I/Xposed  (14377): CustomFilterType: 0
08-31 22:34:00.921 I/Xposed  (14377): mSpeed: true
08-31 22:34:00.921 I/Xposed  (14377): mWeather: true
08-31 22:34:00.921 I/Xposed  (14377): mLocation: true
08-31 22:34:00.921 I/Xposed  (14377): mStoryPreload: false
08-31 22:34:00.921 I/Xposed  (14377): mDiscoverSnap: true
08-31 22:34:00.921 I/Xposed  (14377): mDiscoverUI: true
08-31 22:34:00.921 I/Xposed  (14377): mCustomSticker: true
08-31 22:34:00.921 I/Xposed  (14377): mHideLive: true
08-31 22:34:00.921 I/Xposed  (14377): mHidePeople: true
08-31 22:34:00.921 I/Xposed  (14377): mReplay: false
08-31 22:34:00.921 I/Xposed  (14377): mStealth: false
08-31 22:34:00.921 I/Xposed  (14377): mTyping: false
08-31 22:34:00.921 I/Xposed  (14377): mUnlimGroups: false
08-31 22:34:00.921 I/Xposed  (14377): mForceNavbar: 0
08-31 22:34:00.921 I/Xposed  (14377): ****_Debugging: true ***_*
08-31 22:34:00.921 I/Xposed  (14377): mLicense: 0
08-31 22:34:00.921 I/Xposed  (14377): ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
08-31 22:34:00.921 I/Xposed  (14377): ----------------------- SAVING SETTINGS -----------------------
08-31 22:34:00.921 I/Xposed  (14377): Preferences have changed:
08-31 22:34:00.921 I/Xposed  (14377): ~ mModeSave: SAVE_BUTTON
08-31 22:34:00.921 I/Xposed  (14377): ~ mOverlays: false
08-31 22:34:00.921 I/Xposed  (14377): ~ mTimerMinimum: 0
08-31 22:34:00.921 I/Xposed  (14377): ~ mToastEnabled: true
08-31 22:34:00.921 I/Xposed  (14377): ~ mVibrationEnabled: true
08-31 22:34:00.921 I/Xposed  (14377): ~ mToastLength: 0
08-31 22:34:00.921 I/Xposed  (14377): ~ mSavePath: /storage/emulated/0/Snapprefs
08-31 22:34:00.921 I/Xposed  (14377): ~ mSaveSentSnaps: true
08-31 22:34:00.921 I/Xposed  (14377): ~ mSortByCategory: true
08-31 22:34:00.921 I/Xposed  (14377): ~ mSortByUsername: false
08-31 22:34:00.921 I/Xposed  (14377): ~ mTimerUnlimited: true
08-31 22:34:00.921 I/Xposed  (14377): ~ mHideTimerStory: false
08-31 22:34:00.921 I/Xposed  (14377): ~ mLoopingVids: true
08-31 22:34:00.921 I/Xposed  (14377): ~ mHideTimer: false
08-31 22:34:00.931 I/Xposed  (14377): SnapPrefs: ROOTCHECK: b
08-31 22:34:00.931 I/Xposed  (14377): SnapPrefs: ROOTCHECK: c
08-31 22:34:00.931 I/Xposed  (14377): SnapPrefs: ROOTCHECK: d
08-31 22:34:00.931 I/Xposed  (14377): SnapPrefs: ROOTCHECK: e
08-31 22:34:00.981 I/Xposed  (14377): SnapPrefs: Setting static fields
08-31 22:34:00.991 I/Xposed  (14377): ----------------- SNAPSHARE HOOKED -----------------
08-31 22:34:00.991 I/Xposed  (14377): SnapChat Version: 9.31.1.0 (847)
08-31 22:34:00.991 I/Xposed  (14377): SnapPrefs Version: 2.0.0 beta (25)
08-31 22:34:00.991 I/Xposed  (14377): SnapPrefs: Hooked onCameraStateEvent
08-31 22:34:01.501 I/Xposed  (14377): SnapPrefs: SNAPCONTEXT, NULL? - false
08-31 22:34:01.531 I/Xposed  (14377): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:34:01.561 E/Xposed  (14377): java.lang.NullPointerException: Attempt to get length of null array
08-31 22:34:01.561 E/Xposed  (14377):   at com.marz.snapprefs.Stickers.initStickers(Stickers.java:80)
08-31 22:34:01.561 E/Xposed  (14377):   at com.marz.snapprefs.HookMethods$1$1.afterHookedMethod(HookMethods.java:470)
08-31 22:34:01.561 E/Xposed  (14377):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:707)
08-31 22:34:01.561 E/Xposed  (14377):   at com.snapchat.android.LandingPageActivity.onCreate(<Xposed>)
08-31 22:34:01.561 E/Xposed  (14377):   at android.app.Activity.performCreate(Activity.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.app.ActivityThread.access$1100(ActivityThread.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.os.Handler.dispatchMessage(Handler.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.os.Looper.loop(Looper.java)
08-31 22:34:01.561 E/Xposed  (14377):   at android.app.ActivityThread.main(ActivityThread.java)
08-31 22:34:01.561 E/Xposed  (14377):   at java.lang.reflect.Method.invoke(Native Method)
08-31 22:34:01.561 E/Xposed  (14377):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
08-31 22:34:01.561 E/Xposed  (14377):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
08-31 22:34:01.561 E/Xposed  (14377):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
08-31 22:34:01.561 I/Xposed  (14377): ----------------- SNAPSHARE STARTED -----------------
08-31 22:34:01.561 I/Xposed  (14377): SnapPrefs: Intent type: null, intent action:android.intent.action.MAIN
08-31 22:34:01.561 I/Xposed  (14377): SnapPrefs: Regular call of Snapchat.
08-31 22:34:01.611 I/Xposed  (14377): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:34:01.611 I/Xposed  (14377): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:34:01.631 I/Xposed  (14377): SnapPrefs: SNAPCONTEXT, NULL? - false
08-31 22:34:01.651 I/Xposed  (14377): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
08-31 22:34:01.651 E/Xposed  (14377): java.lang.NullPointerException: Attempt to get length of null array
08-31 22:34:01.651 E/Xposed  (14377):   at com.marz.snapprefs.Stickers.initStickers(Stickers.java:80)
08-31 22:34:01.651 E/Xposed  (14377):   at com.marz.snapprefs.HookMethods$1$1.afterHookedMethod(HookMethods.java:470)
08-31 22:34:01.651 E/Xposed  (14377):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:707)
08-31 22:34:01.651 E/Xposed  (14377):   at com.snapchat.android.LandingPageActivity.onResume(<Xposed>)
08-31 22:34:01.651 E/Xposed  (14377):   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java)
08-31 22:34:01.651 E/Xposed  (14377):   at a

Sorry for the lack of code tabs etc, this is mobile GitHub

**Comment by marzika** [comment]
@PedroC1999 That log only shows that you have enable the Stickers option, but you don't have any stickers in the folder.

**Comment by marzika** [comment]
Fixed in https://github.com/marzika/Snapprefs/commit/2a261b8138af9c834c3fcbcba7ee5bcd1631bdff
