### ISSUE TITLE
Plethora of crash logs

### ISSUE THREAD

**Issue by MildPanda** [marzika/Snapprefs#185]
I have a droid turbo running on the latest version of Snapprefs/compatible snapchat and also latest version of cyanogenmod. 
Sorry I haven't kept what I did before the crash but hopefully the logs speak for them self. If not, let me know,
[Crashes.zip](https://github.com/marzika/Snapprefs/files/441418/Crashes.zip)

**Comment by marzika** [comment]
Fixed in the above mentioned commit and https://github.com/marzika/Snapprefs/commit/d91ba1992d2ca3255bb9bb0f87d3033e77e73485
