### ISSUE TITLE
[Enhancement] Temporary Sent Snap History

### ISSUE THREAD

**Issue by vintheword** [marzika/Snapprefs#187]
Every snap you sent people would be on a temp folder 
If you swipe to chat you would be able to see your sent unviewed snaps to that person
The temp snap would dissapear in the moment your snap is seen

This would be good to keep track on the sent content. Sometimes people start talking about your sented snaps in the morning when they got home from work/college at night and you simply have no idea, specially with Groups and the Select All button.

**Comment by DankMemeGuy** [comment]
This sounds like a good idea! Commenting to stay up-to-date with it :)

**Comment by marzika** [comment]
Too complex to be done withing Xposed and Snapchat.
