### ISSUE TITLE
[Issue] Message can't be sent - Autosave chat triggers prompt

### ISSUE THREAD

**Issue by Freekystar** [marzika/Snapprefs#188]
When a message can't be sent because of one of the following reasons:
- No connection (or servers down)
- Blocked by receiving user

Autosave tries to save the message that doesn't send and keeps popping up the 'Message can't be send' error. This can't be clicked away.

Workaround: Stop Snapchat app

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/issues/142
