### ISSUE TITLE
Feature Request: Hide certain people in Stories

### ISSUE THREAD

**Issue by DankMemeGuy** [marzika/Snapprefs#191]
We all have those few people who drown our Stories list with their 200 second stories daily. Would be nice if we could hide them from being shown?

**Comment by NightMean** [comment]
Already possible...

**Comment by avi312singh** [comment]
How do you do this? Where is it in SR interface?

**Comment by NightMean** [comment]
I don't have my second device charget but somewhere in snapprefs is setting to Block certain people stories when u enable it in snapchat stories menu u can see on the top purple snapchat logo which enables the hiding
Edit: General/Misc/Hide people from stories

**Comment by marzika** [comment]
See @NightMean 's comment.

**Comment by avi312singh** [comment]
Does SR interface need to be enable in SC for this to work?

**Comment by DankMemeGuy** [comment]
@NightMean @marzika what version is this we're talking about? The new beta?

**Comment by NightMean** [comment]
Yes 2.0.0 beta
