### ISSUE TITLE
Can only open 3 groups

### ISSUE THREAD

**Issue by teamRockets** [marzika/Snapprefs#193]
Is it possible to open more than 3 groups? It wont let me

**Comment by SilverSix** [comment]
What do you mean by "open" groups?

**Comment by teamRockets** [comment]
When I send a snap, I click on Edit Groups.
I've made 3 groups with 200 people on each, Now it wont let me open more groups, Only 3.

**Comment by marzika** [comment]
Only premium and deluxe users can have more than 3 groups.
