### ISSUE TITLE
Public Stories displaying as "friends"/"regular users"

### ISSUE THREAD

**Issue by SilverSix** [marzika/Snapprefs#196]
With both "Hide public stories" and "Hide Discover" settings turned on, as well as "Disable Story Pre-loading" active, some stories have slipped through the cracks. Two days ago I had a random user by the name of tomatina5 appear in my stories list. It was a public story for an event in Spain, The "Tomatina." Today, there's another story from "touristvegas16" that's a public story from Vegas.

Long-pressing on them brings up a menu to add or block them. Tried blocking them but there's a toast saying "Something went wrong" meaning that Snapchat does not allow or recognize the request, so the story cannot be hidden that way.

Furthermore, these stories cannot be hidden via Custom Story Hide as these accounts are not in your friendslist.

This issue was never seen before, and something, somehow, public stories are filtering through the cracks. I recall someone experiencing a similar issue, perhaps on the Snapprefs subreddit.

Technical info:
Snapchat 9.31.1, Snapprefs 2.0 beta
Device: Samsung Galaxy S3 (Virgin Mobile variant)
OS: Exodus ROM 6.0-20160901-nightly
Android version: 6.01_r62

**Comment by di0g0h** [comment]
I'm facing the same issue. I dont know if it is from public stories, I didnt check. It is not happening every day to me. 
I actually thought that it was a new feature that snapchat team was testing to discover new people.

Snapchat 9.31.1, Snapprefs 2.0 beta
Device: Huawei P8 (GRA-L09)
OS: emui 3.1 (huawei)
Android version: 5.0.1

**Comment by marzika** [comment]
I don't think it's caused by Snapprefs, but by Snapchat itself.
