### ISSUE TITLE
Question: Would you like an overhauled Saving system?

### ISSUE THREAD

**Issue by Andrerm124** [marzika/Snapprefs#197]
So I've taken an interest in this module lately and have entirely overhauled the saving system (On a fork that is). My system is, from my testings, 100% efficient, I have re-implemented the automatic saving feature and removed the Sweep to Save feature (As it had conflicts - The button save remains).

This system is far more efficient than the old one and I was just wondering if you'd like the source code for it. I appreciate I may be over stepping my boundaries but thought I'd offer in case you'd like to see it :)

Sorry for putting this in the issues section - I know it's not really an "issue"

EDIT: Just to clarify, this isn't something I've just rushed to get working. I've spent a pretty solid chunk of time planning and implementing though I am the only tester, nobody else has tested this system

**Comment by NightMean** [comment]
Does it have issues with saving on the second story saving or you resolved it :O ?

**Comment by Andrerm124** [comment]
No issues with that whatsoever :)

**Technical details:**
When opening a snap, there are two things that my system waits for until actually saving:
1.  Build a HEADER - This contains things like Sender, Timestamp, SnapType etc - Once this is done, add a HEADER flag to the snap.
2. Attach a PAYLOAD - This contains the Image or Video - Once this is done, add a PAYLOAD flag to the snap.

The above can happen in any order, it doesn't matter at all. Infact, when viewing a snap, the PAYLOAD of the next snap is actually pre-assigned so that all is required is the header packet to arrive.
Once both a header and payload is applied, the flag COMPLETED is assigned to the snap and it begins saving. This generally happens practically instantly so you don't even notice anything.

That's the short version of what's happening and probably doesn't mean much to most people but still thought I'd put it out there.

**Comment by godlesplay** [comment]
@Andrerm124 what if I prefer auto save for regular snaps and Sweep to Save for story? what conflict with it?

**Comment by Andrerm124** [comment]
@godlesplay Yeah I've thought about that and I could potentially implement it but right now I've completely ripped out the sweep functions. Besides you were limited to one saving type between the two.

I'll probably have to implement the s2s functions again before considering pushing my system

**Comment by NightMean** [comment]
May I have the apk for testing or will upload the source code to github so I can compile it ? :)

**Comment by Andrerm124** [comment]
@NightMean Right now I need to finish a few things - and before my code goes anywhere - I certainly need to re-enable the premium/deluxe checking functions. Sorry Marz :)

**Comment by NightMean** [comment]
Oh alright,I bought Premium anyway so .. :D May you send me the apk or the source code on gmail when it's finished or can you contact me somewhere ? :)

**Comment by Andrerm124** [comment]
@NightMean I appreciate you wanting to test it but until Marz gives the go ahead (Or until I create a Push Request) it's not my place to be "replacing" his system publicly. I hope you understand :)

**Comment by NightMean** [comment]
Oh yeah sure no problem,I'm just stuck on Lollipop on v9.17.1.0 which I think is the latest version which have no problems with auto-saving at all and I can't upgrade to marshmallow since the new version have problems :P :D

**Comment by Andrerm124** [comment]
@NightMean That's understandable. I'll see what I can do although there won't be anything today as I've not got much time to work on the app

**Comment by NightMean** [comment]
Yeah sure no problems do your things I don't want to pressure you for fixing the app :D

**Comment by marzika** [comment]
Make a pull request so I can review the code, however APKs must not be shared with anyone.

**Comment by Andrerm124** [comment]
@marzika I figured as much, I mostly just wanted to see the response to this before going any further. I'll probably be able to make the PR tomorrow some time

**Comment by Andrerm124** [comment]
@NightMean I've created a PR if you'd like to see the new system #199
