### ISSUE TITLE
Download reddit filter modal shrinks until unusable

### ISSUE THREAD

**Issue by craigjmidwinter** [marzika/Snapprefs#198]
The confirm/download modal when downloading filters from reddit directly within snap prefs initially loads at a reasonable size, but after a few downloads it shrinks to a point where it has disappeared. Clicking on filters now just greys out the screen

**Comment by marzika** [comment]
I don't really get the issue, could you please record your screen while reproducing the issue?

**Comment by craigjmidwinter** [comment]
Sorry, I'm having trouble reproducing the shrinking since the modal is now so tiny it can't be seen, but here is a video of the screen going grey as a modal should be coming into focus. I'm fairly sure that the modal is in the center, just that it has a size of 0px x 0px, though I could be wrong.

https://www.youtube.com/watch?v=yj_EL3YsJrs
