### ISSUE TITLE
[BUG]Filters

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#201]
Since SnapPrefs 2.0.0 release I'm having issues using filters 
They work buuuut they fucking lag like hell when swiping to them 
Any fix?
Cleared cache of device, SP and SC

**Comment by marzika** [comment]
Use less filters. Snapchat is a memory whore, even though the loading is done Async it lags a little.

**Comment by TehMerkMods** [comment]
@marzika I enabled 2 filters and it still lagged  also location spoofer map doesn't show anything

**Comment by marzika** [comment]
It's already being async, so I don't think I can lower the usage of it. The map doesn't show, because you are probably on a debug build.
