### ISSUE TITLE
Link not working - Latest automatic builds (provided by Dopeland): Jenkins artifacts

### ISSUE THREAD

**Issue by zevozki** [marzika/Snapprefs#205]
The link for automatic build is down

http://13.92.242.101:8080/job/SNAPPREFS/lastSuccessfulBuild/artifact/app/build/outputs/apk/

This site can’t be reached

The connection was reset.

**Comment by krugm0f0** [comment]
Just build the apk from source yourself, like the rest of us.

**Comment by zevozki** [comment]
Not every ppl have the knowledge or the accessibility using deployment tools for many reasons.  Just wanted to highlight link issue to the op,  and I dont mind to try to compile the source by myself.  Thanks for the tip.

**Comment by NightMean** [comment]
Jenkins builds are down because Marz wanted to update Gradle and he told us that he didnt received ip for it yet. Just wait ..

**Comment by zevozki** [comment]
Thanks for update. This issue is already known by the op.
