### ISSUE TITLE
Readd Rainbow coloring

### ISSUE THREAD

**Issue by zevozki** [marzika/Snapprefs#206]
I have noticed the rainbow coloring not exist in this version,  i tried to read the changes in the removed and its not mentioned also no one reported that in issue section. 

[Request]  is it possible to add rainbow coloring for word by word in addition to the existing coloring letter by letter?  that would be awesome

**Comment by marzika** [comment]
Snapchat already has the option to select a word or few letters and color them individually. I doubt anyone used rainbow coloring consistently. If wanted, I can add it back in no time.

**Comment by zevozki** [comment]
After reading your replay i checked sc and as you said its there and manually you can color letters or words.  Forgive me I havent notice that it will be adopted by sc,  honestly I havent used sc features since your earlier versions of snapprefs I was using your text customization only. 

So I can consider it as nice to have feature (very low priorty)  after its been adopted by sc. The difference here your feature is one shot very fast coloring for all letters,  but as you said i dont use it frequently. 

I dont want bother you with this feature so you can focus on more important isses/enhancements.  I leave this to you and to the community to decide.  

Thank you so much so far. Nice informative journey with your app.

**Comment by avi312singh** [comment]
+1 - I loved the feature <3...

**Comment by M1kep** [comment]
Agreed I used this feature often

**Comment by marzika** [comment]
Readded
https://github.com/marzika/Snapprefs/commit/c324d4fc00a88b4e6265ae9b5e7a8f2f97fbc40a
