### ISSUE TITLE
[Request] The ability to save profile "picture" snaps

### ISSUE THREAD

**Issue by c4isbad4u** [marzika/Snapprefs#210]
Is saving the profile pictures inside the snapcode possible to do?

**Comment by M1kep** [comment]
Do you mean like if you open a person's profile having a save button?

**Comment by NightMean** [comment]
I think holding on the picture would work too

**Comment by M1kep** [comment]
Working on this enhancement

**Comment by c4isbad4u** [comment]
Sounds good :)

**Comment by M1kep** [comment]
@c4isbad4u I've implemented it, just working on cleaning it up, if Marz accepts it it should be up by end of week, currently alot of bugs are being squashed/worked around so that may delay it, but it is coming!

**Comment by marzika** [comment]
Implemented in @M1kep 's pull request, thanks for both of you!
