### ISSUE TITLE
java.io.FileNotFoundException during save to SD card

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#214]
So I will attach the log... Whenever SR attempts to auto save to external SD it has a cannot save red error at the top... SR has correct storage permissions and root access... Anyone have any idea why i am getting a permission
[xposed_error_20160917_010424.txt](https://github.com/marzika/Snapprefs/files/477869/xposed_error_20160917_010424.txt)

 error which I never got before?

**Comment by marzika** [comment]
Use HandleExternalStorage or any other module that enables full sdcard access.
