### ISSUE TITLE
Separate marking chats as saved from writing them to a log file

### ISSUE THREAD

**Issue by jackmcbarn** [marzika/Snapprefs#225]
Currently, the same preference controls Snapprefs automatically marking all chats as saved  within Snapchat, and for writing them to a file in the ChatLogs folder. This should be split into two separate preferences.

**Comment by Andrerm124** [comment]
@jackmcbarn This is on my todo list. I'll be reworking the chatlog saving so that they're stored in a database and viewed in the Snapprefs app (Won't be anything too fancy though) which should make it easier to view them and, as you said, have the option to disable either individually :)

**Comment by jackmcbarn** [comment]
Hmm, I'm not sure I'm a big fan of the database idea. I do kind of like flat-file saving. (Perhaps have a way to export it like that?)

**Comment by Andrerm124** [comment]
The thing is, the database will allow for much better features as I can assign data to each individual chat message. For example (As suggested by another user) I can allow for the option to enable/disable auto logging of selected chats

**Comment by M1kep** [comment]
I believe this has been resolved/reworked. @Andrerm124 ?

**Comment by Andrerm124** [comment]
@M1kep Yeah, it has

**Comment by M1kep** [comment]
Awesome

@marzika
