### ISSUE TITLE
Filters looking very small

### ISSUE THREAD

**Issue by mathispesch** [marzika/Snapprefs#227]
Hello,

Using last debug version (from Jenkins 23/09/16), filters are very small (http://i.imgur.com/QyTDZBd.jpg).

My phone is a Galaxy S6.

**Comment by NightMean** [comment]
Mines are totally fine

**Comment by hbashton** [comment]
mine are small

**Comment by mathispesch** [comment]
Worked fine after I removed snapprefs data and re-installed it.
