### ISSUE TITLE
Force Navbar padding

### ISSUE THREAD

**Issue by yeezy69** [marzika/Snapprefs#236]
Hey, 

the option "Force Navbar padding" worked last in jenkins Build 40 on my OnePlus 3 with CM13. I use CM13 with disabled Hardware Buttons and Soft-Navbar. Screenshot shows Build 44.

![screenshot-build-44](https://cloud.githubusercontent.com/assets/22444686/18829742/edf9af1a-83dd-11e6-9976-f9ab77a1f70a.jpg)

Thank you :)

**Comment by marzika** [comment]
Verify your settings please, nothing has changed between these builds regarding them.

**Comment by yeezy69** [comment]
I'm running Build 44. Navbar padding did't work. I tried any settings. After "adb install -r snapprefs_build-40.apk" and reboot, Navbar padding works fine. After "adb install -r snapprefs_build-45.apk" and reboot, Navbar padding didn't work.

I completly delete snapprefs and did a reinstall and reconfigure. But no Navbar padding success.

In logcat i found:
09-29 13:25:31.491  3330  3578 I Xposed  : SnapPrefs: Loaded preference: pref_key_forcenavbar val: 1

**Comment by marzika** [comment]
Fixed here: https://github.com/marzika/Snapprefs/commit/43d4d40fcec0f158e98489e7f7f0a76fdec607c5
Sorry, @Andrerm124 messed up the preference name.

**Comment by yeezy69** [comment]
For information: in dev-build 32 force-navbar padding didn't work. Thank you! :)

**Comment by yeezy69** [comment]
Should I create a new ticket or can you open this again?
