### ISSUE TITLE
Save own Story

### ISSUE THREAD

**Issue by yeezy69** [marzika/Snapprefs#238]
Enhancement: With official beta-2.0 i was able to save my own story (over snapprefs). With jenkins build 40, 42 and 44 nothing happens, when i press the snapprefs save button (on my own story).

Of course i'm able to save my story with the normal snapchat button. But if it is possible, i would use the snapprefs save function. Because of the same saving directory as the received snaps.

Thank you :)

**Comment by marzika** [comment]
We will not add it to the button.
