### ISSUE TITLE
[Crash] XPosed Systemless v86.2 + Magisk 6 + SuHide 0.53

### ISSUE THREAD

**Issue by a-elkaim** [marzika/Snapprefs#240]
Hi,

Snapprefs is crashing whenever i take a picture, under the following setup:
- Snapprefs 2.0.0 (lastest release, not compiled from Github)
- XPosed Systemless v86.2
- Magisk 6
- SuperSU 2.78 Systemless
- SuHide 0.53

You can find the logcat trace attached ( i did a `grep snap` on the output )

[Snap crash.txt](https://github.com/marzika/Snapprefs/files/495469/Snap.crash.txt)

**Comment by Abbasoo** [comment]
Same here

**Comment by MrMikeTyson** [comment]
Same

**Comment by mathispesch** [comment]
It works fine for me with the latest Jenkins build.

**Comment by MrMikeTyson** [comment]
Have you our same setup ?  

XPosed Systemless v86.2
Magisk V6
SuperSU 2.78 Systemless
SuHide 0.53 ?

**Comment by marzika** [comment]
The only error I see is that Snapchat cannot find it's own files. It is related to your setup, as Magisk doesn't even support 86.2 of Systemless Xposed, nor 2.78 of SuperSU. Fix your setup, nothing needs to be done on my side.

**Comment by mathispesch** [comment]
I do, on a Samsung G920F.

**Comment by MrMikeTyson** [comment]
How can i fix my setup ?  Must i have xposed 86.5 ?

**Comment by m3rcuriel** [comment]
Hi, sorry to hop in on a closed issue but all you need to do is add snapchat to suhide's blacklist.

1. From adb shell: `ls -nld /data/data/com.snapchat.android`
2. Then note the number in the third column (10000 - 99999)
3. Also from adb shell: `/su/suhide/add $THENUMBER`
