### ISSUE TITLE
AndroidManifest.xml file not found

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#242]
I get an error: Error:Android Source Generator: [Snapprefs-stable] AndroidManifest.xml file not found whenever I try and generate a signed apk. I have sncyhed the manifest file but it still keeps giving me this annoying error in Android Studio. Any help pls?

**Comment by M1kep** [comment]
If compiling yourself just build a debug build

**Comment by M1kep** [comment]
Or pull any of the builds off the Jenkins

**Comment by avi312singh** [comment]
Ok nvm managed to build a signed APK, however I thought the Jenkins automatic build server was down?

**Comment by M1kep** [comment]
Currently being hosted by a differnt person than originally, but the link is on the main GitHub page in the readme: http://138.68.21.49:8080/

**Comment by avi312singh** [comment]
Oh yeah thanks!
