### ISSUE TITLE
nomedia file needed in LensIcons folder

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#245]
The saved lens png files are showing up in gallery even after media scan on my phone, maybe a nomedia file will fix this? Also congrats on the lens collection system, it works amazingly well @Andrerm124

**Comment by PotentialIngenuity** [comment]
You could put that file there your self

**Comment by avi312singh** [comment]
Clap clap congrats bro, remember this is a place for reporting issues and bugs with the app to the developers not to be cocky!! Also learn how to spell before you start telling others what to do

**Comment by Andrerm124** [comment]
@avi312singh Made the changes and pushed a PR (Only because it was a quick change). Thanks for the compliments, I appreciate it :) 

If you could do me a favour and close this issue, that'd be great!

**Comment by avi312singh** [comment]
@quorn23 Just wondering why you would heart such a foolish comment lol XD

**Comment by Andrerm124** [comment]
@avi312singh Please don't use the issue page for non issue questions. If you'd like to, you can visit the Snapprefs-dev.slack.com page and ask in the lounge channel. Thank you 😊
