### ISSUE TITLE
Snap taken by cam not sending

### ISSUE THREAD

**Issue by zevozki** [marzika/Snapprefs#250]
Hi.  Whenever i luanch sc and take pictures and adding some text and filter I will not be able to send it sometimes.  Its just random I couldnt catch the trigger of the issue. I can only say if i disable custom filters and and multi filter its sending snaps normally.  The issue within the custom filter and multi filter option. 
I took catlog as follow,  i hope i took it correctly. 

10-02 13:26:14.846 I/Timeline(23839): Timeline: Activity_launch_request id:com.snapchat.android time:164200804
10-02 13:26:14.847 I/ActivityManager(22788): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.snapchat.android/.LandingPageActivity bnds=[540,267][804,597](has extras)} from uid 10032 on display 0
10-02 13:26:15.204 I/Xposed  (32399): SnapPrefs: Updating view_snap.snap_container layout
10-02 13:26:15.269 I/Xposed  (32399): ----------------- SNAPSHARE STARTED -----------------
10-02 13:26:15.269 I/Xposed  (32399): SnapPrefs: Intent type: null, intent action:android.intent.action.MAIN
10-02 13:26:15.269 I/Xposed  (32399): SnapPrefs: Regular call of Snapchat.
10-02 13:26:15.284 I/Xposed  (32399): SnapPrefs: SNAPCONTEXT, NULL? - false
10-02 13:26:15.386 I/Xposed  (32399): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
10-02 13:26:15.524 I/Xposed  (32399): SnapPrefs: SNAPCONTEXT, NULL? - false
10-02 13:26:15.558 I/Xposed  (32399): SnapPrefs: FILE NOT FOUND - ARE YOU SURE YOU CREATED IT?
10-02 13:26:15.630 I/Finsky  (23885): [144] com.google.android.finsky.billing.iab.r.a(5175): com.snapchat.android: Account determined from installer data - [mn2tkVPopxKKlu5SPPSNZPVc_aA]
10-02 13:26:15.995 D/QCameraParameters(22517): int32_t qcamera::QCameraParameters::setNumOfSnapshot(): nBurstNum = 1, nExpnum = 1
10-02 13:26:16.000 D/QCameraParameters(22517): int32_t qcamera::QCameraParameters::setNumOfSnapshot(): nBurstNum = 1, nExpnum = 1
10-02 13:26:16.473 I/Xposed  (32399): SnapPrefs: Updating view_story_snap.snap_container layout
10-02 13:26:16.680 D/QCameraParameters(22517): int32_t qcamera::QCameraParameters::setNumOfSnapshot(): nBurstNum = 1, nExpnum = 1
10-02 13:26:16.691 D/QCameraParameters(22517): int32_t qcamera::QCameraParameters::setNumOfSnapshot(): nBurstNum = 1, nExpnum = 1
10-02 13:26:16.691 I/ActivityManager(22788): Displayed com.snapchat.android/.LandingPageActivity: +1s801ms
10-02 13:26:16.691 I/Timeline(22788): Timeline: Activity_windows_visible id: ActivityRecord{3b2c5633 u0 com.snapchat.android/.LandingPageActivity t8258} time:164202650
10-02 13:26:16.849 E/mm-camera(260): mct_stream_start_link: Starting snapshot stream linking 
10-02 13:26:16.849 E/mm-camera(260): mct_stream_start_link: Regular snapshot
10-02 13:26:17.614 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
10-02 13:26:17.614 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk

10-02 13:26:17.709 I/Xposed  (32399): SnapPrefs: Failed scan checks
10-02 13:26:17.721 I/Finsky  (23885): [144] com.google.android.finsky.billing.iab.r.a(5175): com.snapchat.android: Account determined from installer data - [mn2tkVPopxKKlu5SPPSNZPVc_aA]
10-02 13:26:17.723 I/Finsky  (23885): [145] com.google.android.finsky.billing.iab.r.a(5175): com.snapchat.android: Account determined from installer data - [mn2tkVPopxKKlu5SPPSNZPVc_aA]
10-02 13:26:18.095 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
10-02 13:26:18.095 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
10-02 13:26:19.282 I/Xposed  (32399): SnapPrefs: FileUtils: File not found: java.io.FileNotFoundException: /data/data/com.snapchat.android/files/weather.txt: open failed: ENOENT (No such file or directory)
10-02 13:26:19.282 I/Xposed  (32399): SnapPrefs: set the temperatures
10-02 13:26:19.283 I/Xposed  (32399): SnapPrefs: FileUtils: File not found: java.io.FileNotFoundException: /data/data/com.snapchat.android/files/weather.txt: open failed: ENOENT (No such file or directory)
10-02 13:26:19.283 I/Xposed  (32399): SnapPrefs: set the temperatures
10-02 13:26:20.346 I/Xposed  (32399): SnapPrefs: FileUtils: File not found: java.io.FileNotFoundException: /data/data/com.snapchat.android/files/weather.txt: open failed: ENOENT (No such file or directory)
10-02 13:26:20.346 I/Xposed  (32399): SnapPrefs: set the temperatures
10-02 13:26:20.347 I/Xposed  (32399): SnapPrefs: FileUtils: File not found: java.io.FileNotFoundException: /data/data/com.snapchat.android/files/weather.txt: open failed: ENOENT (No such file or directory)
10-02 13:26:20.347 I/Xposed  (32399): SnapPrefs: set the temperatures
10-02 13:26:20.545 D/QCameraParameters(22517): int32_t qcamera::QCameraParameters::setNumOfSnapshot(): nBurstNum = 1, nExpnum = 1
10-02 13:26:20.704 I/Xposed  (32399): SnapPrefs: Unlimited vanilla captions
10-02 13:26:20.796 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:20.832 E/BitmapFactory(32399): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Snapprefs/Filters/fullscreen_filter.png: open failed: ENOENT (No such file or directory)
10-02 13:26:20.832 I/Xposed  (32399): SnapPrefs: Replaced batteryfilter from /storage/emulated/0/Snapprefs/Filters Type: 0
10-02 13:26:20.833 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:20.973 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.036 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.137 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.201 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.271 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.335 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.418 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.502 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.569 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.667 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.717 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.777 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.835 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.895 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:21.975 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.026 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.077 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.146 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.207 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.264 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.345 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.402 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.432 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.456 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.514 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.584 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.667 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.741 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.824 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.888 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:22.925 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:23.016 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:23.109 I/Xposed  (32399): SnapPrefs: fullScreenFilter
10-02 13:26:23.235 I/Xposed  (32399): SnapPrefs: Called setColor: -65536
10-02 13:26:23.235 I/Xposed  (32399): SnapPrefs: Called setColor: -65536
10-02 13:26:23.392 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
10-02 13:26:23.393 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
10-02 13:26:23.733 W/View    (32399): requestLayout() improperly called by com.snapchat.android.ui.SelfScalingImageView{37881f50 V.ED.... ......ID 0,0-1080,1920 #7f0f03b7 app:id/geofilter_imageview} during layout: running second layout pass
10-02 13:26:23.802 W/View    (32399): requestLayout() improperly called by com.snapchat.android.ui.SelfScalingImageView{20e9c15a V.ED.... ......ID 0,0-1080,1920 #7f0f03b7 app:id/geofilter_imageview} during layout: running second layout pass
10-02 13:26:23.882 W/View    (32399): requestLayout() improperly called by com.snapchat.android.ui.SelfScalingImageView{1dd1b1de V.ED.... ......ID 0,0-1080,1920 #7f0f03b7 app:id/geofilter_imageview} during layout: running second layout pass
10-02 13:26:24.895 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
10-02 13:26:24.896 I/Xposed  (32399): SnapPrefs: Found an unexpected entry at stories TYPE: Qk
10-02 13:26:31.779 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:31.779 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:31.779 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:31.779 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:32.723 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:32.723 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:32.723 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:32.723 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:33.631 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:33.631 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:33.631 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:33.631 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:34.493 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:34.493 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:34.493 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:34.493 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:35.063 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:35.063 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:35.063 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:35.063 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:35.571 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:35.571 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:35.571 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:35.571 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:37.191 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:37.191 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:37.191 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:37.191 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:37.815 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:37.815 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:37.815 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:37.815 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:38.752 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:38.752 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:38.752 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:38.752 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:39.232 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:39.232 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:39.232 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:39.232 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:40.138 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:40.138 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:40.138 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:40.138 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:40.919 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:40.919 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:40.919 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:40.919 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:41.839 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:41.839 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:41.839 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:41.839 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)
10-02 13:26:42.317 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.applyFilter(VisualFilters.java:339)
10-02 13:26:42.317 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters.access$100(VisualFilters.java:54)
10-02 13:26:42.317 E/Xposed  (32399):   at com.marz.snapprefs.VisualFilters$6.beforeHookedMethod(VisualFilters.java:233)
10-02 13:26:42.317 E/Xposed  (32399):   at com.snapchat.android.ui.SwipeImageView$1.doInBackground(SourceFile:1214)

**Comment by M1kep** [comment]
@zevozki attempt to clear your SnapPrefs cache

**Comment by zevozki** [comment]
@M1kep just did and I still having same problem. 
Just want to make it clear,  the problem is after taking picture and writing text and swipe and select filter then you press the arrow so you can select the receiver,  I cant pass to select receiver its just stayed there. Keep pressing the arrow for ever until sc crash.

**Comment by M1kep** [comment]
Ok, what version of SP and SC?

**Comment by zevozki** [comment]
@M1kep 
Sc v9.31.1.0
Sp v2.0.0 beta

**Comment by marzika** [comment]
Make a proper filtered logcat, as it only contains the parts of the error stack.

**Comment by zevozki** [comment]
@marzika sorry for that, this is my first time doing logcat.  I want to learn to do the proper filter but I dont know how.

**Comment by M1kep** [comment]
We have recently pushed the development branch over to the stable branch in this we have resolved many issue, and added new functionalities. For the time being this build can be downloaded from: http://138.68.21.49:8080/job/SNAPPREFS%20-%20Official%20-%20stable/lastSuccessfulBuild/

**Please Note** This Version Is Built For SnapChat 9.39.5 **End Note**
If you cannot install this version as an update we recomend that you re-install this version. 

If this new build solves your issue please comment, and close the issue. Otherwise leave a comment stating this issue is still present.

**Comment by alexhulbert** [comment]
The issue is happening for me even more on this build, I'll upload my own logcat later today,

**Comment by zevozki** [comment]
Resolved in this development branch. However other things raised like
1. Saving snap button not visible. I just click the corner and its showing small green dot and the snap is saved. Saving both story or direct. 
2. Looping not working in story. 
3. Skipping stories fast will force close sc. 

Im sorry im not able to provide logcat im in travel.  So far this is what i can say about latest branch

**Comment by M1kep** [comment]
@zevozki 
1. That is the stealth saving functionality, not sure if you have that enabled or not.
Also please create a new issue for further problems.

**Comment by zevozki** [comment]
@M1kep  thanks for swift replay. 
Generally speaking  Im noticing new things added but i cant see how this new functions can be used,  like a guide I mean.  

Others created the issues already so i dont need to duplicate. I will keep checking for more issues.
