### ISSUE TITLE
Logcat : Snapchat crash after taking picture

### ISSUE THREAD

**Issue by MrMikeTyson** [marzika/Snapprefs#251]
Hello, Snapchat crash after taking picture, here is a logcat.

[alogcat.2016-10-02-16-42-25+0200.txt](https://github.com/marzika/Snapprefs/files/505175/alogcat.2016-10-02-16-42-25.0200.txt)

**Comment by marzika** [comment]
Filter the log properly, otherwise the issue report is invalid. DONT filter for any line containing "snapchat'. Filter in Android Studio for the Snapchat application.

**Comment by MrMikeTyson** [comment]
But I don't have Android Studio. My computer does not have enough space for me to install Android Studio ... What can I do?

**Comment by marzika** [comment]
Then find an application that can filter to packages instead of content of lines.

**Comment by MrMikeTyson** [comment]
Sorry but I'm not too expert ... I do not know how to do that

**Comment by AmineI** [comment]
Nobody here is "too expert" to the point of knowing every app in the world, to suggest which one fits your needs. When I search an app for something, I do like everyone : I google it. Why not starting by that :) ?

**Comment by AmineI** [comment]
A minute after, I found one in the five first google play store results. Yaaay !

Sorry to seem rude but everyone should know how to make a google search before complaining :/ .

**Comment by Efficacy28** [comment]
Here is my logcat (filter for com.snapchat.android) and log from Xposed.

[logcat.txt](https://github.com/marzika/Snapprefs/files/505505/logcat.txt) - 60ish lines
[xposedLog.txt](https://github.com/marzika/Snapprefs/files/505506/xposedLog.txt) - 130ish lines

Device Information:
Samsung Galaxy S4 (SPH-L720)
Android version 4.4.2 KitKat
L720VPUFNG2

**Comment by davex2012** [comment]
@Efficacy28 how did you produce a logcat for snapchat?

**Comment by AmineI** [comment]
Okay, if nobody found it... Either Android Studio's per app filter, or Logcat extreme, the 3rd result from google play store when you search "Logcat".

**Comment by Efficacy28** [comment]
The "crash" occurs a few seconds after taking a picture. I use quotations because it's not a crash per se, but Snapchat just freezes or slows down significantly. The "crash" has been occuring since the official stable Snapprefs 2.0.0 beta update, but I suppose not a lot of users experiences this issue since it wasn't properly reported up until now.

Here is short clip (~42 sec) of the crash
https://youtu.be/FgO_QZZISSw

EDIT: Fixed YouTube link. Corresponding logs in my last comment above.

**Comment by M1kep** [comment]
@efficacy28 download cat log, open it, click the circles x on the top right to clear the log, open snapchat,  cause the freeze, then open catlog, search for snap, click the three vertical dots button on the bottom right, click save, upload here

**Comment by Efficacy28** [comment]
@M1kep 
[catLog.txt](https://github.com/marzika/Snapprefs/files/517501/catLog.txt)

**Comment by Efficacy28** [comment]
I read the information from the pull requests. I disabled all the visual filters and I was able to take a picture without the freeze. Thanks for the help.

**Comment by M1kep** [comment]
Awesome, glad you were able to figure that out, was odd trying to find an issue where  there is no crash, especially when  we are coding into another app :p
