### ISSUE TITLE
The "GRADIENT" caption in the painting tools menu does not fit in its layout

### ISSUE THREAD

**Issue by gilbsgilbs** [marzika/Snapprefs#253]
Hi,
The "GRADIENT" caption in the painting tools menu is split into two lines on my phone because the layout is too small to display it properly. Thus, the trailing "T" is displayed on a second line (which is barely visible). We would probably expect all the "GRADIENT" string to display on one line.

My phone is a LG Nexus 5 running the last Paranoid Android. Let us know if this does reproduce on other ROM/screen resolutions/phones.

![gradient](https://cloud.githubusercontent.com/assets/3407667/19023894/69e94d04-88f9-11e6-894a-9d330f660115.png)

Thanks!

**Comment by M1kep** [comment]
@gilbsgilbs can I get a full screenshot of the issue?

**Comment by gilbsgilbs** [comment]
@M1kep here it is.
![screenshot](https://cloud.githubusercontent.com/assets/3407667/19023857/8ca67c64-88f8-11e6-8391-d1ad27045d63.png)

**Comment by marzika** [comment]
Fixed in https://github.com/marzika/Snapprefs/commit/83b8222657ee02c9159ff3a2b9ad4c076951090d
