### ISSUE TITLE
[Request] Externalise hooks into downloadable resource

### ISSUE THREAD

**Issue by psylenced** [marzika/Snapprefs#257]
Similar to how XInsta works, externalise all the magic strings the obfuscator class into a downloadable and dynamically loadable resource.

Eg:
https://github.com/iHelp101/XInsta/blob/master/Hooks.txt ( From: https://github.com/iHelp101/XInsta )

This means a rebuild of the app is not required per snapchat version change, and it's only required when there are new features or breaking changes (ie. signature changes).

The way I believe XInsta works is by detecting the currently installed version, downloading the latest hooks.txt file and then loading the appropriate hooks based on version matching key for the instagram app.

Any time the hooks change in a new version, an update is committed into github, users update their hooks.txt file and continue without needing to wait for a full xposed app update.

**Comment by roryclaasen** [comment]
see #36

**Comment by psylenced** [comment]
My apologies :)
