### ISSUE TITLE
Idea with snapchat sign in

### ISSUE THREAD

**Issue by SlayaMods** [marzika/Snapprefs#259]
I have no idea if it is possible but can there be someway for snapchat to not detect xposed when signing  into snapchat

**Comment by M1kep** [comment]
Pretty sure that is related to SafetyNet, but input from @marzika would be more informational

**Comment by marzika** [comment]
It is because of SafetyNet, bypassing it goes way beyond Snapprefs' capabilities.

**Comment by a-elkaim** [comment]
We can't do anything, if you want to, you can look into SuHide, it is the only way to hide Xposed from being detected by SafetyNet for now, but it seems it is not Snapprefs compatible.

**Comment by SlayaMods** [comment]
Okay thanks for input
