### ISSUE TITLE
SnapPrefs crashes when loading "My Filters" tab if data connection is unavailable

### ISSUE THREAD

**Issue by svg-frog** [marzika/Snapprefs#265]
[snapprefs.txt](https://github.com/marzika/Snapprefs/files/520331/snapprefs.txt)

If you have no network data (and no WiFi), or Airplane Mode is enabled, SnapPrefs crashes when loading "My Filters" page.

Error log of Snapprefs crash is attached.

**Comment by Efficacy28** [comment]
I can confirm this as well. The simple solution would obviously be to establish an internet connection prior to loading the My Filters, Reddit Filters, or G+ Filters tabs.

**Comment by marzika** [comment]
Fixed by @Andrerm124
