### ISSUE TITLE
Text options menu locks up sometimes

### ISSUE THREAD

**Issue by franc-ist** [marzika/Snapprefs#278]
Sometimes the text menu will lock up, where options can be clicked, but none of the dialog boxes will work. As well as this, the user will be unable to exit the selected dialog without the use of hardware buttons or crashing Snapchat.

AOSPA 6.0.2, OnePlus X, 9.39.5 beta build from source.

**Comment by marzika** [comment]
I am not sure if this can be reproduced, if you happen to grab a Logcat of the crash, please post it here.
