### ISSUE TITLE
Snaps failing to load if autoadvance turned off

### ISSUE THREAD

**Issue by franc-ist** [marzika/Snapprefs#279]
Running the 9.39.5 source build. Snaps will load as completely black, but will still play sound (videos).

**Comment by M1kep** [comment]
Does it give any sort of logs?

**Comment by franc-ist** [comment]
[Here are the logs onwards from one case of this,](http://pastebin.com/9HbmeV7t), which was Melissa's video snap. If you would like full logs, I can arrange that.

**Comment by marzika** [comment]
I am kinda sure it is an issue of Snapchat with the rendering, as we are not touching that part.
