### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Efficacy28** [marzika/Snapprefs#286]
SC crashes after a few seconds from startup after installing the SP dev build 26.

[Log_2016-10-25_07-59-23.txt](https://github.com/marzika/Snapprefs/files/549303/Log_2016-10-25_07-59-23.txt)

**Comment by M1kep** [comment]
Looks like it is crashing when  attempting to upgrade the db hmmmm

**Comment by M1kep** [comment]
Does it happen every time You open the app? If so can you upload. Your lense.db file?

**Comment by M1kep** [comment]
Also, if it does happen every time can you clear the log, reproduce the issue, and upload the unfiltered log? It appears your filter is removing they key exception

**Comment by Efficacy28** [comment]
@M1kep I reverted back to build 25 because it doesn't crash I think the jenkins website is down so I can't get build 26. Can you restart it?

**Comment by M1kep** [comment]
Jenkins isn't down, http://138.68.21.49:8080/

But I really would appreciate if you could still get me a log at some point.

**Comment by M1kep** [comment]
Actually go with build 29 http://138.68.21.49:8080/job/SNAPPREFSDev/29/

**Comment by lucaboox** [comment]
I had the same issue but I rebuilt the app with a new version and it was fixed I forgot what build it was though

**Comment by Efficacy28** [comment]
@M1kep SPdev29 crashes when selecting the Lens Collector / Loader tab. [SPcrash.txt](https://github.com/marzika/Snapprefs/files/551928/SPcrash.txt)

Here's the .db file you requested: [Lenses.db](https://drive.google.com/file/d/0ByoyUnstsl4EWjdsRnNEZkZEZ3YxSjZtZGtEczNZQ1Fkbnlj/view?usp=sharing)

SC9.39.5.0 still crashes with SPdev29. Here's the filtered log and the corresponding unfiltered log respectively:
[SCcrash.txt](https://github.com/marzika/Snapprefs/files/551937/SCcrash.txt)
[SCcrash_unfiltered.txt](https://github.com/marzika/Snapprefs/files/551939/SCcrash_unfiltered.txt) (Warning: 10 000+ lines)

**Comment by Andrerm124** [comment]
I believe I may have resolved it in my latest PR
