### ISSUE TITLE
August 18 Build

### ISSUE THREAD

**Issue by DankMemeGuy** [marzika/Snapprefs#287]
Not sure how to do this, and i can't find the build on jenkins, but can someone render the August 18 build so it's an 'installable' file?

**Comment by dkisselev** [comment]
I don't think that build is good (ie, works well).

The current development branch is built and available here: http://138.68.21.49:8080/job/SNAPPREFSDev/ (download the app-debug.apk file). Development is updated nearly daily these days and works reasonably well.

**Comment by quorn23** [comment]
http://bfy.tw/8Mca

**Comment by DankMemeGuy** [comment]
@dkisselev I'm looking for the last build that had the auto-save feature, which seems like it was that specific build, unless I'm wrong?
