### ISSUE TITLE
Custom Stickers

### ISSUE THREAD

**Issue by sami0596** [marzika/Snapprefs#290]
Hi.
I have the latest snapprefs build for Snapchat 9.39.5.0
( http://138.68.21.49:8080/job/SNAPPREFSDev/29/ )
When I click on my custom sticker, it will disappear and then the previous will shows up.
Help!

**Comment by marzika** [comment]
You need to check the zip names, then clear Snapchat's Sticker directory in the /data partition.

**Comment by sami0596** [comment]
I have checked the zip names:
twemoji_2_png.zip and twemoji_2_svg.zip

What do you mean with "clear Snapchat's Sticker directory in the /data partition."

Which directory in /data? 
Can't  find anything
