### ISSUE TITLE
Can't upload pictures using Upload button

### ISSUE THREAD

**Issue by massi08** [marzika/Snapprefs#292]
Hi,
I'm having some trouble with the upload button not showing my pictures, instead it only shows my videos.  I don't know if it's intended or it's a bug.I had this problem on Snapchat 9.31.1.0 using Snapprefs 2.0.0 Beta. Now I'm on Snapchat 9.39.5.0 using the latest Jenkins build of SnapprefsDev and still have the same issue.
I'm using a OnePlus One CM 13.1.2 Android 6.0.1.

**Comment by franc-ist** [comment]
Are you talking about the one near the camera switcher? I'm pretty sure this is only for videos, as this is all I get as well when I click it.

**Comment by massi08** [comment]
@FishyFing Yep I'm talking about this one.

**Comment by marzika** [comment]
Fixed in https://github.com/marzika/Snapprefs/commit/70d6234b4d5b5b02435e956d0c684e85798ee859
