### ISSUE TITLE
Snapprefs Crashes Upon Selecting Lens Collector / Loader Tab

### ISSUE THREAD

**Issue by Efficacy28** [marzika/Snapprefs#293]
![img_20161027_070852](https://cloud.githubusercontent.com/assets/22584055/19752768/a2c2b1f6-9bb4-11e6-8219-b1a7faa7d866.jpg)

Also, my collected lenses don't load (probably because I can't access the Lens Collector / Loader tab due to the crash). I'm using SPdev32. This issue has been present for me since build 26—there were no crash issues for me for build 25.

[SPdevLog.txt](https://github.com/marzika/Snapprefs/files/554595/SPdevLog.txt)

**Comment by Andrerm124** [comment]
Would you mind uploading your Lenses.db file for me so that I can replicate and fix this issue? 

Also, I really appreciate the detail you've used, you wouldn't believe how much easier that makes things 😀

**Comment by Efficacy28** [comment]
@Andrerm124 GitHub won't let me upload .db files so I just renamed it to .txt [Lenses.txt](https://github.com/marzika/Snapprefs/files/555945/Lenses.txt)

Haha I know what it's like. I'm a programmer myself, but nowhere near your guys' level 😛

**Comment by Andrerm124** [comment]
@Efficacy28 Resolved this issue, thanks for the help :)

**Comment by Efficacy28** [comment]
@Andrerm124 It works marvelously. Yep!
