### ISSUE TITLE
Can't send snap to more than one person

### ISSUE THREAD

**Issue by banterbus321** [marzika/Snapprefs#295]
I am using snapchat version 9.31.0 and snapprefs 2.0.0. The issue I am having is with the app every time I try to send a snap to more than one person the names of the people just disappear in the chats window and don't get sent. Any help would be massively appreciated .

I have tried installing build 29 and 32 and rebooting but it just causes my sc to crash on launch

**Comment by Efficacy28** [comment]
@banterbus321 Builds 29 and 32 require Snapchat v9.39.5 to run properly. Just google for the apk of that version and try again with build 32.

**Comment by banterbus321** [comment]
@Efficacy28 Thank you, I re-installed the app and so far it seems to be working!!
