### ISSUE TITLE
Crash When Trying to Save Chat Media

### ISSUE THREAD

**Issue by Efficacy28** [marzika/Snapprefs#296]
I'm using SPAndrUpdate9.39.5 build 40. When I open the image from chat and then long press, that's when it crashes. The _filtered_ [Crash Log](https://github.com/marzika/Snapprefs/files/559014/ChatMediaSaveLog.txt) is 14k+ lines, but you can find the error at the end of the log as follows:

> ...
> 10-28 14:53:15.093 23824 23824 I Xposed  : ----------------------- SNAPPREFS -----------------------
> 10-28 14:53:15.123 23824 23824 I Xposed  : Snapprefs: We have the chat image
> 10-28 14:53:15.123 23824 23824 I Xposed  : Snapprefs: We have the chatMedia
> 10-28 14:53:15.123 23824 23824 E AndroidRuntime: Process: com.snapchat.android, PID: 23824
> **10-28 14:53:15.123 23824 23824 E AndroidRuntime:    at com.marz.snapprefs.Chat$9$1._onLongClick_(Chat.java:412)**
> 
> 10-28 14:53:15.133   896  1576 W ActivityManager:   Force finishing activity com.snapchat.android/.LandingPageActivity
> 
> 10-28 14:53:15.143   896  1258 V SmartFaceService - 3rd party pause: onReceive [android.intent.action.ACTIVITY_STATE/com.snapchat.android/pause]
> 
> 10-28 14:53:16.444   896  1507 I LocationManagerService: remove 44376bd0 by com.snapchat.android
> 
> 10-28 14:53:16.444   896  1503 I LocationManagerService: remove 439c4840 by com.snapchat.android
> 
> 10-28 14:53:16.444   896  1462 I ActivityManager: Process com.snapchat.android (pid 23824) (adj 9) has died.
> 
> 10-28 14:53:16.444   896  1506 I WindowState: WIN DEATH: Window{442c50a8 u0 com.snapchat.android/com.snapchat.android.LandingPageActivity}
> 
> 10-28 14:53:16.444   896  1462 W ActivityManager: Service crashed 2 times, stopping: ServiceRecord{456c01d8 u0 com.snapchat.android/.service.ScStickyService}
> 
> 10-28 14:53:16.454   284   284 E QCameraHWI: cancelPictureInternal : destroy_stream_bundle of snapshot & thumbnail
> //End of log

**Comment by lucaboox** [comment]
I was about to report this lol same issue here

**Comment by Andrerm124** [comment]
@Efficacy28 The media saving has been broken for a while now unfortunately. Though the chat logging system has been completely replaced and I couldn't get the old db's to transfer across so I'm sorry about that. 

Also, that db probably contains some private information (Such as friends usernames/messages) so you may wish to edit it out 😊

**Comment by Efficacy28** [comment]
@Andrerm124 I'm using AndrUpdate9.39.5 build 64 and chat saving seems to be working again. 

But when someone sends multiple images into one message, SP thinks that each image is the same. So, after saving the first image successfully, aftempting to save another image from the same message results in "Chat image exists." One solution could be to simply rename the saved media, but after closing and restarting SC, I'm able to save another image. So, if someone sent me 5 images into a single message, I need to restart SC 4 times to save each image. Could this be fixed? I really appreciate your work and attention to our reports. Thanks!

**Comment by Andrerm124** [comment]
@Efficacy28 Hmmm, this is probably just a bad oversight from me. I've honestly only tested with one image at a time so I'll have to look into it. Do you happen to know if it does it with videos too?

**Comment by Andrerm124** [comment]
@Efficacy28 Ahhhh I understand why now! It's just a case of finding something to add to the filename to separate them

**Comment by Andrerm124** [comment]
@Efficacy28 Resolved in [#de19698](https://github.com/Andrerm124/Snapprefs/commit/de196980d0f1bd1b6290540105cefdb5e96128fa)

**Comment by Efficacy28** [comment]
@Andrerm124 It works! Wonderful, thanks again :)

**Comment by lucaboox** [comment]
Where did you get build 64
