### ISSUE TITLE
Accept EULA Bug

### ISSUE THREAD

**Issue by NicolaiSchmid** [marzika/Snapprefs#300]
When I open snapchat Snapprefs promts me to accept their EULA which I already did. Opening the Snapprefs app doesn't help, since it doesn't asks me to accept them again. 
Resetting Snapprefs didn't work

**Comment by davex2012** [comment]
Go to xda and search your issue. You'll find the answer.

**Comment by joern-h** [comment]
@f7f7u7f7 Accept it and change a setting. Thats all
The issue is only there if you dont change a setting.

**Comment by M1kep** [comment]
@f7f7u7f7 Generally you should install/update SP, accept EULA, activate, restart, open SP, ensure SC isn't in history, if so kill it from there, open SC
