### ISSUE TITLE
Snapprefs Force Close when tapping on "Lens collector/ loader"

### ISSUE THREAD

**Issue by mranzy** [marzika/Snapprefs#301]
I'm using 52 on  SNAPPREFSAndrUpdate9.39.5
 Here are the logs: 

[SR.txt](https://github.com/marzika/Snapprefs/files/563033/SR.txt)

**Comment by M1kep** [comment]
@mranzy Do you have a Lense.db in your save location?

**Comment by M1kep** [comment]
Also, can you replicate on http://138.68.21.49:8080/job/SNAPPREFSAndrUpdate9.39.5/52/

**Comment by mranzy** [comment]
Yes I found it in Snapprefs file, here it is

PS : had to rename it to txt or it wont upload

**Comment by Andrerm124** [comment]
For some reason you renamed a ChatMessages.db to Lenses.db and the contents are completely different causing you to crash

**Comment by a-elkaim** [comment]
I have the same issue, but I never renamed ChatMessages.db to Lenses.db

But still, my Lenses.db content looks like the ChatMessages.db one

**Comment by Andrerm124** [comment]
@azsde Seems I owe @mranzy an apology, there was a piece of code left over from the old system causing the names to overwrite. This has been resolved in my latest build. Again, sorry about that :/

**Comment by a-elkaim** [comment]
@Andrerm124  I see, I deleted my Lenses.db, how can I generate a new one ?

**Comment by Andrerm124** [comment]
@azsde It'll do it automatically when it's needed

**Comment by a-elkaim** [comment]
I'm going to try your build and let you know if this works.

**Comment by a-elkaim** [comment]
It seems to be working (at least, not crashing anymore).

Maybe you could change the toggle buttons color to something green when enabled and gray when disabled ? Instead of lighter and darker grey ?

**Comment by Andrerm124** [comment]
@azsde That's just stock android, it's handled differently by the system and people on different roms (Such as myself) see them differently

**Comment by azsde** [comment]
@Andrerm124 My bad then ! :) Awesome work with the lense collector by  the way.

**Comment by a-elkaim** [comment]
@Andrerm124 My bad then ! :) I can't seem to collect any lenses, is there a specific way of collecting them ?

**Comment by Andrerm124** [comment]
@azsde You need to load snapchat up for at least 30 seconds for them to go through

**Comment by BornInSuriname** [comment]
Snapprefs is fc when I want to open the lenses. What can I do?

**Comment by Andrerm124** [comment]
@BornInSuriname You can read 9 posts up

**Comment by BornInSuriname** [comment]
Thnx @Andrerm124 but I deleten de lenses.db but without result.
I also deinstalled snapprefs deleten evers folder buiten still fc
