### ISSUE TITLE
[Request] Replace failed story (mainly)/ sent snaps 

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#306]
If I snap has pernebantly failed to send (size/time issue etc) and you realise a few hours later, would there be a way to replace the failed snap with a video/image. This way your story retains its original form it was sent it... I dunno if permanently failed snaps are kept in the cache, if not then this would probably be impossible but if not then maybe it may not be to just replace the failed snap in the cache and try sending again

**Comment by marzika** [comment]
They are not stored in the cache, therefore cannot be retrieved.
