### ISSUE TITLE
[Request] Compression 

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#307]
To make the unlimited recording feature 100% successful a compressor could be implemented to make the video under 4.7mb or whatever the current size limit is... Or you could choose a compression % setting once the snap has gone over 10 seconds. 
Not sure how hard it would be to implement something like ffmpeg, but it's very efficient 

http://android.stackexchange.com/questions/127650/fast-video-compression-on-android

https://www.quora.com/What-are-the-steps-for-integrating-FFMPEG-on-Android

**Comment by M1kep** [comment]
Unlimited recording was implemented about a week or two ago.

**Comment by M1kep** [comment]
@marz can close this.

**Comment by avi312singh** [comment]
Who said it wasn't??

**Comment by M1kep** [comment]
Threre is no realistic max file size anymore.... 
Are you looking to send viedeos over 30 seconds>?

**Comment by avi312singh** [comment]
No between 10 and 15, they fail nearly 100% of the time... Until I compress ut using an app to about under 4.7Mb then it will send

**Comment by M1kep** [comment]
Hrm, what build are you using? I believed we resolved that issue with a change to the method we hook

**Comment by avi312singh** [comment]
Snapchat 9.29.50.0 Sr ur latest build ;) #114 Which seems to have fixed it... Your feature of specifying time for unlim. recording really works well!! I have set it to 15 seconds and it works 100% perfectly... Gonna experiment with higher times :)

**Comment by M1kep** [comment]
Awesome! Sounds great! Glad its working for you :D

**Comment by avi312singh** [comment]
Cheers boss, delay in reply was due to rebooting phone but yh well done, amazed ur commit seems to have fixed it finally loool. Good to see no more of them fkin annoying snap failed to send ;)
