### ISSUE TITLE
Force Navbar padding

### ISSUE THREAD

**Issue by yeezy69** [marzika/Snapprefs#309]
Hey,

the option "Force Navbar padding" worked last in jenkins "Official stable" Build 48 (with 9.31.1) on my OnePlus 3 with CM13. I use CM13 with disabled Hardware Buttons and Soft-Navbar. On jenkins "Official development" Build 34 it didn't work (with 9.39.5).

Same issue like #236 

Configuration file /data/data/com.marz.snapprefs/shared_prefs/com.marz.snapprefs_preferences.xml says:
<int name="pref_key_forcenavbar" value="1" />

Thanks :)

**Comment by marzika** [comment]
Thanks for reporting it, should be fixed in the above mentioned commit. If it still doesn't work, let me know.
