### ISSUE TITLE
Can't open snapchat 9.31.1.0 anymore

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#316]
Hey,
i've a problem : i cant open snapchat for 5 days. I'm pretty sure it's linked with the account AND the snapchat version, because i can connect to another account with SC 9.31.1.0 (and Snappref is perfectly functionning) BUT i cant connect to my own account. HOWEVER I can connect to my account by upgrading Snapchat to the latest, uninstalling xposed and then reinstalling xposed after im connected (of course, snapprefs is then not working)
Thank you for all your job,
Elerir
EDIT: I already tried modifying the Snapprefs 9.31.1.0 to change the version name but it's not working
However, without internet access i can go on snapchat 9.31.1.0

**Comment by iiTranquility** [comment]
Quote from MaaarZ's post.

"The thread is getting closed again, as it is getting out of the hand yet again.

Yes, 9.31.1.0 has been made incompatible by Snapchat serverside, don't post about it.
Development builds support 9.39.5.0, but they are experimental and are NOT stable.

If you found an issue with the DEVELOPMENT BUILDS, send them to our Slack Channel's #issue-reporting or to the Github Issues page WITH PROPER XPOSED AND/OR LOGCATS (without these your issue will NOT be resolved).

Github: https://github.com/marzika/Snapprefs
Development builds: http://138.68.21.49:8080/
Slack channel: https://snapprefs-dev.slack.com
Get an invite to Slack: https://snapprefs-dev.herokuapp.com"

**Comment by Elerir** [comment]
Ok thanks, and what do i need to do to test this Snappref development version ? Im a beginner in java but i can find some bugs maybe
