### ISSUE TITLE
Sweep to save problem

### ISSUE THREAD

**Issue by MrMikeTyson** [marzika/Snapprefs#320]
Hello everyone,

I use the "sweep to save" function but when I open snapchat and I sweep to save a photo or a video, it doesn't work. I'm using SnapPrefs 2.0.0 beta, the latest and Snapchat 9.39.5. Here's a log of Xposed attached.

[xposed_error_20161110_154831.txt](https://github.com/marzika/Snapprefs/files/583638/xposed_error_20161110_154831.txt)

**Comment by marzika** [comment]
You are not sweeping in a long enough distance.
