### ISSUE TITLE
Memory issue with many custom filters

### ISSUE THREAD

**Issue by ConnectDevelopers** [marzika/Snapprefs#325]
## Expected Behavior
The pre-edit screen should not freeze for 10 seconds with 15 custom filters.

## Current Behavior
When for example: 15 custom filters are being loaded on the pre-edit screen, it takes about 10 seconds to load the edit screen and it takes less than 0.5 without custom filters. Threading issue??

## Possible Solution
Use different thread to load the filters?

## Steps to Reproduce (for bugs)
Download or make multiple filters, use them and take a picture and you should see the pre-edit freeze.

## Context
It's not very userfriendly to use the custom filters since it takes too long to load.

## Your Environment
* Version used: 2.0.0  Beta (59 Nov 13, 2016 4:41:11 AM)
* Android version: 6.0.1 with OxygenOS 3.2.7
* Xposed version and type: v86-arm64, Systemless
* Root version and type: SuperSU, systemless
* Do you use any root/xposed hiding? If yes, which?: No

**Comment by marzika** [comment]
Please check if this commits fixes it for you: https://github.com/marzika/Snapprefs/commit/35e00a0f123e22105e0b4fe03a5242af2fa2a045
