### ISSUE TITLE
Fling to Save

### ISSUE THREAD

**Issue by robert-henley** [marzika/Snapprefs#326]
Fling to save doesn't work on received Snaps, but does work on Stories. It does save the picture/video, but won't let me tap past it to finish opening it.
I had a build from Nov. 2nd (don't remember which one), didn't work then. I just updated to today's Stable Build #70, same problem.
I can back out of it, but it won't open and show that I opened it.

* Version used:  Snapprefs Official Stable Build #70 
Snapchat Version: 9.39.5
* Android version:  4.4.4
Cyanogen OS: 11.0
* Xposed version: 2.6.1  
* Root version: KingRoot

**Comment by marzika** [comment]
This should fix your issue: https://github.com/marzika/Snapprefs/commit/86b0443e41f08ded6962b113c61117de3ee21424
