### ISSUE TITLE
Cannot scale images shared from gallery. 

### ISSUE THREAD

**Issue by zevozki** [marzika/Snapprefs#340]
## Expected Behavior
If i do select the scale for the pic in snapprefs and sharing pic from gallery it should scale all images from my gallery straight into snapchat. 

## Current Behavior
After the recent branch development with sharing with scale selected in snapprefs.  Any image sharing is now opening new interface called Edit,  it only allow crop and rotate and there is no scale! Maybe this is new functionality editing before sharing however what is the use now for crop in snapprefs app and when sharing from gallery. Its duplicate functions or Im confusing things? 
I just want to report the scale for sharing images  is not working

## Possible Solution
I cant suggest 

## Steps to Reproduce (for bugs)
Just share any image from gallery and see if you can scale it

## Context
Shared images are chopped  which affect all pic shared

## Your Environment

* Version used:  latest branch development as of today
* Android version:  5.0.2
Cyanogen OS 12.0
Oneplus one

**Comment by M1kep** [comment]
@zevozki Is the new implementation a valid resolution for the old "scale and crop to fit" options, because both can be emulated in the new interface?

**Comment by zevozki** [comment]
@M1kep i have taken screenshot of it.  Here I cant reduce the scale more than this.  That why it will be cropped 
http://m.imgur.com/PvmxHBG

**Comment by M1kep** [comment]
Ah, so previously it would have squished it to fit? WIth black bars up top more than likely?

**Comment by zevozki** [comment]
@M1kep Yes. Previous to this update it was sharing any image and it will fit it automatically to the screen resolution.  If the image is wide it will scale it and as you said the black bars above and beyond will be there. 

Note: "Previous"  I mean in older version when the sharing images was direct from gallery to snapchat.  Now sharing becomes gallery > Edit > snapchat

**Comment by marzika** [comment]
Can you please check if this works? https://github.com/marzika/Snapprefs/commit/10c81259601893e17c2bd0865b297fe6971b3970

**Comment by zevozki** [comment]
@marzika  i tried to access this link in order to test the build but its ask for login and password 

http://138.68.21.49:8080/job/SNAPPREFS%20-%20Official%20-%20stable/lastSuccessfulBuild/

**Comment by M1kep** [comment]
@zevozki Use new links in the readme

www.snapprefs-builds.com

**Comment by zevozki** [comment]
@marzika I have downloaded the build 186 and installed.  I tried to share and saw the image still cannot be reduced the scale to fit the screen
http://imgur.com/CIuLOoH
However I can play with finger and reduce the size but until i move out my fingers the pic is filling the full screen again. 
This is how it suppose to be after correct scale 
http://imgur.com/XKbH3uy

**Comment by marzika** [comment]
The only issue I see here are:
a) there is no build 186
b) the latest stable build is 92

**Comment by zevozki** [comment]
@marzika Sorry i mean development build 168

http://www.snapprefs-builds.com/view/Development/job/SNAPPREFS%20-%20M1kep%20-%20development/lastSuccessfulBuild/artifact/app/build/outputs/apk/snapPrefs-v25b168-debug.apk

**Comment by marzika** [comment]
How would M1kep's build have the changes, when the commit I linked is from the official stable branch?

**Comment by zevozki** [comment]
@marzika I apologize, first time i use gihub with your app only so I am learning new things. 

Back to topic,  i have downloaded the stable branch 92 from http://www.snapprefs-builds.com/view/Stable/job/SNAPPREFS%20-%20Official%20-%20stable/lastSuccessfulBuild/artifact/app/build/outputs/apk/snapPrefs-v25b92-debug.apk I tried to share but still scale is not working same result with previous build.

**Comment by M1kep** [comment]
@zevozki With @marzika no commit you would need to set the image adjustment method to SCALE

**Comment by valdeviant** [comment]
"Edit" comes up no-natter what adjustment method you choose, even none. Using stable build 92...
https://drive.google.com/file/d/0B9LpVLAINqS1Z1lRaXdrdjRWNHM/view?usp=drivesdk

**Comment by M1kep** [comment]
@valdeviant I'll have a build for you to try at some point in the near future

**Comment by zevozki** [comment]
@M1kep i have tried that too. Selected the method of adjustment to scale but still i am getting the exact result. Steps i did

1- in snapprefs I have selected method of adjustment to scale 
2-Share from gallery to snapprefs
3-Edit interface pops up, I did nothing  just selet the tick. 
4-snapchat app auto open  and I do share as normally as instructed on how to share images.
5- image shared is just cropped image like this
http://imgur.com/CIuLOoH

**Comment by zevozki** [comment]
@valdeviant exactly as you said

@M1kep valdeviant is right.

**Comment by M1kep** [comment]
@zevozki and @valdeviant  can you try this and upload a log please.

http://www.snapprefs-builds.com/job/SNAPPREFS%20-%20M1kep%20-%20development/lastSuccessfulBuild/artifact/app/build/outputs/apk/snapPrefs-v25b201-debug.apk

**Comment by M1kep** [comment]
* Edited Link ^

**Comment by zevozki** [comment]
@M1kep I have downloaded and done testing.  With Your build im able to share scaled images successfully. 

Things to note in this build. 
1- the edit interface is now gone and sharing is now as previous. From gallery share by snapprefs > snapchat lunch automatically...etc.

2- image adjustment method in snapprefs working ok with "Scale"  and "None"  but not with "Crop". 

So I can confirm the scale and none working perfectly.

**Comment by M1kep** [comment]
It appears the current issue is with the preferences not propagating correctly. Either @Andrerm124 or @marzika would be better suited for looking into that, it seems that I can get it to work with multiple force closes and spamming the setting

**Comment by valdeviant** [comment]
Thanks, @M1kep ! Scale is working for me too. I've noticed that when you set the adjustment to none, the "edit" interface still comes up, and the picture being sent still gets cropped. But, instead of filling the screen on snapchat, the image stays in it's original cropped size.
https://drive.google.com/file/d/0B9LpVLAINqS1bXBlaDlPNHE3VjQ/view?usp=drivesdk

**Comment by valdeviant** [comment]
Steps: tried "scale" method with success. Changed adjustment to "none" and killed both SC & SP through settings. Shared image through gallery, "edit" interface pops up...

**Comment by M1kep** [comment]
Ya currently ONLY scale won't trigger the interface. I believe a sure fire way for the setting to take affect is a device restart :L

**Comment by zevozki** [comment]
@valdeviant
I have gone through your steps and yes I faced same behavior. 

However I have done something else to make scale working.  Just when you select Scale only kill SC only and let SP running.  Then test and let me know if scale is working in with my method.

**Comment by M1kep** [comment]
As a side note, the stable branch should work the same as my upload. All I added was additional logging

**Comment by zevozki** [comment]
@M1kep I was using the stable #92  in some stages in this topic and issue is present,  but your build fix my issue. So far only stable #92 is there so I believe your changes is not yet deployed in the next stable build. I will check it once its released.

**Comment by valdeviant** [comment]
BUMP.
problem persists on stable version 93...

**Comment by zevozki** [comment]
Im sticking with development 201 since its working with scale for me so far.

**Comment by zevozki** [comment]
Update, with stable 95 i managed to scale images if I do this method 
"However I have done something else to make scale working. Just when you select Scale only kill SC only and let SP running."

So development branch201 and stable95 behaving same for meantime however still not straightforward.

**Comment by marzika** [comment]
Should be fixed in https://github.com/marzika/Snapprefs/commit/ed76e4970bb51c9598dde1fb5b4a2bcec9e94b76 without having Snapprefs open, if you still have the issue, post here.

**Comment by zevozki** [comment]
Update.  After stable 96.
Its seems work well but something to note. 
If the selection image adjustment method scale,  crop it will work smoothly.  But if none then the editor will pop up. If want to select back either scale or crop then both sc and sp need to be force closed to make it work.  Its not an issue but this is how it works. 

This issue can be closed for now.  Well done developers!
