### ISSUE TITLE
"Chat" title returns line before "t"

### ISSUE THREAD

**Issue by inv0ke** [marzika/Snapprefs#344]
## Expected Behavior

"Chat" to be all inline on the top

## Current Behavior

http://i.imgur.com/gO48N44.png

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Swipe to Chats

## Context

The padding(?) of the text where it says Chat is enlarged, simply reporting the bug so it can be fixed if it hasn't been already.

## Your Environment

* Version used: SC 9.39.5.0 / Current stable build of SP
* Android version:  Galaxy S4 / Android 4.3
* Xposed version and type (systemless or regular)  Regular on 2.6.1
* Root version and type (SuperSU, phh, etc. and system or systemless):  SuperSU System via Towelroot (?)
* Do you use any root/xposed hiding? If yes, which?: None

**Comment by marzika** [comment]
Snapprefs has nothing to do with it.
