### ISSUE TITLE
Not sending to all.

### ISSUE THREAD

**Issue by iiTranquility** [marzika/Snapprefs#351]
## Expected Behavior

You should be able to send a snap to everyone via the button at the top, using select all, and it should send fine.

## Current Behavior

From time to time, no matter if I reboot the app or force close Snapprefs, I can't send a snap to everyone.

## Possible Solution

No idea whatsoever.

## Steps to Reproduce (for bugs)

I'm not sure, it just doesn't work from time to time, but how to actually come across it?
1. Take a snap.
2. Press send.
3. Select all.
4. Press send again.

## Context

Trying to keep my streaks with everyone, but it doesn't send, so it effects my streaks.

## Your Environment

* Version used:  
* Android version: 6.0.1
* Xposed version and type (systemless or regular)  3.0 Alpha4. Regular.
* Root version and type (SuperSU, phh, etc. and system or systemless): SuperSU.
* Do you use any root/xposed hiding? If yes, which?: No.

Xposed log included, Logcat didn't bring anything important, unless you still want me to add it?
[error.txt](https://github.com/marzika/Snapprefs/files/628048/error.txt)

**Comment by marzika** [comment]
1) Fix your Xposed problems
2) You can only send to 200 people max.
