### ISSUE TITLE
back flash flashes but doesn't do anything to the image

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#353]
back flash flashes but it doesn't effect the image taken and the flash isn't applied to the image. On galaxy S5. Using #93 from Jenkins.

**Comment by M1kep** [comment]
Does this happen without snap prefs?

**Comment by ghost** [comment]
No it does not

**Comment by ghost** [comment]
https://drive.google.com/file/d/0Bx_frzjHj5vleDVrTkQzWTJzV2c/view?usp=drivesdk

**Comment by krugm0f0** [comment]
So you take a photo with the back camera, with flash enabled. The flash fires, but the picture is still dark?

**Comment by ghost** [comment]
Yes that is correct

**Comment by TehMerkMods** [comment]
@marzika @Implacity What happens is the back camera takes the photo as the flash is turning on, happens with me on S7 Edge, The photo is instant the way to combat this is to tap first to "focus" then as the flash is on take the photo.

If I can log into snapchat again sometime today xD I Will show a video

**Comment by marzika** [comment]
Snapchat issue.
