### ISSUE TITLE
Sharing image from gallery then edit issue

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#354]
Basically share an image from gallery via snapprefs/snapchat then use any one of the following: paint tool, text caption, stickers/emojis -> you are no longer able to share it to your story and I think the message gets sent as snapchat message instead of an image snap. However you can add filters to the shared image and send it as a snap message fine

**Comment by marzika** [comment]
Sorry, Snapprefs cannot fix someone's inability to read a dialog that covers the whole screen.
