### ISSUE TITLE
Just took the brand new snapprefs update for the 7th of december and the lens collector settings will not apply to my snapchat. It will only give me the default ones that snapchat provides.

### ISSUE THREAD

**Issue by knoxjosh39** [marzika/Snapprefs#355]

**Comment by M1kep** [comment]
Wow, loving the description. 

What branch and build are you using.

**Comment by M1kep** [comment]
Also screenshots and a log file could be of use

**Comment by zevozki** [comment]
With stable 95  +1
 i have same issue. Lens collection not working,  only defult lens of sc.

**Comment by marzika** [comment]
Should be fixed here: https://github.com/marzika/Snapprefs/pull/358
