### ISSUE TITLE
9.31.1.0 no longer supported by Snapchat

### ISSUE THREAD

**Issue by sexlinebling** [marzika/Snapprefs#360]
You can no longer login with the 9.31.1.0 apk, even without xposed installed

**Comment by valdeviant** [comment]
Yeah, Snapchat  blocked it via server. Update

**Comment by sexlinebling** [comment]
Thought snapperfs only works on 9.31.1.0

**Comment by valdeviant** [comment]
The latest stable release works for 9.39.5.0
