### ISSUE TITLE
Nougat Multitasking/Splitscreen support

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#362]
It would be interesting to explore allowing Splitscreen with Snapchat on Nougat as the app currently says it doesn't support it, but it would be a nice feature to have.

**Comment by NightMean** [comment]
Xposed for Nougat isn't out yet if I'm correct and changing any settings in snapprefs requires killing snapchat so splitscreen technically won't work

**Comment by gordiclazar** [comment]
@mhsjlw I dont understand why anyone would want multiwindowed snapchat?!?! So you can see just half or the pictures you get or to see just half of the picture you are trying to make??? Its so useless and pointless...

**Comment by ghost** [comment]
For chatting, while watching YouTube for example

**Comment by gordiclazar** [comment]
@mhsjlw If you mean playing youtube music you can do that in background with other xposed modules... again you cant text and watch video at the same time, only thing you can is play music and text which doesnt require multiwindow.

**Comment by ghost** [comment]
> watching

I can currently watch YouTube while chatting in Slack for example and I quite enjoy it. I'd like to do the same with Snapchat. This is just a suggestion, I'm willing to take constructive criticism.

**Comment by gordiclazar** [comment]
@mhsjlw I can see what you mean, but still i dont feel like it is so useful feature to have... besides that i dont know anyone who uses snapchat for intensive messaging. Whatsapp, viber, kik,.... there are so many way better msg apps to use in multiwindow. Im just not sure if all the trouble of introducing multiwindow support to SC and snapprefs is worth the reward in the end.

**Comment by marzika** [comment]
Cannot be done RN.
