### ISSUE TITLE
Add audio record and device sound support for wired selfie sticks (and headsets)

### ISSUE THREAD

**Issue by KallePlayer** [marzika/Snapprefs#367]
Wired selfie sticks uses the 3.5 mm jack to send the command "Volume Up" since this is the universal Android (and iPhone) button for taking a photo. It can register a long press and thus also record videos in SnapChat.

The problem is that the devices recognize wired selfie sticks as headsets and therefore disables the built in microphone and speakers making all videos captured mute.

Would it be possible to add a "Selfie Stick / Headset feature"? Preferably as a toggle switch on the main SnapChat window. This would force the device to use the build in microphone and speakers which would make wired selfie sticks fully compatible with SnapChat (if issue #366 also gets resolved). This would benefit actual headsets as well because, from my experience, the headset microphone picks up sound very low and you still can't record the sound from lenses here either.

**Comment by M1kep** [comment]
Not sure we'll be able to implement this seeing as snapchat doesn't have this, but I can take a look into a preference for #366

**Comment by marzika** [comment]
Cannot be implemented on our side.
