### ISSUE TITLE
Autosave sent snaps only saves text/drawings/stickers but not the photo.

### ISSUE THREAD

**Issue by SilverSix** [marzika/Snapprefs#369]
## Expected Behavior
In previous builds, autosaving sent snaps saves the snap flawlessly as received by the end user.
(Working on v2.0.0 compatible with SC 9.31.1)

## Current Behavior
Photos taken on Snapchat do not disappear when sent, but autosaving sent snaps saves any text, stickers, filters, etc on a black background; photo taken is missing. Sharing from gallery does not change the behavior. Applies to both videos and pictures.

## Context
Having snaps autosaved saves time in comparison to Snapchat's "save to device" now called "memories." It usually takes a long time, while saving snaps via Snapprefs is nearly instant.

## Environment
* Version used: 2.0.0 beta for SC 9.39.5
* Android version: Exodus ROM 6.0-20161112 (Marshmallow 6.0)
* Xposed version and type (systemless or regular): Systemless Xposed 86.5
* Root version and type (SuperSU, phh, etc. and system or systemless): phh's Superuser for Magisk r266
* Do you use any root/xposed hiding? No.

## Files
Took a random picture, added a filter, text, drawing, and sticker. Snap was sent to myself.
### Image as saved by Snapchat/Memories:
![saved by sc](https://cloud.githubusercontent.com/assets/21166192/21477079/637a5e2c-cb0c-11e6-9d31-e0e5f366ef56.jpg)
### Image as saved by Snapprefs via Save Button on Received Snaps
![saved by sp receivedsnaps](https://cloud.githubusercontent.com/assets/21166192/21477077/6376f048-cb0c-11e6-9e6e-bee2d39d1158.jpg)
### Image as saved by Snapprefs via Autosave Sent Snaps
![saved by sp sentsnaps](https://cloud.githubusercontent.com/assets/21166192/21477078/63771d0c-cb0c-11e6-8b7a-f6c5471c8205.jpg)
### Logcat
[Snapprefs.txt](https://github.com/marzika/Snapprefs/files/672636/Snapprefs.txt)

**Comment by M1kep** [comment]
I am unable to reproduce this issue on 2.1.0, @SilverSix can you try uninstalling the beta, restarting, and then installing the official 2.1.0 for 9.39.5 and enable and restart?

**Comment by SilverSix** [comment]
Issue is not present as of the latest stable release. Issue closed.
