### ISSUE TITLE
Snapprefs crashes immediately when pressing "Chat Logs"

### ISSUE THREAD

**Issue by PEEKPerformer** [marzika/Snapprefs#373]
[2016-12-27-03-13-20.txt](https://github.com/marzika/Snapprefs/files/675932/2016-12-27-03-13-20.txt)
Here is a logfile detailing the crash.

## Expected Behavior
The new chat logs feature functions as intended.

## Current Behavior
The snapprefs application crashes and the chat logs are not displayed.

## Steps to Reproduce (for bugs)

1. Open Snapprefs App
2. Tap "Chat Logs"
3. App crashes instantly
4.

## Context
 Use this feature

## Your Environment

* Version used:  2.1.0
* Android version:  6.0.1
* Systemless Xposed 87.0
* Root version and type (SuperSU, phh, etc. and system or systemless):  Systemless phh
* Do you use any root/xposed hiding? If yes, which?: None

**Comment by PEEKPerformer** [comment]
https://stackoverflow.com/questions/20440327/failed-to-chmod-warning-in-kitkat-when-trying-to-openorcreatedatabase

Just deleted the stale database with a different UID.

**Comment by M1kep** [comment]
Seeing as you filtered the log incorrectly and missed the actual error, we can't be sure why it crashed. That chmod issue isn't related to the crash as it appears for most users.
