### ISSUE TITLE
FC while opening Premium & Deluxe settings

### ISSUE THREAD

**Issue by yeezy69** [marzika/Snapprefs#376]
I'm deluxe user. I became a force close while opening Premium & Deluxe settings. I tried to delete snapprefs app-data, but it didn't help.

Snapprefs Version: stable build 102.
Regular xposed on Oneplus 3 with CM13/RR.

[logcat.txt](https://github.com/marzika/Snapprefs/files/680002/logcat.txt)

**Comment by M1kep** [comment]
Found the issue, I'll fix the build server in a sec

**Comment by M1kep** [comment]
@yeezy69 If you can please try [Build 103](http://www.snapprefs-builds.com/job/SNAPPREFS%20-%20Official%20-%20stable/103/) and let me know if that fixes it

**Comment by yeezy69** [comment]
Build 103 works fine for me! Thank you! :)
