### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by DankMemeGuy** [marzika/Snapprefs#377]
The entire site (snapprefs.com) is down, including the reset button for the IDs. Will it ever be possible to have this process done in-app so the website going down doesn't delay?

**Comment by marzika** [comment]
The host fucked something up with the domain, we have to wait until they sort the issue out.
How would it be possible to communicate with the server - where your ID is stored - in app or anywhere else, when the server is offline?

**Comment by marzika** [comment]
The server is online again.

**Comment by DankMemeGuy** [comment]
Seems down again?
