### ISSUE TITLE
Only two SnapChat lenses available - Lens-database

### ISSUE THREAD

**Issue by KallePlayer** [marzika/Snapprefs#382]
I recently factory reseted my device. After installing SnapChat again (9.39.5.0) I only got 4 lenses. The dog, the deer, face swap and face from an image.

Now the latter two also disappeared and I'm just left with the dog and the deer lenses. Disabling SnapPrefs and rebooting the device does nothing. Is it limited by SnapChat themselves because you run an old version? And if so, is there any Snapprefs official Lens-database you can download?

What about having a lens-database maintained with the newest lenses so we can enjoy the new lenses on this old version of SnapChat if the above is in fact the case?

**Comment by a-elkaim** [comment]
Snapchat stopped providing lenses from 9.39.5.0, the only way to have lenses is now to use the ones you have collected or found online

**Comment by KallePlayer** [comment]
Sadly I haven't collected any lenses.

> Is there any Snapprefs official Lens-database you can download?
> 
> What about having a lens-database maintained with the newest lenses so we can enjoy the new lenses on this old version of SnapChat?

**Comment by PotentialIngenuity** [comment]
I have kept a db up to date with all the lenses here.
https://www.reddit.com/r/snapprefs/comments/5cbeww/request_lenses/

**Comment by KallePlayer** [comment]
@blake1029384756 Cool, thanks.

Since I'm a bit paranoid I'd like to know what exactly Lenses.db and Lenses-journal.db contain and if importing those files from an "unknown" source could be dangerous in this case. For example, do they store any personal information?

Also I'm curious, how do you save the lenses from the latest SnapChat?

**Comment by alexhulbert** [comment]
@KallePlayer just open them with a sqlite editor if your scared. But they're database files (and not exeutables), so you really shouldn't be worrying anyway.

**Comment by Andrerm124** [comment]
@KallePlayer as the person that made the lens collection and system I can safely say there's nothing dangerous about the db. The worst that could be done is that they put in a custom lens (Or replace lenses) which has different images/audio/models etc. 

However that being said, installing things from untrusted placed is obviously not advised but if you'd prefer, you can use my own personal Lenses.db. It likely has a few less lenses but as I made the system you can rest assured that it's safe

https://drive.google.com/file/d/0Bx2tM5wp4t-nekl5dVhka0ZSU2c/view?usp=drivesdk

**Comment by KallePlayer** [comment]
Thanks. I was unsure since the database contains download links and if they could be changed to make Snapprefs download malicious software for example.
