### ISSUE TITLE
Snap previewed as picture eventhough video 

### ISSUE THREAD

**Issue by avi312singh** [marzika/Snapprefs#383]
Don't know if this is a SR or SC issue but when I record a video snap sometimes it is displayed as a picture from the last frame of the video, basically a standstill image of the last frame of the video. This happens 80% of the time when SC has been closed and is started up again, so basically first time start.

**Comment by TehMerkMods** [comment]
This Is SP Happens to me as well.

**Comment by marzika** [comment]
Snapchat issue.
