### ISSUE TITLE
Disable SafetyNet?

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#384]
## Your Environment

* Version used:  Latest Stable Build 13hrs Ago From Post
* Android version:  6.0.1
* Xposed version and type Regular 
* Root version and type SuperSU
* Do you use any root/xposed hiding? If yes, which?:N/A

Can we disable Safety net atall? Not being able to login does my nut in even after removing Xposed I still can't get in.

**Comment by quorn23** [comment]
When you look through XDA and the web you will quickly find out this is not possible.

What you can do is look up Magisk, so you can (after a proper unroot) use Magisk and systemless xposed. This way you only need to disable xposed and do a reboot to bypass SafetyNet in general. 
Head over to the Magisk section on XDA, you most likely will find all answers to questions you might have regarding Magisk and systemless root :)

**Comment by TehMerkMods** [comment]
@quorn23 my only problem with Magisk is I've heard allot of bad stuff with the S7 Edge....

**Comment by quorn23** [comment]
I don't own a Samsung Device, so i don't have any experience with Magisk and Touchwiz, but i recall seeing a thread about Samsung devices in the Magisk section.
I do like Samsung devices in terms of hardware, handy little devices, but it might worth looking for an AOSP based Rom

**Comment by marzika** [comment]
Not an issue of Snapprefs.
