### ISSUE TITLE
Feasibility of disabling SnapChat account logout

### ISSUE THREAD

**Issue by alexhulbert** [marzika/Snapprefs#386]
Hi! I'm upgrading to (rooted) Nougat soon, but I really love SnapPrefs and the features it offers. So, to continue using Snapchat and SnapPrefs, I'm going to emulate it on my laptop. I've tried this and it works,

However, if I want to use SnapPrefs on my laptop, I have to sign back in on my phone the next time I use it and vice versa. Snapchat logs you out of one device when you enter another.

Is there any way to share the tokens, etc I'm using on one account to another account so that I can access snapchat seamlessly from both devices? 3rd party clients such as Casper provide this functionality, but I'm afraid of getting banned and I prefer using SnapPrefs anyway.

If this isn't already a possibility and no one's willing to try and implement it, could someone who knows how the login system work at least instruct me on patching this in myself? I don't mind putting a bit of elbow grease into getting this working.

Thanks, 

Alex Hulbert

**Comment by psylenced** [comment]
I believe this is already possible.

People have been using Titanium backup for example to backup and then restore the app on 2 devices.

Both are able to be used at the same time without any logging out.

I believe when you perform the act of logging in, SC generates a new token which will invalidate previous tokens - sharing the same is fine.

So if you can get Titanium installed on your emulator, give that a go and see how it works.

**Comment by alexhulbert** [comment]
Awesome; Thanks!

**Comment by stevesbrain** [comment]
@Taconut Out of curiosity, which emulator are you using? :)

**Comment by alexhulbert** [comment]
i was using Genymotion with the ARM compatibility layer. It didn't end up working (any version other than the latest logs itself out), but I've kind of just abandoned SnapPrefs instead. I feel better about myself for not cheating the system, and I can use a screen recorder for those times when it is absolutely necessary to screenshot something.

It works if I have both snapchat instances on the latest version. I may not have SnapPrefs, but now at least I can browse my friends' stories on my laptop.

**Comment by stevesbrain** [comment]
@Taconut Appreciate the response - thanks! :)

**Comment by marzika** [comment]
Just transfer the backups.
