### ISSUE TITLE
Snapprefs-Builds.com not working

### ISSUE THREAD

**Issue by stevesbrain** [marzika/Snapprefs#387]
If snapprefs-builds.com isn't run by/directly related to this project, then accept my apologies and please close the ticket :)

## Expected Behavior
Snapprefs-builds.com website loads normally

## Current Behavior
Snapprefs-builds.com website attempts to load normally, but leads to a page describing the following:
```
SSL has been disabled

Due to Jenkins's functionality, SSL has to be disabled.

You attempted to connect over https, which would have broken your connection.


You will now be redirected to the correct URL.
```

This occurs *when* visiting over HTTP - not over HTTPS. The page refreshes every 5 seconds.

## Steps to Reproduce (for bugs)
1. Visit http://www.snapprefs-builds.com in your web browser
2. Observe

## Context
Was trying to grab the latest build when I stumbled across this configuration issue.

## Your Environment
Not really relevant as it happens from any browser/OS.

**Comment by krugm0f0** [comment]
Seeing the same behavior.

**Comment by svg-frog** [comment]
@krugm0f0 and @stevesbrain 
Sorry! I'm the one that runs snapprefs-builds.com - seems like the SSL stripping sorta broke with one of Jenkins' automatic updates.

Working on it now.

**Comment by svg-frog** [comment]
@krugm0f0 @stevesbrain 
Issue has been resolved. Thanks for reporting!

**Comment by stevesbrain** [comment]
Thanks for running it, @ElectronicWizard - and thanks for getting it fixed so quick :)
