### ISSUE TITLE
Auto regeneration of Obfuscator.java 

### ISSUE THREAD

**Issue by psylenced** [marzika/Snapprefs#388]
Just thinking out loud here.

It's my understanding that the updating of Obfuscator.java for new versions requires a whole heap of changes and research, which takes a lot of time.

What is the possibility of creating a few regex/grep searches which help identify the method names based on signature from a source dump?

Basically some sort of auto-regeneration of this file which can be run each version, requiring updating only the methods/classes which no longer match with most of them being discovered automatically.

**Comment by marzika** [comment]
Duplicate https://github.com/marzika/Snapprefs/issues/36 .
