### ISSUE TITLE
Replying to a snap, take picture and send button inoperable. 

### ISSUE THREAD

**Issue by nicholas9543** [marzika/Snapprefs#389]
Been having this issue for a while now. I'm going to try to be as detailed as I can. I have narrowed it down to in app notifications not being displayed making some functions inoperable. Very annoying and loose snaps because of this. 
Problem 1.
In the event of a double tap to snap friend 1 to reply, after viewing a snap from them. Camera opens, if friend 2 sends me a snap/chat (any notification) while on the camera screen the take picture button is frozen. Going to received snaps screen seems to fix this unless another notification happens to comes in while on the camera screen. 

Problem 2
In the event of a double tap to snap friend 1 to reply, after viewing a snap from them. Camera opens, take your picture/video, make caption. (knowing a background snapchat notification comes in) Then send button at the bottom does not work nor the bar to add a recipient. Hitting the home then recent apps buttons is a temporary get around. It will do it back to back unless the application is force stopped. Sometimes trying to send will create a force close but it's not consistent. Usually happens when 5 notifications come in at once.

**Comment by marzika** [comment]
Duplicate https://github.com/marzika/Snapprefs/issues/385 .

**Comment by alexhulbert** [comment]
I had this issue a few months ago. Not even factory resetting helped.
