### ISSUE TITLE
You're using an old version of Snapchat that may stop working soon (9.39.5.0)

### ISSUE THREAD

**Issue by KallePlayer** [marzika/Snapprefs#390]
SC version: 9.39.5.0

I just received this chat message from teamsnapchat 50 minutes ago while watching stories:

> Hey! 👏 You're using an old version of Snapchat that may stop working soon. Tap [here](https://play.google.com/store/apps/details?id=com.snapchat.android&hl=en) to update!

I'm guessing they'll drop the support for this old version pretty soon.

**Comment by marzika** [comment]
Update branch has been already opened.
