### ISSUE TITLE
Update Branch Build 40 Not Working

### ISSUE THREAD

**Issue by Efficacy28** [marzika/Snapprefs#393]
**If build 40 of the update branch isn't supposed to work yet,
then I apologize and please close this issue.** _Else..._

I have SC 10.6.6.0 (1092) installed and SP doesn't seem
to hook onto SC as I observed no added functionality.

Here's a log if it'll help: 
[log.txt](https://github.com/marzika/Snapprefs/files/975271/Log_2017-05-03_22-42-09.txt)

**Comment by crxed9** [comment]
It's not supposed to work yet.
