### ISSUE TITLE
I get random nonstop vibrations while viewing pictures and videos. This didn't happen until I updated snapprefs and snapchat. It doesn't happen when snapprefs is disabled

### ISSUE THREAD

**Issue by ghost** [marzika/Snapprefs#41]

**Comment by dkisselev** [comment]
There's a bug where saving a picture causes the phone to vibrate for 10 seconds.

I'm guessing you have auto picture saving turned on, so it will save and vibrate any time it loads a new photo from someone.

Marz knows about the bug but we just have to wait until the next release.
