### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by gpollo** [marzika/Snapprefs#42]
My understanding of the issue isn't really clear, sorry about that. From what I understand, Snapprefs saves a story each time I watch it. It creates a lot of duplicated files. I'm pretty sure it saves the file multiple times without me even watching the story multiple times. It is the unclear part.

_EDIT_:
I did some testing and here's a better review of the issue. I removed all saved snaps, then I watched a random snap and Snapprefs saved 6 identical files...
**Phone**: _Nexus 5 with Cyanogenmod 12.1_
**Android version**: _Android 5.1.1_
**Snapchat version**: _v9.20.2.0 Beta_
**Snapprefs version**: _1.6.3_
**Xposed framework version**: _78.0_

For the time being, I wrote a small bash script that filter and moves duplicates. Here it is if someone is interested: https://gist.github.com/TheNiceGuy/262ac6a2c7107acf7ac2. It basically hashes each file and checks for duplicates. It does not remove duplicate Stories with ReceivedSnaps, they are checked separately. Thanks.

**Comment by nihilim** [comment]
confirming same issue on several devices.

**Comment by kubob** [comment]
Same problem.
Device: HTC One S
Cyanogenmod 12.1
Snapchat version: 9.21.1.0
Snapprefs version: 1.6.5
Xposed framework version: 79.0

**Comment by ghost** [comment]
Hello, I have the exact same issue, on version 1.6.5 of snappref. I'm on marshmallow, my phone is a HTC M9, running the Viper ROM. 

Notice the timestamps here, indicating that the images are saved within milliseconds of each other http://i.imgur.com/u0kmgDb.jpg

Cropping made to protect the sender's username :-)

**Comment by marzika** [comment]
Fixed:

https://github.com/marzika/Snapprefs/commit/5942512ab487ffa25c73b7b40a3d446fc78339d7

**Comment by ghost** [comment]
Very nice! Thank you!
