### ISSUE TITLE
Snapchat doesn't use the system's font when Snapprefs is enabled

### ISSUE THREAD

**Issue by gpollo** [marzika/Snapprefs#46]
**Phone**: _Nexus 5 with Cyanogenmod 12.1_
**Android version**: _Android 5.1.1_
**Snapchat version**: _v9.21.1.0_
**Snapprefs version**: _1.6.5_
**Xposed framework version**: _78.0_

Hello,

I use iFont to change the system's font. It used to work with Snapchat/Snapprefs (v9.20.2.0 Beta/1.6.3), but when I updated both of them (v9.21.1.0/1.6.5), Snapchat no longer used my custom font. Disabling Snapprefs in the Xposed framwork fixes the problem. Am I missing some options in Snapprefs to change the font or is it unintended?

Thanks

**Comment by marzika** [comment]
Snapprefs doesn't change anything font releated. Please report the issue to the other module, there is probably an unexpected error while modifying fonts in a hooked app.
