### ISSUE TITLE
Update for snapchat version 9.22.0.2

### ISSUE THREAD

**Issue by artemegion** [marzika/Snapprefs#47]
Could You possibly update this awesome module to work with latest Snapchat version?

**Comment by NightMean** [comment]
Be patient! -,- Marz will work on it when he wants and not someone say.. He's normal person as you are...

**Comment by artemegion** [comment]
@NightMean I'm just kindly asking man. Somewhere else he said he's using iPhone for daily usage so he may not even noticed that there was an update for android.

**Comment by NightMean** [comment]
Okay but it has been asked so many times on xda so it's annoying.. mostly for Marz.Yes he's but he have an old samsung which he use for testing snapprefs.Also if he wants to check for latest version he can go to apkmirror and as far as I know the versions on android and ios should be the same but I'm not 100% sure

**Comment by marzika** [comment]
I have stated numerous times, that I will not update the app until I
finished my exams. I know there have been updates to Snapchat.

**Comment by marzika** [comment]
There is no reason to have two issues opened for the same issue.

https://github.com/marzika/Snapprefs/issues/49
