### ISSUE TITLE
A few visual UI bugs 

### ISSUE THREAD

**Issue by raku-cat** [marzika/Snapprefs#48]
Not sure how many of these you are aware of, the current app at the time of me posting this though has a couple issues.
In the "Buy/Activate membership" menu, the field to request your username for godmod has no button under it, I don't have premium so I don't know if that's something that only pops up after you've done that or what, if that's the case then ignore this. 
Another bug is in the visual filter store, when you click "Manage Visual Filters" the list comes up with a transparent background and pressing back exits out of the entire visual filter store screen. Everything else is looking good, I can separate this in to two issues or provide screenshots etcetera if needed.

**Comment by marzika** [comment]
The button is only displayed for the deluxe users. That manager has been rewritten since then.
