### ISSUE TITLE
Snapprefs still developing or development is stopped? 

### ISSUE THREAD

**Issue by cancer-ian** [marzika/Snapprefs#52]
It's been around 3 to 4 months since snapprefs update, link to XDA has also been closed and it is stated that it will reopen once update has arrived. There is no clue of any new update which was said to be released very soon by Marzika. Please tell us if an update is being developed and if it is then when will it get launched?

**Comment by marzika** [comment]
The latest commit was pushed 11 days ago. It will be released at the exact time when people will learn that none of them own me or anyone, just because they bought a 2.99$ license and acknowledge the fact that I do not own anyone anything, be it my freetime or support for newer versions.

**Comment by savvyMatthew** [comment]
@marzika Totally agree with you. It's crazy how bad the XDA thread got. 

Hope school is still going well for you, grades first right lol.
