### ISSUE TITLE
Snapprefs still developing or development is stopped? 

### ISSUE THREAD

**Issue by cancer-ian** [marzika/Snapprefs#53]
My last thread was closed by Marzika with a reply that he will update snapprefs when everyone learns that he doesn't own anyone anything and stuff. Well FYI everyone knows that. People learnt that the same day you closed XDA thread.  It would be better if you say clearly if you are ever going to launch or you are just developing it in freetime for timepass of yours or never going to launch. With your response we can know to update our snapchat and not stay on 9.21.1.0

**Comment by NightMean** [comment]
He clearly stated that the last branch update was 11 days ago... so yes,it's still in developement.Also you can search the xda with the beautiful search icon and write there Update and click seach... You would get the same information over and over again
