### ISSUE TITLE
[REQUEST] Block snapchat's attempts to detect xposed

### ISSUE THREAD

**Issue by scottopell** [marzika/Snapprefs#54]
Snapchat started detecting the xposed framework files and blocking login attempts.

This xda link goes through different users workarounds and strategies:
http://forum.xda-developers.com/xposed/snapchat-rooted-phones-xposed-t3283198

From what I can gather from that thread and my personal experiences, snapchat seems to be checking for the xposed files during the initial login, and not after.

I have had two interesting experiences myself:
1. After failing to login on an xposed device, I could uninstall the xposed APK, uninstall snapchat, reinstall snapchat, and fail to login. I haven't tried uninstalling the xposed framework yet.
2. On a second device, I can still login to my account, so there doesn't seem to be any evidence that snapchat is blacklisting accounts on the server side.

I don't have any experience developing for xposed, and a small bit of experience with android development in general, so as a question for the devs here, would it be feasible to intercept this call and override the return value? Naively I would assume that snapchat is simply `stat`ing the file, or the java equivalent, and we could just return `E_NOSUCHFILE` or whatever.

**Comment by marzika** [comment]
Snapchat itself does nothing, the only thing that does the check is SafetyNet. https://github.com/pylerSM/NoDeviceCheck/issues/3
