### ISSUE TITLE
[REQUEST] Fix Navbar Overlay Bug

### ISSUE THREAD

**Issue by dylanraga** [marzika/Snapprefs#55]
Ever since Marshmallow (and some Lollipop devices) a lot of users that have software keys have problems with them overlapping with Snapchat's bottom buttons

I'm wondering if it's possible to fix this via an enhancement on your module? Like an option to raise the bottom of the app 48dpi (or w.e the size of the navbar) if the option is enabled. Thank you.

**Comment by joexn** [comment]
Just confirming this isn't a problem on the Nexus 5 & 6P

**Comment by marzika** [comment]
They have a method which returns a boolean depending if they should enable or disable the bottom padding. I have already made a hook for that for a separate project so merging it into Snapprefs shouldn't be a problem. Expect it in the next release.

**Comment by joexn** [comment]
Just a quick question, will the next release be made for the latest Snapchat version or will there be a set version of Snapchat you'll have to use?

**Comment by savvyMatthew** [comment]
I had a similar problem,  but I just force immersive mode. 

A different problem I have is after I take a picture my snap is blurred at the bottom.  With or  with out immersive mode. It sends the pictures like that. Witch I find odd. It's very annoying.  

http://i.imgur.com/8GW7ESd.jpg

Oh this is a snapchat problem not snapprefs.
Just brought it up, sounds somewhat related to the other problem

**Comment by marzika** [comment]
Added options to force it to hide or show. It will be in General -> Misc. .

https://github.com/marzika/Snapprefs/commit/18360df55730d5ac1dba6818c4d238d4d8c4c140
