### ISSUE TITLE
Best place to watch for updates?

### ISSUE THREAD

**Issue by kwest12** [marzika/Snapprefs#56]
Hey there, now that the xda thread is defunct, I'm wondering what the easiest place is to get notified of the next update, whenever it happens to be released.  I know in that past you've posted to your Snapchat story, teasing releases.  I also seem to recall you posting to Instagram now and then, which actually would be the easiest solution, seeing as how I could set Instagram to notify me of posts from your account.  I'm just trying to narrow down where I should watch - could you tell me which is the best place?

Thanks!

**Comment by NightMean** [comment]
I would choose xda and turn on notifications for new posts,because Marz said that when there will be update he will post it to xda,also you can see it here on github but you will be receiving all changes which are happening to app

**Comment by kwest12** [comment]
Works for me.  Thanks for the response.

**Comment by PerryVerheij** [comment]
It would also be great if there would be a Pushbullet channel notifying you of updates.
