### ISSUE TITLE
Phone hangs when I tap on Snapchat icon with Snapprefs on

### ISSUE THREAD

**Issue by ChoyDarren** [marzika/Snapprefs#57]
This didn't happen on my OnePlus One or Note 4, but on my BLU Pure XL, if I have Snapprefs on and tap on the Snapchat icon, my phone stops responding to everything for a couple minutes. Screen touches and button presses do nothing. When it comes back, Snapchat may or may not be loaded, but within a minute of my phone being "usable" again, it crashes and restarts itself. Log is attached.

[xposed_error_20160418_162706.txt](https://github.com/marzika/Snapprefs/files/226336/xposed_error_20160418_162706.txt)

**Comment by marzika** [comment]
The only error I see is that you have the multi filter option enabled, but you don't have any filters in the folder. There is no reason Snapprefs would cause that huge of a hang as everything is running in a separate thread or ASync.

**Comment by ChoyDarren** [comment]
Unfortunately, Snapprefs seems to be the culprit for my phone. When I uncheck Snapprefs in Xposed Installer, restart my phone, and tap on the Snapchat icon, it loads just fine. When I check off Snapprefs in Xposed Installer, restart my phone, and tap on the Snapchat icon, my whole phone hangs.

**Comment by marzika** [comment]
Could you please make a logcat limited to com.snapchat.android then upload
it to a gist and attach it here?

2016-05-02 23:28 GMT+02:00 D168 notifications@github.com:

**Comment by ChoyDarren** [comment]
How do I do that?

**Comment by marzika** [comment]
https://wiki.cyanogenmod.org/w/Doc:_debugging_with_logcat

2016-05-02 23:35 GMT+02:00 D168 notifications@github.com:

**Comment by ChoyDarren** [comment]
[Logcat](https://github.com/marzika/Snapprefs/files/247394/ea4ce9e737036de4f4b200234377a9ee-8ee0a52443e6fdc3ca5f0b97118276e2ca5c84ff.zip)
Did I do this right?

**Comment by marzika** [comment]
I cannot seem to recognize anything that would cause the issue. It might be an issue with your ROM.

**Comment by ChoyDarren** [comment]
Alright. I guess I'll wait for the next version and see if my phone likes that any better. Thanks for your time
