### ISSUE TITLE
[Q] Obfuscation mapping tools

### ISSUE THREAD

**Issue by XspeedPL** [marzika/Snapprefs#58]
Hello!

I was wondering if you automate the process of mapping the obfuscated classes of SC in any way.
I mean, doing it by trial and error seems stupid.
Do you use some software to compare classes from different versions or anything?

Thanks

**Comment by marzika** [comment]
I'm using Kevin Mark's ProFinder. http://forum.xda-developers.com/android/software/profinder-proguard-obfuscation-tracker-t3183647
