### ISSUE TITLE
[Enhancement] Hooking "pinnable_stickers" in android_preferences.xml

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#61]
Hi ! I'm reviewing the way snapprefs & snapchat works (and it's pretty interesting)

Looking at the xml preferences of snapchat, I already saw that the lenses are forced by snapprefs, hooking the "is_device_whitelisted_for_lenses_on_backend" to true.

With a recent version of snapchat, (9.27 i guess, I'm not really sure) the 'pinnable stickers' were added. [This gif](http://giphy.com/gifs/3o6ozrHCZFjBhCrczK) is explaining what they do better than me , but it still works only with major devices, like lenses.
 A 'pinnable_stickers' value has been added to the preferences, and they work the same way as lenses : If it's set to true, these stickers are working, if it isn't, they won't 'show up'.
I'm thinking of hooking the 'pinnable_stickers' value to true, the same way as lenses, in the same file, with almost the same code, would it be possible ?

Thank you for your time and patience !

**Comment by marzika** [comment]
It's possible, let me know how it turns out.
