### ISSUE TITLE
Jenkins build fails

### ISSUE THREAD

**Issue by lgdolman** [marzika/Snapprefs#62]
Jenkins is currently failing on this build with the following error. 
<code>
:app:compileDebugJavaWithJavac/var/lib/jenkins/workspace/Snapprefs/app/src/main/java/com/marz/snapprefs/GcmBroadcastReceiver.java:13: error: class GCMBroadcastReceiver is public, should be declared in a file named GCMBroadcastReceiver.java
public class GCMBroadcastReceiver extends WakefulBroadcastReceiver {
       ^

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:compileDebugJavaWithJavac'.
  </code?

**Comment by marzika** [comment]
Rename the Java file to GCM....java, github didn't carry on with my filename change.
