### ISSUE TITLE
I still can not login, please help remove xposed

### ISSUE THREAD

**Issue by hakankocyigit** [marzika/Snapprefs#63]
can not be! The logon attempt failed temporarily. (I removed xposed)

**Comment by blvcklotus** [comment]
Did you flash the uninstaller/tap uninstall in the app?

**Comment by hakankocyigit** [comment]
xposed remove files with twrp

**Comment by hakankocyigit** [comment]
I raised xposed but still I can not enter SnapChat

**Comment by marzika** [comment]
It is not related to Snapprefs.
