### ISSUE TITLE
[REQUEST]  Screenshot hotkeys alerts snapchat of screenshot

### ISSUE THREAD

**Issue by kripz** [marzika/Snapprefs#7]
Since we already have automatic and swipe to save, please consider allowing the option of sending screen captured messages when the screenshot keys are pressed (in addition to actually saving the pictures as well).

**Comment by Ketrel** [comment]
I could see this being useful for when you want someone to know you took a screenshot.  Would it be possible to additionally (or alternatively) trigger the sending of the notification separately from actually taking a screenshot?

**Comment by AmineI** [comment]
Yeah, Something like "send screenshot alert when you save a snap" could be a useful feature :P.

**Comment by JohanSF** [comment]
I usually swipe up and down, it could be triggered by swiping left and right instead? But it would have to be tested so that it doesn't happen on accident.

**Comment by M1kep** [comment]
@marzika

**Comment by marzika** [comment]
Sorry, it will not be done, because people will come crying about pressing that accidentally.
