### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by tomifier** [marzika/Snapprefs#73]
I noticed a issue with groups. The issue is that people in groups get mixed up. For example: 

People A in A group
People B in B group
People C in C group 

When you choose the people, everything is fine nothing wrong. But then when you close snapchat or something the people in groups get mixed up like:

People A are suddenly in C group
People B are in A group for no reason.. and so on. 

I don't have a logcat of the issue as I went back to the stable version. It happens when alot of people are in the groups. It stays normal if only small number of people are in one group.

**Comment by marzika** [comment]
It's advised to force restart Snapchat when changing groups, that should solve this issue.

**Comment by marzika** [comment]
It should be fixed here, let me know if the problem still persists. https://github.com/marzika/Snapprefs/commit/4237273561f1b31c04d5afdae89d3c59e3fd97a6
