### ISSUE TITLE
Building from source 

### ISSUE THREAD

**Issue by M1kep** [marzika/Snapprefs#74]
If one wanted to use a extremely beta, no help offered version, how would they to abiut compiling this code?

**Comment by edi194** [comment]
Most of things are working correctly.

**Comment by M1kep** [comment]
But what steps would I take to compile it?

**Comment by edi194** [comment]
You need Android Studio and downloaded source of app. Then, you need to compile apk, it's easy.

**Comment by hbashton** [comment]
what about using it with a greater version of Snapchat

**Comment by AmineI** [comment]
To compile from source you need minimal knowledge on how to use Tools like Android Studio. There are many guides on the Internet, Google will help you for this one . But please this is not an issue but a simple question, this should be on reddit or somewhere else

**Comment by marzika** [comment]
You have to compile it just the exact same way like how you would do on any other Github hosted projects. The issues section is for issues with Snapprefs, not for a spoonfeeding thread like the XDA thread became.
