### ISSUE TITLE
[bug]Snapprefs integration menu 'not showing' ?

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#75]
Hi,
In snapprefs, I noticed that an option offers to show a snapprefs button integrated in snapchat.
While the sharing button is there, when pulling down / tapping the snap icon, I don't see this button. There are, as usual, the 'help' button, 'trophies', and snapchat settings at the top, + the 'add friends' things. What does it looks like, could I be missing it ? 
I can provide both Xposed Log & logcat if you need them, and my device is a Samsung with Android 4.2.2 .

**Comment by marzika** [comment]
If you can see the share icon, then you should be able to see it under the add friend, etc buttons.

**Comment by AmineI** [comment]
Nope, it's not there at all, Under "My Friends" I have a small arrow that returns back to the camera. Need a screenshot or a log ?

**Comment by marzika** [comment]
Xposed Log. What's your phone's resolution?

**Comment by AmineI** [comment]
540*960 . Xposed log is coming, i need to clean the unrelated entries / Reboot without the other modules

**Comment by marzika** [comment]
It probably doesn't show because it doesn't have enough space to show on your phone.

**Comment by hbashton** [comment]
when will you update the obfuscation classes to hook into the latest
Snapchat version?

**Comment by AmineI** [comment]
Okay, with all the other modules disabled, the 'open snapprefs' button now appears.After enabling them again and rebooting, the button won't appear anymore.
Since this seems to be related to another module's compatibility to snapprefs, I think it's outside of your work ? If it's still, I linked an [Xposed Log](https://github.com/marzika/Snapprefs/files/251301/xposed_error_20160506_002419.txt) showing both the entries from without other modules, then the reboot with these modules. Looks like a wild nullpointer exception appears when the other modules are enabled.
I think it's not useful yet, I'll take my time tomorrow to disable modules + reboot a lot to isolate the conflicting one.

**Comment by marzika** [comment]
If I had to take a guess XInternalSD would be mine.

**Comment by AmineI** [comment]
Why exactly do you think so ? As you probably know XInternalSD fake the stockage so that apps thinks my internalSD is my ExternalSD. I can't live without it since I'm with an already full 8Go device ;_; .
The first part of the log, labeled '22:16' is the one working (With Xtoast, MultipleWidgets, XInternalSD & Download2SD), and the second one made at 22:19 is the one where there is an issue.
Don't worry, I'll update the thread and the log when I'll found the culprit.

**Comment by marzika** [comment]
Because it crashes here:

```
       static File groupsDir = new File(Environment.getExternalStorageDirectory() + "/Snapprefs/Groups");
        ...
        File groupFolder = groupsDir;
        if (!groupFolder.exists()) {
            groupFolder.mkdir();
        }
        File[] groupFiles = groupFolder.listFiles(); <---
        if (groupFiles.length == 0) {
            groups.clear();
            return;
        }
```

listFiles() only returns null when an I/O errors occurs or the folder is not found. As you can see the if the folder is not found, it is created immediately, so the I/O error is the only case it should happen. XInternalSD is the only thing that messes with the External-Internal SDCard.

**Comment by AmineI** [comment]
Oh, yes it's seems logical.
But right now XInternalSD is enabled, and the icon is showing. I'm still trying, and Downloads2SD and Obb on SD aren't the culprits too. Could it be RootCloak ? I think it's enabled for the snapchat app, but not snapprefs

**Comment by AmineI** [comment]
Rootcloak was the culprit. I enabled it on Snapchat while trying to find a way to connect to snapchat without having to uninstall Xposed. I guess snapprefs try to su inside the snapchat context, and rootcloak prevent it. Then I'd be better disabling rootcloak for snapchat than you changing the way the context works. 
Thank you anyway :) !
