### ISSUE TITLE
[bug] Snapprefs crashes with "Show in launcher" option

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#76]
In General > Misc, the option "show snapprefs icon in launcher" makes Snapprefs crash every time I try to use it.
I use Android 4.2.2 and can provide a logcat if you need it

**Comment by marzika** [comment]
I need the logcat.

**Comment by AmineI** [comment]
Here's a [logcat](https://github.com/marzika/Snapprefs/files/251329/logcat.txt) of the issue. I basically opened the app, opened General > Misc and ticked the option. (Which, interestingly enough, was unticked while the app icon does appear in the launcher)

**Comment by marzika** [comment]
Ah, I forgot to push one of my commits. It should be addressed now at. Let me know if it still crashes.

https://github.com/marzika/Snapprefs/commit/5a1391bacf87160b5b58557728f1a092a0512153

**Comment by AmineI** [comment]
It isn't crashing anymore, but the option is still unchecked by default, while it should be checked (since, by default, the app is shown in the launcher)
Thank you for time !
