### ISSUE TITLE
[bug]Snapprefs crashes a lot after a 'clear app data'

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#77]
Hi,
When I clear snapprefs data, a lot of options (I'll try to remember all of them next time) makes the app crash if I check/uncheck them, but only once : after relaunching snapprefs once I never have any other crash when i use THIS option, until I clear data again.
Example : 
Clear app data, Launch snapprefs, open the menu and try to tap on "Spoofing" . This make snapprefs crash on my device. After relaunching it, the "spoofing" menu is accessible without any other crash.
Android 4.2.2 and I can provide logcat, as usual.

**Comment by marzika** [comment]
I need the logcat.

**Comment by AmineI** [comment]
Okay, I had fun reproducing this : It seems to be completely random. I tried multiple times, and each time it was another checkbox crashing. The [logcat](https://github.com/marzika/Snapprefs/files/251363/logcat.1.txt) was mainly the same each time : java.lang.Boolean cannot be cast to java.lang.String . I don't know if this will be helpful however.

**Comment by marzika** [comment]
This commit should fix it. Let me know if it still crashes.

https://github.com/marzika/Snapprefs/commit/17808d1197c6328bdfa18c798caac7eb032f3258

**Comment by AmineI** [comment]
I'll give it a try and if I get a crash again, i'll update this. By the way, each time I clear data before opening the app, I get one or two blank snapprefs notifications. I guess it's normal - for GCM debugging, right ?

**Comment by marzika** [comment]
It means that the registration is successful.
