### ISSUE TITLE
[bug] Snapprefs 'Save button' can't work with stories

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#78]
Hi again !

As usual, when viewing a story, tapping the bottom of the screen will open a chat with the author.
However, when I enable the 'save button' feature, it's so low that tapping it open the chat instead.

Like you suggested in another thread, it could be because of my 540*960 resolution though.

**Comment by TehMerkMods** [comment]
nope happens to me aswell on the s4 & s5

**Comment by edi194** [comment]
Single tap works like that, when you hold this button it works correctly.

**Comment by AmineI** [comment]
Ah, great to know, thank you ! I'll use this workaround.

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/commit/8e935366179ae59e0161af2ed75738cd4e0e3cf0 should fix it by disabling the onClickListener for the SwipeUpArrowView, while still being able to swipe up to open the Chat EditText. Let me know, if it doesn't work.

**Comment by FPSUsername** [comment]
I have v1.6.5 and don't have that save button feature. I assume that you use a self compiled version, is there a tutorial where I can  compile it myself (and which snapchat version matches)?

**Comment by AmineI** [comment]
This version is for the same snapchat as the released version (9.21.10) so don't expect a surprise upgrade there, and I think Google is better than us to teach you how to compile an android app :) .

Don't do this if you can't stand bugs & issues, the purpose of a development version is to report bugs and help development, you'll be better waiting for the next official version.
