### ISSUE TITLE
[REQUEST] Lenses and other features working with every snapchat version

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#79]
Hi agaaain !
Still checking the source code, I'm analyzing how the Lenses are forced on older devices.
I think the lenses are enabled 'only' by hooking the android_preferences file.

The presence of 'LensesProvider_GetLenses' and 'LensesProvider_Class' in the Obfuscator file probably means I'm wrong : in that case I'd be glad to know how it works ! (And you can dismiss the request since it can't be done in that case)

---

If I'm right and it only involves hooking android_preferences, could it be done separately from the other hooks ?

I mean, right now Snapprefs checks what version of Snapchat is launched, and will give errors if it's not compatible anyway, preventing the android_preferences hook to occur.
In that case, it could be nice to run this hook anyway, before everything else.

I'm probably totally wrong, so please give me a hint about that, I'm still studying and it's really interesting.
Sorry to bother you, and thank you again for your time !

**Comment by marzika** [comment]
These strings in the Obfuscator are not for forcing lenses, only the preference getting is hooked. I will not remove it from the version regulation as might as well change between versions.
