### ISSUE TITLE
[bug] Snapprefs 'Save button' often shows chat and keyboard instead of save

### ISSUE THREAD

**Issue by JaelMalax** [marzika/Snapprefs#82]
Sometimes the image is saved and shows toast message Picture saved but many times instead of save it slides out the keyboard and offer chat in Snapchat. No matter if I touch shortly or holding save button longer. I have Galaxy S6 with MM.

**Comment by marzika** [comment]
No reason to open an other issue for the same error. https://github.com/marzika/Snapprefs/issues/78
