### ISSUE TITLE
[Issue]New file explorer won't show hidden folders

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#83]
Hi !
In the saving preferences, snapprefs previously allowed to hide a folder 'Folder' by renaming it to '.Folder', and to save snaps in that folder.
However, with the new UI of the 'folder picker', hidden folders beginning with a dot won't appear, making it impossible to select them.

**Comment by marzika** [comment]
That's an invalid folder name, I have switched to a new file explorer library, which doesn't seem to allow that. Rename that library and use the hide folder option of Snapprefs to generate a .nomedia in the selected folder to hide it's content.

**Comment by AmineI** [comment]
Okay. I did it, thank you !
I guess the process could be automatised while updating snapprefs from <1.6.5 ?

**Comment by marzika** [comment]
If you are moving from a previous version it will save for your previously selected folder, from 2.0+ if you want to select an other folder like that (. prefix) you will not be able to.
