### ISSUE TITLE
[Bug] Groups FC snapchat

### ISSUE THREAD

**Issue by CrilleTheBoss** [marzika/Snapprefs#85]
When pressing on add new group snapchat force closes
Logcat = http://pastebin.com/TfeCvwwD

**Comment by marzika** [comment]
The log doesn't contain the crash.

**Comment by CrilleTheBoss** [comment]
Here is the log from xposed installer = http://pastebin.com/pmRc93g6

**Comment by marzika** [comment]
I told you, your logcat doesn't have the crash, take a new one.

**Comment by CrilleTheBoss** [comment]
I have tried taking news logs, they are all the same. In the first log I uploaded you can see that snapchat crashed. 
When it crashes there is no FC pop-up or anything Snapchat just closes completely and I have to reopen it again.

**Comment by marzika** [comment]
It doesn't show anything that would cause a crash.

**Comment by CrilleTheBoss** [comment]
I have tried taking many logs, it does not produce a useful crash report. Is there something I could do to locate this issue?

**Comment by marzika** [comment]
Maybe there is a problem with your logcat filters. If you cannot get a logcat of the crash I cannot see what the error is.

**Comment by marzika** [comment]
I have found a NPE when reading the Groups from the SDCard, could you please try with this new commit? https://github.com/marzika/Snapprefs/commit/8059d5cffe4184a6987a230e70797cd65e04bf5c

**Comment by CrilleTheBoss** [comment]
It did not fix the problem. I tried to filter "napchat.android" instead in the logcat
Here is the log http://pastebin.com/cdqJiVG5

**Comment by marzika** [comment]
Stil nothing, you could start capturing a log without filters just before crashing and stopping it right after it crashed, also please answer some questions:
1) Do you have a folder called Groups in /sdcard/Snapprefs ?
2) Do you have any files in it? If so how are they called?
3) Android version?
4) Are you a free user?
5) Do you happen to have an additional sdcard plugged in?

**Comment by CrilleTheBoss** [comment]
1. Yes
2. No
3. 5.1.1
4. Yes
5. Yes a 64gb micro sd card

[2016-05-10-02-56-35.txt](https://github.com/marzika/Snapprefs/files/256173/2016-05-10-02-56-35.txt)

**Comment by CrilleTheBoss** [comment]
I did some more testing. I tried it with my nexus 7 runnig aosp and it worked fine. It only crashes on my phone. (Samsung Galaxy Note 3 5.1.1, Phronesis rom v6.5)
It works if i add the group manually in /snapprefs/Groups. It shows up and functions correctly. But when trying to add a group or edit one snapchat crashes.(It crashes without FC popup)

**Comment by marzika** [comment]
I would suggest you checking for modules that interfere with internal/external storage. It might be the case that your ROM has a wierd permission set for the SDCard, which HandleExternalStorage will be able to solve.

**Comment by CrilleTheBoss** [comment]
I disabled all mods and modules except snapprefs, it didn't work. I installed the HandleExternalStorage module, and that doesn't work either.

**Comment by AlThani** [comment]
I have the same issue, using Galaxy S7 6.0.1, I'm using the internal storage, and I have an empty folder called Groups in /sdcard/Snapprefs and I'm a Deluxe user.

**Comment by LakuuPiipu** [comment]
Have the same issue when clicking add groups it crashes and the same with story blocking.
However you solved the issue i had with the new text tools. So it might be the same type of issue on this ?

**Comment by marzika** [comment]
Unless someone gets a proper logcat of the crash I cannot fix a thing.

**Comment by AlThani** [comment]
Here is what I did,
1- opened the snapchat app.
2- took a photo.
3- clicked send.
4- clicked edit groups.
5- clicked Add new Group.
6- Snapchat app closed unexpectedly.

here is the Log: http://pastebin.com/ybcqN5W5

hope it's ok.

Thanks Marzika.

**Comment by marzika** [comment]
Logcat not Xposed log.

**Comment by AlThani** [comment]
that's alogcat I used alogcat

[aLogCat](https://play.google.com/store/apps/details?id=rs.pedjaapps.alogcatroot.app&hl=en)

**Comment by marzika** [comment]
That is the Xposed Log output of Snapprefs, I don't care about it. I need the logcat of the crash, no Snapprefs filter, nothing, just the pure crash log. If noone is capable of doing that I will close this issue.

**Comment by AlThani** [comment]
allright here is what I did:

1- opend aLogcat.
2- opened the snapchat app.
3- took a photo.
4- clicked send.
5- clicked edit groups.
6- clicked Add new Group.
7- Snapchat app closed unexpectedly.
8- opend aLogcat.
9- saved log.
[logcat](http://pastebin.com/DmWm1ASn)

If there is another way please let me know so I can try it for you.

Thanks

**Comment by CrilleTheBoss** [comment]
I gave you the pure log in one of my posts without any filters.

**Comment by marzika** [comment]
@AlThani could you please contact me on Hangouts at maaaaarz at gmail.com ? It seems to be caused on Galaxy devices with a (modified) stock ROM. I will flash one on my S3 and hopefully I can get rid of the issue.

**Comment by marzika** [comment]
I did some more digging and found this google issue: https://code.google.com/p/android/issues/detail?id=191935
It will be fixed through an OTA of your ROM/device. In the meantime you can try some of the following:
- disable system-wide animations
- recompile the app with these lines uncommented
  https://github.com/marzika/Snapprefs/blob/4237273561f1b31c04d5afdae89d3c59e3fd97a6/app/src/main/java/com/marz/snapprefs/GroupDialog.java#L113
  https://github.com/marzika/Snapprefs/blob/4237273561f1b31c04d5afdae89d3c59e3fd97a6/app/src/main/java/com/marz/snapprefs/Groups.java#L80

Also, groups can be manually added:
- make a new file in /sdcard/Snapprefs/Groups
- name it what your group name will be (it must not have any extensions)
- in the file type the name of the group, then place a ; (semicolon)
- list the usernames separated by a ; (semicolon)

Example file:
Name: Snapprefs
Content of file: Snapprefs;snapprefs;djkhaled305;mygfsaccount

**Comment by CrilleTheBoss** [comment]
I disabled all animations and recompiled with your lines uncommented but the exact same issue is still happening. It's the same logcat as before so it's not useful. But adding groups manually works! and it is not hard to do :) Thanks

**Comment by davex2012** [comment]
i want to get logcat using this command but don't know ActivityManager: Names

 adb logcat ActivityManager:I MyApp:D *:S

@marzika
