### ISSUE TITLE
[Bug] Hide best friends not working

### ISSUE THREAD

**Issue by systemallica** [marzika/Snapprefs#87]
The feature "Hide best friends" does not work. Checking or uncheking the box does not make a difference.

I'm on Android 6.0.1, let me know if you need any logs or more info.

**Comment by marzika** [comment]
I forgot to update it to 9.21.1.0 and went unnoticed since non of my test accounts have best friends. Leaving it open until I include it's class and method to the Obfuscator file.

**Comment by twwhite** [comment]
Is that an easy fix? I would really dig having that feature back asap

**Comment by marzika** [comment]
Find the method that returns a boolean depending on the current
Friend's mBestFriendIndex and change the code to hook that.

2016-05-17 1:19 GMT+02:00 Tim White notifications@github.com:

**Comment by marzika** [comment]
Thanks. https://github.com/marzika/Snapprefs/commit/ad4f11e36c5a02b0abea4d7e2a8f3e329c385d2c
