### ISSUE TITLE
[Bug] Repeated message "Image already exists"

### ISSUE THREAD

**Issue by systemallica** [marzika/Snapprefs#88]
When receiving a snap, with autosave enabled, Snapprefs says "Image already exists" and "Image saved" multiple times(like 10, flashing very quickly). Even though, the snap saves correctly, and only once, so this is not a major bug.

I took a Xposed log of me opening a snap, hope it helps:

[xposed_error_20160515_182841.txt](https://github.com/marzika/Snapprefs/files/265115/xposed_error_20160515_182841.txt)

**Comment by NightMean** [comment]
I have the same issue,I even posted video about how second story snap is not saving and u can see that on the video that the Image Saved flashing like 6 times

**Comment by krugm0f0** [comment]
I am seeing the same issue.

**Comment by JaelMalax** [comment]
I've received snap with autosave enabled. It shows "image already exist" but wasn't saved at all, instead of it was saved random story image with filename of snap sender.

**Comment by marzika** [comment]
It's due to the fact that the saving is now ASync and being called multiple times before one of them would finish. I haven't found a way yet to only call the saving once.

**Comment by systemallica** [comment]
I see, maybe then it would be possible to show the notification just once, even though the saving method is being called multiple times? Or just give an option to disable the notification(s)?

**Comment by marzika** [comment]
The notification gets called as the final step of the saving has finished or when errors occour and I am not willing to change it since it would void it's point. If you disable the notification how will you know that the saving has been done or it failed instantly?..

**Comment by systemallica** [comment]
Well, different users have different preferences. I always liked Snapprefs to be as "invisible" as possible. Once I have checked that it's saving correctly I don't need any notifications. So having an option to hide all the notifications would be very nice.

**Comment by avi312singh** [comment]
Maybe set a timer on the first asynchronous call?

**Comment by Blimeo** [comment]
Not possible

**Comment by marzika** [comment]
Thanks for the commit, I will merge it as soon as I have time to finish the update. Do anyone have an idea about how OneSky handles file updates? @avi312singh I want a permanent solution, not a bandaid one.
