### ISSUE TITLE
[ALREADY ADDED] Send local image as just-captured snap

### ISSUE THREAD

**Issue by ViRb3** [marzika/Snapprefs#9]
I am sure this is a simple enchantment and here's the theory:

When you send a local image in SC, the original behavior is it will send it as a "message" and it will behave just like sent text.
What about we override the behavior and make SC think that this snap has been just captured? From a legal point of view, this will allow using a better camera app to take a normal shot and then send it like a normal snap.

I am personally going to take on the task once I finish school as well.

**Comment by Shaxine** [comment]
You know that you can already do that!?
When you are sharing an image you can choose snapprefs and it will open SC with the photo you shared ready to send as a normal snap.

**Comment by ViRb3** [comment]
Please excuse my inability to read, I probably need an upgrade. Thanks for this feature :)
