### ISSUE TITLE
[bug] Snapshare button over Lenses

### ISSUE THREAD

**Issue by AmineI** [marzika/Snapprefs#90]
Hi !
Normally, when you use Lenses, by long tapping a head, the snapshare button will disappear to leave space to the Lenses Icons.
However, if you take a picture with a Lense and cancel that picture (dismiss / return), the Lenses icons are still enabled but the Snapshare button reappears, preventing you to take another picture 😮 
As usual I can provide logs if it helps, but I don't really think you'll need them for that kind of issue.

Thank you for your time !

**Comment by NightMean** [comment]
I just tested this and I have the same issue

**Comment by marzika** [comment]
I hide the icon when the lens stuff is starting the opening animation. If you canceled the lenses and then opened them again, the icon should be hidden. Right now, I cannot think about a proper way of checking if you had the lens selector visible after taking a snap, however I will look into it!

**Comment by kicost** [comment]
Where do you guys take dowload these testing versions :/ ?

**Comment by NightMean** [comment]
We compiled them,just google how to do it

**Comment by kicost** [comment]
i cant right now because im at the work, can someone give me a link, i won't share it .Promise!

**Comment by NightMean** [comment]
Then google how to do it later

**Comment by kicost** [comment]
man i compiled kernels and other stuff but never apk, i think im able to do it but i cant right now...can u please provide me a link?

**Comment by marzika** [comment]
No compiled builds are allowed to be shared. If you want to help, compile it yourself, if you cannot, don't. It's like that to filter out people who don't know anything about development or debugging in general. Also, the issues on GitHub are not for chit-chat.

**Comment by kicost** [comment]
OK ill try to compile it and if i do it right ,u can count on me as a tester :)

**Comment by marzika** [comment]
Fixed, by finding a new place for the button, redesign will follow.
