### ISSUE TITLE
[Question]About 9.31.1.0

### ISSUE THREAD

**Issue by TehMerkMods** [marzika/Snapprefs#94]
I Was checking out the 'update' Cause i watched you update it to 9.31.1.0 last night. Now i can see you've updated to 9.31.1.0 but nothing seems to work for me?:?

**Comment by NightMean** [comment]
Same for me,We just have to wait until it will be fully updated.I'm sure this isn't fully updated yet

**Comment by marzika** [comment]
Care to read the whole commit, not just 2 words of it?

**Comment by TehMerkMods** [comment]
Apologies Marz <3
