### ISSUE TITLE
Add easy upgrade mechanism for hooks

### ISSUE THREAD

**Issue by rapperskull** [marzika/Snapprefs#95]
Hi, I recently discovered this module, and even if I have never used it, because I installed Snapchat when the supported version was already old, I think it's a very good one and can't wait for it to support the latest version.
I want to suggest an improvement: the XInsta Xposed module has a mechanism that lets the coder to just update the hooks when a new version is out, without requiring an update to the app itself. This speeds up the update process and permits fast and relatively easy updates. Is it possible to implement something like that in Snapprefs too?

**Comment by AmineI** [comment]
Hmm, something like this : #36 ?

**Comment by rapperskull** [comment]
Yes, exactly that. I've not seen that issue, sorry.

**Comment by AmineI** [comment]
You should close it before Marz see it and mark it as a duplicate, I guess :3 .

But yep it would be a good idea to have an external file for obfuscation managing, it would make debug easier (no recompile each time you try a new class for SC) and something like "Multiple version support" by providing old obfuscations files, (even if it would be somewhat useless - Who wants to stay on an old version anyway ?).

**Comment by rapperskull** [comment]
Unfortunately I don't have permissions to close the issue, we'll have to wait.

**Comment by marzika** [comment]
https://github.com/marzika/Snapprefs/issues/36
