### ISSUE TITLE
[BUG] Sharing media from gallery

### ISSUE THREAD

**Issue by vintheword** [marzika/Snapprefs#96]
First I thank everyone who contributed to this git.

Comparing the last with the new version made camera-daemon, snapchat process and snapprefs run using less CPU and Memory.(5 to 10% less).

Now with the bug, I believe this is server related. It used to work in the past, but seems that Snapchat is refusing to accept the media and stucks at "Sending...". When it fails and you tap to send again, the conversation is deleted. If you add to your story, it gets stuck at "Posting" and sometime later deletes itself with the message "Cannot post".

**Comment by marzika** [comment]
How are you using the sharing function, please tell me your exact steps?

**Comment by AmineI** [comment]
Hey, 
I don't think it's server related since it works perfectly on my phone (just tried) :smiley:

**Comment by NightMean** [comment]
It works fine for me

**Comment by vintheword** [comment]
1- Open Snapchat
2- Tap the galerry icon above the recording button
3- Select the media (in my case is saved video from previous snap)
4- Select continue
5- Record some seconds
6- The video shows up
7- Send
8- Select my story and some other people
9- Send again
10- It stucks and deletes itself.

Moto G 2014 - CM13 6.0.1 - Xposed v80 - Snapchat 9.21.1.0

The other features behaves fine as expected.
Tried to delete data and cache but it has no affect.

The video has EXACTLY 10 seconds. Maybe is it's lenght?

**Comment by vintheword** [comment]
The other features behaves fine as expected.

**Comment by vintheword** [comment]
I just troubleshooted some more:

Sharing feature doesn`t work if the video hits the 10s mark.

But you can shoot 10s+ and post it directly from snapchat camera.

**Comment by CrilleTheBoss** [comment]
I can confirm that videos over 10s do not send

**Comment by vintheword** [comment]
https://youtu.be/b-PU3PwcOeY

aparently 9s also.

**Comment by edi194** [comment]
My friend shared 23s video from gallery on stock 1.6.5 Snapprefs build (S3 Neo + Ressurection Remix LP + Xposed v80 or 83 probably), with build from source it's not working

**Comment by marzika** [comment]
You cannot send stuff over around 2mbs it's limited on the server.
