### ISSUE TITLE
Newest update

### ISSUE THREAD

**Issue by LakuuPiipu** [marzika/Snapprefs#99]
Will you update the obsfucator classes to the latesg version with the new design? Or will you continue on this One?❤❤

**Comment by AmineI** [comment]
Hey, since he already began porting 9.31.1.0 I guess he'll look into this one first. there has been so many huges changes in the Snapchat classes since 9.21.10 that I think he'd better finish this version first.

I tried myself to look into this, I gave up after less than 5hours trying to find some important classes like "com.snapchat.android.util.SnapMediaUtils". We'll have to be patient !
- Not an issue, should be on reddit I think

**Comment by rapperskull** [comment]
I think it's useless to update the module to an old version.
One thing is that the update is ready and a new version comes out, another thing is that the update is not yet out and already old.

**Comment by NightMean** [comment]
well I just saw how the new version looks like and I don't think it's worth upgrading to old 9.31.1.0 because  the new version have redesigned buttons that I'm sure changed few things for sure.But that's on Marz of course,it's just my opinion

**Comment by dkisselev** [comment]
@AmineIzumi on a reddit post a while ago Marz mentioned that he uses a tool to auto-update the class  names. There are obviously a lot of changes on the front side, but I don't think the core backend stuff changes much (like the class structure defines a snap or a chat thread).

**Comment by AmineI** [comment]
mhh I haven't seen the new UI of snapchat. But yep let's see what he'll choose to do. Actually, Snapchat updates are pretty fast.

Yep, it's Profinder, however there has been changes on the core stuff, you can watch Marz's old live to see if you want, or test yourself by comparing the apks classes ;).

**Comment by marzika** [comment]
When the update is released it will support the latest version of Snapchat. ProGuard cannot reliably identify class chanhes between big updates and we are talking about 15-20 of them, everything have to be done manually to ensure the correct classes and methods are found.

https://github.com/marzika/Snapprefs/issues/49
